simdjson/simdjson

README.md
include/simdjson/common_defs.h

Closes https://github.com/lemire/simdjson/issues/53 - adds link to C# impl https://github.com/EgorBo/SimdJsonSharp
Also, fixes `never_inline` macro for MSVC

Add link to C# version

---

include/simdjson/parsedjson.h
src/parsedjson.cpp

None of allocation checks in `ParsedJson::allocateCapacity` would be executed, because `new` by default throws.
BTW I'm thinking about purpose of this method, and for me it looks rather like a constructor. I checked all use cases in your code and the pattern is the same: default-construct ParsedJson, then execute on that instance allocateCapacity. If all allocations were done in constructor you might use `std::unique_ptr` for memory management and also get rid of explicit `dealloce` method from API.

Use nothrow

---

.circleci/config.yml

Closes #56.
Two isolated workflow builds, one running clang-6 and the other gcc-7 using the Uubuntu 18.04 LTS as a base image. Runs with both the traditional make as well as CMake.

Build with both clang-6.0 and gcc-7.

---

CMakeLists.txt

I think I've made a mistake in the previous PR https://github.com/lemire/simdjson/pull/76
Here is a good example about VERSION/SOVERSION: https://github.com/intel/mkl-dnn/blob/master/src/CMakeLists.txt#L95-L96

CMake: SOVERSION should be 0 instead of 0.0.1

---

tests/singleheadertest.cpp

Use `aligned_free` instead of `free` to free memory allocated by aligned function.

Fix crash in singleheader test

---

tests/singleheadertest.cpp

Fix following build warning:  
```
......
Scanning dependencies of target singleheader
[ 66%] Building CXX object tests/CMakeFiles/singleheader.dir/singleheadertest.cpp.o
/home/xiaonan/simdjson/tests/singleheadertest.cpp: In function ‘int main()’:
/home/xiaonan/simdjson/tests/singleheadertest.cpp:11:22: warning: ignoring return value of ‘bool ParsedJson::allocateCapacity(size_t, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
pj.allocateCapacity(p.size());
~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
......
```

Fix build warning

---

README.md

Preview: https://github.com/myd7349/simdjson/tree/doc-vcpkg-guide#usage-using-vcpkg-on-windows-linux-and-macos
Some words are borrowed from https://github.com/googleapis/google-cloud-cpp#windows-using-vcpkg

Add instructions regarding vcpkg (fix #116)

---

include/simdjson/simdutf8check.h

- Adjust some line breaks (e.g. it seems that `10xx` consists of four elements, not three).
- Add trivial comments.

Adjust format and comments on avxcheckOverlong

---

Makefile

Aswell as some cleanup of the branching logic just below.
This way we can make `make CXXFLAGS="--coverage" allparserscheckfile` and `CXXFLAGS="--coverage" make allparserscheckfile` work interchangeably, without having to specify the default flags (`-std=C++17 -Iinclude ...` ) in C(XX)FLAGS which are already defined in the Makefile.

Allows additional C(XX)FLAGS to be passed through command line

---

tests/allparserscheckfile.cpp

Just a minor fix as it currently reports simdjson's parsing success as failures, instead of the opposite. 
I took the liberty to remove some redundant stuff aswell.
`allparsercheckfile.cpp` could do with a full clean up to separate the logic of all the different parsers, aswell as removing all the C-style code and rewrite in C++17.

 Fix parsing success check for simdjson's json_parse in allparserscheckfile.cpp and minor cleanup

---

include/simdjson/parsedjson.h
src/parsedjsoniterator.cpp

I found that some predicates is missing on `ParsedJson::iterator`. So this PR adds such a functions.

Add predicates to ParsedJson::iterator

---

src/stage1_find_marks.cpp

In some instances, this new "flatten" code improves results during stage 1 in a significant manner... (~10%).
This is maybe not the best design. Some further investigation is warranted, but this PR is evidence that there are more gains possible.
In number below, look at the number of cycles.
On skylake...
```
$ for i in jsonexamples/*.json ; do echo $i ; echo "-----current master:"; for j in {1..5} ; do ./parsemaster $i | grep "stage 1" ; done ; echo "------new code:"; for j in {1..5} ; do ./parse $i | grep "stage 1" ; done ; echo ; done
jsonexamples/apache_builds.json
-----current master:
stage 1 instructions:     358290 cycles:     104137 (49.22 %) ins/cycles: 3.44 mis. branches:         19 (cycles/mis.branch 5371.52) cache accesses:       3674 (failure          0)
stage 1 runs at 0.82 …
```

A slightly better "flatten"?

---

.appveyor.yml
.circleci/config.yml
.travis.yml
CMakeLists.txt
CONTRIBUTORS
Makefile
README.md
include/simdjson/jsonminifier.h
include/simdjson/numberparsing.h
include/simdjson/portability.h
include/simdjson/simdjson.h
include/simdjson/simdutf8check.h
include/simdjson/stage1_find_marks.h
include/simdjson/stringparsing.h
src/jsonparser.cpp
tests/CMakeLists.txt
tools/cmake/FindOptions.cmake

The changes from [PR#139](https://github.com/lemire/simdjson/pull/139) have been integrated. simdjson should now be supporting SSE4.2.
It has been tested by manually setting the json_parse_ptr to the sse implementation. Everything seems fine. The benchmark showed similar performances to the previous version. However, it would probably need to be tested on a real sse-only machine.
The SIMDJSON_PADDING has not been modified. I'm looking for an intelligent way to modify its value on runtime. However, it does not seem to cause any problem right now.
simdutf8check also generates a lot of warnings about unused functions. Changes will be made.

SSE integration (PR#139)

---

benchmark/minifiercompetition.cpp
benchmark/parseandstatcompetition.cpp

The scripts for running the benchmarks were failing because the makefiles were not able to compile the cpp files. On further investigation, I found that there were some scope errors, and on fixing those I was able to compile and run the benchmarks.
This commit is already included in the recent PR by @jkeiser, just making this a separate PR for better visibility.

Fix benchmark cpp files

---

benchmark/parse.cpp
benchmark/statisticalmodel.cpp
include/simdjson/parsedjson.h
include/simdjson/simdutf8check_haswell.h
include/simdjson/simdutf8check_westmere.h
include/simdjson/stage1_find_marks.h
include/simdjson/stage1_find_marks_haswell.h
include/simdjson/stage1_find_marks_westmere.h
src/parsedjsoniterator.cpp
tests/jsoncheck.cpp
tools/json2json.cpp
tools/jsonstats.cpp
tools/minify.cpp

This fixes all the "obvious" warnings on VS2019: unused variables in the catch() statements, assigning const >= 128 to a signed byte, and a weird one that wanted `noexcept` in a couple of constructors for some reason (which I was happy to provide, since that's been around a while in C++).
Two warnings remain:
* It thinks there's a buffer overrun when depth_capacity is 1 [in parsedjsoniterator.cpp](https://github.com/lemire/simdjson/blob/master/src/parsedjsoniterator.cpp#L26):
`Warning	C6386	Buffer overrun while writing to 'depth_index':  the writable size is 'pj.depth_capacity*16' bytes, but '32' bytes might be written.`
* C++ uses exceptions, but we haven't turned on unwind semantics with `/EHsc`. I'm not sure whether we *wanted* unwind semantics turned on, because I know they impact …

Fix most warnings on VS2019

---

include/simdjson/jsonparser.h

A simple change that prevents clang-format to automatically move sysinfoapi.h before windows.h.

preventing clang-format to move sysinfoapi.h

---

.gitattributes

This gets `docker build` running successfully on Windows. `.sh` and `Makefile` really want linefeeds.
Generated from https://www.richie-bendall.ml/gitattributes-generator/ with Common and C++ as parameters. I left json as binary since that is intentional.

Default Unix files to LF instead of CRLF

---

.dockerignore

Right now `docker build` is sending everything from .git and any other random subdirectory. This creates a whitelist that only sends in stuff we need. (NOTE: I'm not actually sure we even need all that, but this makes it fast enough I quit worrying about it :))

Make Docker start much faster

---

include/simdjson/portability.h
include/simdjson/stage1_find_marks_common.h
include/simdjson/stage2_build_tape_common.h
include/simdjson/stringparsing_arm64.h
include/simdjson/stringparsing_common.h
include/simdjson/stringparsing_haswell.h
include/simdjson/stringparsing_westmere.h
src/stage1_find_marks.cpp
src/stage2_build_tape.cpp

This fixes the Visual Studio Intellisense errors by moving the namespace stuff into the .h file. Basically Intellisense wants to read the .h file by itself, without considering the fact that it might be included from within a `namespace {}` directive.
I'm not thrilled at having to pass two variables. I think there might be a way to avoid it by using a `template<> const char* REGION_TARGET<Architecture::WESTMERE> = "avx2,bmi,pclmul";` and use `TARGET_REGION(REGION_TARGET<TARGETED_ARCHITECTURE>)`, but I don't know if the pragma would support using a const char*.
If I get time to learn about [C++ Hint Files](https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=vs-2019), that might be an alternate way to fix Intellisense without changing the codebase. But that has drawbacks …

Fix Intellisense errors opening .h files on VS2019

---

.dockerignore

I'm not sure how it was working on my machine, but .git is needed to bring in submodules. Docker is failing right now.
There are better ways to do the Dockerfile that don't copy so much (volume mounts), but right now I just want it to work :)) Even with .git it's WAY faster than before though, probably because of the VS folder on my machine or something. 40M transfer instead of 700M.

Bring .git into docker

---

src/jsonparser.cpp

https://github.com/lemire/simdjson/issues/251
https://github.com/yandex/ClickHouse/issues/6285#issuecomment-517970722

Make dynamic dispatch free of TSan warnings

---

.drone.yml
Makefile
benchmark/CMakeLists.txt
benchmark/Dockerfile
benchmark/parse.cpp
benchmark/perfdiff.cpp
scripts/checkperf.sh

This adds a performance degradation test in .drone.yml (hopefully, we'll see what happens when the PR runs :)). It checks out `master` and compares to this branch, and fails if it degrades more than 10%. Advice requested on what tolerance to use here--0% doesn't work because variance. I expect we'll also want to track it over time to make sure we don't consistently lose 1% here, 2% there until it adds up
To try to mitigate variance in performance numbers (especially in CI), I added a few things. Suggestions / feedback welcome:
* The `checkperf` is a separate step, with the hopes that we can re-run it if we believe we got a spurious result.
* We compile and measure master and current-branch performance in the same machine / container / CI run, eliminating the possibility of being assigned …

check for performance degradation in CI

---

.circleci/config.yml
Makefile
benchmark/perfdiff.cpp
scripts/checkperf.sh

Fixes the big things we wanted out of #272:
- Compare against v0.2.1 instead of master
- Do comparison up to 6 times, fail iff throughput < reference throughput all 6 times
- Check no-AVX perf as well

Make perf validation more stable, check no-AVX as well

---

benchmark/perfdiff.cpp

Since we run the performance check 8 different times in different CIs, we have to run a 7th interleaved attempt to keep the probability of false failure in the same range. I also increased the threshold to 0.5% while we were at it. False failure should be few and far between with this change, but should still reliably detect reduced performance above a certain noise level.

Lower the bar for performance check

---

include/simdjson/simd_input.h
include/simdjson/simd_input_arm64.h
include/simdjson/simd_input_haswell.h
include/simdjson/simd_input_westmere.h
include/simdjson/simdutf8check.h
include/simdjson/simdutf8check_arm64.h
include/simdjson/simdutf8check_haswell.h
include/simdjson/simdutf8check_westmere.h
include/simdjson/stage1_find_marks.h
include/simdjson/stage1_find_marks_common.h

This converts simd_input to use struct methods instead of functions. It doesn't seem to make anything slower, and *definitely* removes a lot of ceremony, particularly around template parameters: since the parameters are taken care of as a part of the type, the methods get them for free.
But if there is a general ethos here to only use C functions or something, I'll abandon the PR, that's why I only converted such a small portion :)

Use methods instead of functions for simd_input

---

.gitignore

This PR ignores files of cmake, as well as C++ in #278.

Update .gitignore for cmake files

---

benchmark/perfdiff.cpp

Fixes https://github.com/lemire/simdjson/issues/298
The idea is that we run 7 tests with the reference code, 7 tests with the new code. If all 7 new tests are worse than all 7 reference tests, then we *know* (???) something is fishy.
If we just have overlapping values, then we can't know for sure that there is a problem.
This will only pick up the *obvious* performance regressions, but I don't think this can be helped. And it is already useful to catch the really big regressions.

This should lower false positives of performance checks

---

src/haswell/stage1_find_marks.h
src/westmere/stage1_find_marks.h

This is a minor change to switch the structurals calculation to do each input register separately rather than interleaving the operations, which makes the algorithm a bit easier on the eyes. At least on avx, I don't see actual perf degradation.
Apologies for the rate of PRs. It should settle down a bit now that I've figured out how to get decent perf numbers on my Windows machine. I feel a lot more confident about performance not regressing.

Use non-interleaved map() to make structurals clearer

---

.drone.yml
scripts/checkperf.sh
src/arm64/simd_input.h
src/arm64/simdutf8check.h
src/arm64/stage1_find_marks.h
src/haswell/simd_input.h
src/haswell/simdutf8check.h
src/haswell/stage1_find_marks.h
src/simd_input.h
src/westmere/simd_input.h
src/westmere/simdutf8check.h
src/westmere/stage1_find_marks.h

This is purely a draft, created so that I can see its effect on CI (and test on ARM). Given how interleaving seemed to make a difference with the equivalent stage 1 PR, I'd like to see if interleaving will speed up utf8 checking here.
Results:
- master vs. v0.2.1: 3/20 SSE failures, 0/20 AVX failures
- master vs. v0.2.1: 0/20 SSE failures, 1/20 AVX failures

Use simd_input generic methods for utf8 checking

---

.gitignore
benchmark/parse.cpp
include/simdjson/common_defs.h
scripts/checkperf.sh
src/arm64/simd_input.h
src/arm64/stage1_find_marks.h
src/generic/stage1_find_marks.h
src/generic/stage1_find_marks_flatten.h
src/haswell/simd_input.h
src/haswell/simdutf8check.h
src/haswell/stage1_find_marks.h
src/westmere/simd_input.h
src/westmere/stage1_find_marks.h

This brings together all of the performance patches except [aligned loads](https://github.com/lemire/simdjson/pull/315), and even does the loop unrolling a little better (interleaving the two iterations for another 1-2% boost or so). All performance impacts are understood (at least, I have a story that purports to explain them :)) and the reordering in particular is explained in code comments.
Across all files (see [comment below](https://github.com/lemire/simdjson/pull/317#issuecomment-534256380)), it gives a 5% overall throughput improvement on average on my AVX2 Kady Lake R processor, or 1-9% improvement depending largely on the density of json elements in the file. Stage 1's improvement is 11-20%, averaging around 15%. Each of the individual patches was confirmed to have a positive …

Combined performance patch (5% overall, 15% stage 1)

---

include/simdjson/parsedjson.h
src/parsedjson.cpp

As per [issue 320](https://github.com/lemire/simdjson/issues/320), this PR improves the const correctness of the `ParsedJson` interface by allowing one to call (more) print/query functions on immutable objects.

Improved const correctness for ParsedJson interface

---

include/simdjson/parsedjsoniterator.h
include/simdjson/portability.h

As per [issue 323](https://github.com/lemire/simdjson/issues/323), this PR introduces a case insensitive key lookup for the iterator. The proposal refactors `move_to_key` into a private `move_to_key_impl` which takes not only the key but a comparator. This way, there's no code duplication and both `move_to_key` and the newly added `move_to_key_insensitive` are added cleanly.
In principle, there should be zero overhead from the comparator.

case insensitive move_to_key

---

src/numberparsing.h

I did not add a test case, since it is only detected if undefined behaviour sanitizer is used. The fuzzer will find it.
The offending input is:
```
4E-2147483674
```
detected by oss-fuzz
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18714

fix integer overflow in subnormal_power10

---

.github/workflows/fuzzers.yml
fuzz/build_fuzzer_variants.sh

This is a github action CI job aiming to make sure that bugs that are easy to find through fuzzing are detected already at the pull request stage.
If this job runs successfully, it means that
- the fuzzers are possible to build in a number of variants (with/without avx, with/without sanitizers)
- the corpus can be executed by the fuzzers, without problems
- the corpus can be executed by a reproduce build, executed through valgrind
- easy to find test cases not already in the corpus, are added to the corpus for the next run by storing them externally
To get this running, github actions needs to be enabled, and the password for logging in to bintray needs to be set (let's exchange that via email, or possibly make me an admin on this repo).
It is possible to see this in action over here: …

run short fuzzing and valgrind in github action

---

.gitignore
src/arm64/simd.h
src/arm64/stage1_find_marks.h
src/generic/stage1_find_marks.h
src/haswell/simd.h
src/haswell/stage1_find_marks.h
src/westmere/simd.h
src/westmere/stage1_find_marks.h

On Westmere and ARM64, there is a real performance increase when you step through the file 64 bytes at a time rather than 128.
Westmere: 1.744035 -> 1.810536 (3.8% perf improvement)
ARM64: 0.143128 -> TBD (on [this patch](https://github.com/lemire/simdjson/pull/365) it produced a 0.5% improvement, but that was after the UTF-8 changes were applied)
Wanted to pull this out so that the other patch can stand on its own.

Run stage 1 in 64-byte increments on Westmere and ARM

---

.appveyor.yml
.circleci/config.yml
CMakeLists.txt
benchmark/CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt

After recent discussions on threads in the cmake build, this cleans up the cmake
threading handling and makes it configurable.
Update: the CI jobs seem to work, this PR is ready for review!

Make threads optional in the cmake build

---

.github/workflows/fuzzers.yml

This is to fulfill that the initial seed corpus and associated scripts used by oss-fuzz stay healthy.
I test ran this in the github action on my github clone, and it worked as expected. It adds 30 seconds or so to the CI job.
Closes #370

run the oss fuzz initial seed corpus in CI

---

Makefile
src/arm64/bitmask.h

On some ARM platforms, PMULL is slow.
In theory, PMULL has a throughout of one instruction per cycle with a latency of 4 or 5 cycles on some platforms like the [A53](http://infocenter.arm.com/help/topic/com.arm.doc.uan0015b/Cortex_A57_Software_Optimization_Guide_external.pdf) or 4 cycles on  the [A72](http://infocenter.arm.com/help/topic/com.arm.doc.uan0016a/cortex_a72_software_optimization_guide_external.pdf). That's better than the portable approach which might compile to the following...
```
eor x0, x0, x0, lsl 1
eor x0, x0, x0, lsl 2
eor x0, x0, x0, lsl 4
eor x0, x0, x0, lsl 8
eor x0, x0, x0, lsl 16
eor x0, x0, x0, lsl 32
```
I would expect this sequence to havre a latency of 6 cycles... However, a pure latency analysis might be misleading here.
Which is better, six calls to `eor` or …

[for discussion] PMULL is sometimes slow on ARM64, let us not rely on it?

---

Makefile
benchmark/benchfeatures.cpp

This takes into account the actual miss rate, displaying it (since it makes such a huge difference). Before, we estimated miss rate == flip rate, when miss rate can vary by many other code factors.
I also used it to adjust the effectiveness rating, adjusting for the misses that went wrong. Turns out if we account for the miss rate, our new estimate is pretty accurate (within 5%), even if we were 20% off without adjusting. indicating the feature measurement is probably working pretty well. Sample skylake output (it outputs Markdown tables because we paste them so often):
> Features in ns/block (64 bytes):
> 
> | Stage    |     Base | 7 Struct |    UTF-8 |  15 Str. | 16+ Str. |   7 Struct Miss |      UTF-8 Miss |    15 Str. Miss |   16+ Str. Miss |
> …

Incorporate actual miss rate in feature benchmarks

---

.github/workflows/fuzzers.yml

this is to get more debug output from cases like this:
https://github.com/lemire/simdjson/commit/c9cd8e62111a7b25c240bea08a175de5ec6f8def/checks?check_suite_id=351526761
https://pipelines.actions.githubusercontent.com/gFSIASDqcDhMdHkcuMJEdsUcdOsOrVBr8d56BjAkszcoMkibGp/_apis/pipelines/1/runs/274/signedlogcontent/3?urlExpires=2019-12-21T18%3A50%3A08.3387613Z&urlSigningMethod=HMACV1&urlSignature=DVF3u4jEs81xJP6Hmi8LLQlLOztJke8MsP62J0MXruQ%3D
which ends with:
2019-12-20T23:08:42.6830393Z ../src/generic/numberparsing.h:243:31: runtime error: 1e+311 is outside the range of representable values of type 'double'
2019-12-20T23:08:42.6836790Z SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/generic/numberparsing.h:243:31 in
2019-12-20T23:08:42.6837715Z MS: 2 …

try to output failed fuzz cases

---

.github/workflows/fuzzers.yml
fuzz/CMakeLists.txt
fuzz/NullBuffer.h
fuzz/build_fuzzer_variants.sh
fuzz/fuzz_dump.cpp
fuzz/fuzz_dump_raw_tape.cpp
fuzz/fuzz_print_json.cpp
fuzz/measure_coverage.sh

after looking at the coverage report available at
https://storage.googleapis.com/oss-fuzz-coverage/simdjson/reports/20191222/linux/src/simdjson/report.html
Here is the related ticket: https://github.com/lemire/simdjson/issues/368

add new fuzzers for print_json and dump_raw_tape

---

.drone.yml
include/simdjson/parsedjson.h
include/simdjson/parsedjsoniterator.h
scripts/checkperf.sh
src/generic/stage1_find_marks.h
src/generic/stringparsing.h
src/parsedjson.cpp

This switches from owning raw pointers to use unique_ptr.
This simplifies the code.
Background:
- https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-raii
- https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-ptr
- https://en.cppreference.com/w/cpp/language/rule_of_three

use unique_ptr in class parsedjson

---

.github/workflows/fuzzers.yml
include/simdjson/stage2_build_tape.h
src/arm64/stage2_build_tape.h
src/generic/stage2_build_tape.h
src/generic/stage2_streaming_build_tape.h
src/haswell/stage2_build_tape.h
src/westmere/stage2_build_tape.h

This factors the unified_machine as far as I could without regressing performance (it actually increases stage 2 throughput by about 1% on my machine). I removed as many macros as possible (we're down to FAIL_IF and GOTO now, which use `return` and `goto` statements and thus couldn't be turned into functions).
Goals
-----
1. **No performance change:** Regress not a single digit of performance.
2. **No functional change:** Run the exact same code in the exact same order, as much as possible.
3. **Share code internally:** Remove as much redundant code as possible using shared functions.
4. **Fewer macros:** Use more functions and fewer macros.
5. **Factor the streaming parser too:** Share as much code as possible between the streaming and non-streaming parser.
Code Highlights
------------- …

Refactor stage 2 into structural_parser class

---

.gitignore
include/simdjson/simdjson.h

```cpp
// source: github.com/martinmoene
// C++ language version detection (C++20 is speculative):
// Note: VC14.0/1900 (VS2015) lacks too much from C++14.
#ifndef SIMDJSON_CPLUSPLUS
#if defined(_MSVC_LANG) && !defined(__clang__)
#define SIMDJSON_CPLUSPLUS (_MSC_VER == 1900 ? 201103L : _MSVC_LANG)
#else
#define SIMDJSON_CPLUSPLUS __cplusplus
#endif
#endif
#define SIMDJSON_CPP98_OR_GREATER (SIMDJSON_CPLUSPLUS >= 199711L)
#define SIMDJSON_CPP11_OR_GREATER (SIMDJSON_CPLUSPLUS >= 201103L)
#define SIMDJSON_CPP14_OR_GREATER (SIMDJSON_CPLUSPLUS >= 201402L)
#define SIMDJSON_CPP17_OR_GREATER (SIMDJSON_CPLUSPLUS >= 201703L)
#define SIMDJSON_CPP20_OR_GREATER (SIMDJSON_CPLUSPLUS >= 202000L)
```

C++ language version detection 

---

benchmark/benchmarker.h
benchmark/event_counter.h
benchmark/json_parser.h
benchmark/parse.cpp

Amazingly, stage 2 alone can be slower than stage 1 and stage 2 together.
Look...
```
$ cd scripts/ruby
$ ruby kostya_large.rb
$ cd ..
$ cd ..
$ make parse
$ ./parse -n 10 scripts/1.json 
number of iterations 10 
scripts/1.json
==============
1742429 blocks -  111515519 bytes - 15728645 structurals ( 14.1 %)
special blocks with: utf8         0 (  0.0 %) - 0 structurals         0 (  0.0 %) - 1+ structurals   1742430 (100.0 %) - 8+ structurals   1716436 ( 98.5 %) - 16+ structurals         0 (  0.0 %)
special block flips: utf8         0 (  0.0 %) - 0 structurals         0 (  0.0 %) - 1+ structurals         0 (  0.0 %) - 8+ structurals     51988 (  3.0 %) - 16+ structurals         0 (  0.0 %)
All Stages
|    Speed        :  44.6178 ns per block ( 99.92%) -   0.6972 ns per byte -   4.9428 ns …
```

Instead of emulating the whole parsing as stage 1 + stage 2, let us benchmark the real thing.

---

src/generic/stage2_build_tape.h

I think that this costs us nothing and makes the code future-proof.

I think that i and idx should be of type size_t (64-bit).

---

CMakeLists.txt
tests/CMakeLists.txt

@Lekensteyn  wrote
"LTO cannot be checked unless the language is specified with the
'project' option. "
Let us try to specify the language, then?
https://github.com/lemire/simdjson/pull/449

Making the project tag in simdjson more explicit

---

Makefile
benchmark/CMakeLists.txt
benchmark/get_corpus_benchmark.cpp

We have a PR that proposes to streamline the get_corpus function, but we have no benchmark. Let us create one.

Adding a "get_corpus" benchmark.

---

src/arm64/simd.h
src/generic/stage1_find_marks.h

When simdjson searches for escaped quotes like `\"`, it produces a list of escaped non-backslash characters to rule out false positives like `\\\\"`. This patch redoes the algorithm to produce the full list of escapes (even though it's not needed), which turns out to improves performance.
It reduces stage 1 instructions by around 10%, and improves overall throughput by around 2% (and stage 1 by 7%), on Skylake. The speedup is largely achieved by focusing on `+`'s effect on the mask rather than the carry bit, removing the need for one of the two legs of the calculation (instead of both even and odd, we just do one `+`).
The current algorithm uses `+` to find the end of a series of backslashes based on its start. To correct for series with an even number of backslashes, it does this twice: …

Find all escaped characters with fewer instructions

---

.gitmodules
CMakeLists.txt

This doesn't change the default of -DSIMDJSON_GOOGLE_BENCHMARKS=OFF, but it does disable all building of the Google Benchmark tests, bringing compile time back down to normal. It also removes the dependencies/googletest submodule.
At this point, the only real extra time taken is in `cmake`--an extra 8 seconds to detect features the first time it's run. `make` is a couple seconds longer purely because it is building the actual `bench_parse_call` executable. Since cmake is off the main dev path, we probably could enable it without hurting our experience after this.

Remove googletest entirely as benchmark dependency

---

.gitignore
benchmark/CMakeLists.txt
benchmark/bench_dom_api.cpp
include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h
src/document.cpp
src/error.cpp
src/generic/stage1_find_marks.h
src/haswell/simd.h
src/westmere/simd.h
tests/CMakeLists.txt
tests/basictests.cpp
tests/readme_examples.cpp

This enables the following scenarios, tested in `make run_basictests`:
```c++
string json(R"( [ 1, 2, 3 ] )");
document doc = document::parse(json);
for (uint64_t value : document::array(doc)) {
cout << value << endl;
}
```
```c++
string json(R"( { "a": 1, "b": 2, "c": 3 } )");
document doc = document::parse(json);
for (auto [key, value] : document::object(doc)) {
// key is a string_view, value can be converted to whatever: int64_t(value) or (const char*)value, for example
}
```
It has the usual `auto [value, error] = ...` semantics for all calls. (Iteration cannot fail, though the case to `document::array` / `document::object` can.) `as_object()`, `as_array()`, etc. are the methods to call instead of conversion.)
A lot more stuff has doxygen style documentation now.

Document navigation API

---

benchmark/bench_parse_call.cpp
include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h

We renamed InvalidJson to invalid_json to follow the snake_case rule ,,, but we're using this class for all errors in simdjson, including allocation and DOM navigation. simdjson_error better describes it. This is a straight search and replace.
This is backcompat safe, since we haven't actually released invalid_json (it's new in master since 0.2), so nobody can have a dependency with `try { } catch (invalid_json j) { }`

Rename invalid_json to simdjson_error

---

README.md
benchmark/bench_parse_call.cpp
benchmark/benchmarker.h
benchmark/parse_stream.cpp
include/simdjson/document.h
include/simdjson/implementation.h
include/simdjson/inline/document.h
include/simdjson/inline/document_stream.h
include/simdjson/jsonparser.h
tests/basictests.cpp
tests/jsoncheck.cpp
tests/numberparsingcheck.cpp
tests/pointercheck.cpp
tests/readme_examples.cpp
tests/singleheadertest.cpp
tests/stringparsingcheck.cpp
tools/json2json.cpp
tools/jsonpointer.cpp

* Update parse() and parse_many() to automatically reallocate when encountering documents larger than capacity
* Add max_capacity so users can control or eliminate automatic reallocation
* Expose separate set_capacity() and set_max_depth() methods on parser
This is based on issue #517. Copy/pasting the reasoning and scenarios here:
In our current API, you have to decide on a maximum document size before you parse:
```c++
document::parser parser;
if (parser.allocate_capacity(1024)) { exit(1); }
const document &doc = parser.parse(json, json_len);
```
This is distracting for tutorials and is not ideal for use cases where the document size is unknown up front (e.g. servers). I propose we introduce automatic bumping of memory, up to a particular maximum.
With this proposal, you don't have to …

Automatically allocate memory as needed in parse

---

benchmark/parseandstatcompetition.cpp
benchmark/statisticalmodel.cpp
include/simdjson/common_defs.h
include/simdjson/document.h
include/simdjson/document_iterator.h
include/simdjson/inline/document.h
include/simdjson/inline/document_iterator.h
include/simdjson/jsonioutil.h
include/simdjson/jsonminifier.h
include/simdjson/simdjson_version.h
tools/jsonstats.cpp

This moves the top-level constants we define into the simdjson namespace, and adds documentation for them. This handles the public-API-facing part of #523.

Make #defines into simdjson::constants

---

include/simdjson/document_stream.h
tests/basictests.cpp

Currently, document::stream contains an attribute that is a reference:
```
document::parser &parser;
```
Yet we try to have it default on the move operator:
```
stream &operator=(document::stream &&other) = default;
stream &operator=(const document::stream &) = delete; // Disallow copying
```
```
stream(document::stream &&other) = default;
stream(const document::stream &) = delete; // Disallow copying
```
I am not sure what the move is supposed to do with the reference.
I cannot find where we test the copy constructor and assignment. This has been concerned that it is either dead code or buggy code.

Adding a check to see whether document::stream copy constructor and assignment actually compile

---

benchmark/benchmarker.h
benchmark/perfdiff.cpp

The recent allocation patch changed how `parse` calls allocation, and did it wrongly. (Since it's calling stage1/stage2 internally, automatic allocation won't happen for the benchmarker.) Right now, it crashes every time you run it.
I have no IDEA how this could get in. I have not checked any of these patches in until all the tests show green, and I *know* we run the performance checker. I'll look into it, maybe there's a false positive when it crashes or something.

Fix parse benchmarker

---

README.md
benchmark/bench_dom_api.cpp
include/simdjson/document.h
include/simdjson/document_parser.h
include/simdjson/inline/document.h
include/simdjson/inline/document_iterator.h
include/simdjson/internal/jsonformatutils.h
tests/basictests.cpp
tests/readme_examples.cpp

This patch supports `cout << doc` as well as any element, object or array in the document:
```c++
const document &doc = parser.parse(json);
cout << doc;
document::element foo = doc["foo"];
cout << foo;
```
Further, in keeping with other APIs, we support << against the results of operations that may fail. In case of failure, `<<` will rethrow the exception. It allows super clean syntax when combined with the other patches:
```c++
cout << parser.parse(json);
cout << parser.parse(json)["foo"];
```
I added tests for this, as well.
Fixes #528.

Support cout << json

---

README.md
include/simdjson/document.h
include/simdjson/padded_string.h
tests/readme_examples.cpp

This makes one-line examples with embedded text much easier to read, and also encourages the initialization of padded strings. Can be used like this:
```c++
cout << document::parse("[1,2,3]"_padded);
```
Or this:
```c++
auto json = "[1,2,3]"_padded; // Creates a `padded_string` type
cout << document::parse(json);
```
Fixes #527.

Support document::parse("[1,2,3]"_padded)

---

Makefile
src/CMakeLists.txt
src/arm64/stage2_build_tape.h
src/generic/atomparsing.h
src/generic/numberparsing.h
src/generic/stage2_build_tape.h
src/generic/stage2_streaming_build_tape.h
src/generic/stringparsing.h
src/haswell/stage2_build_tape.h
src/stage2_build_tape.cpp
src/westmere/stage2_build_tape.h

In a first move towards a "stage 1 sax" for minification/pretty printing, I made a structural_iterator interface that takes care of advance_char() over structurals, and separated that from stage 2.
It buys us 5% overall (and 10% in stage 2), on Kady Lake R. That wasn't my intent at all :)
I'm guessing that, by peeling off `structural_indexes` into a specific member, the compiler now feels justified in enregistering it, and it's used often enough to make a difference.
```
jkeiser@JKEISER-THINKPAD:~/simdjson$ make parse && ./parse jsonexamples/twitter.json -n 20000
g++ -msse4.2 -mpclmul  -std=c++17  -pthread -Wall -Wextra -Wshadow -Ibenchmark/linux -O3 -Isrc -Iinclude  -o parse benchmark/parse.cpp src/simdjson.cpp 
perf_event_open: Invalid argument
number of iterations 20000 …
```

Split structural iteration from stage 2 parser (5% overall)

---

CONTRIBUTING.md
README.md
doc/tape.md
include/simdjson/document_iterator.h
include/simdjson/inline/document_iterator.h
include/simdjson/jsonstream.h
singleheader/simdjson.h

The most important of these is the fix for the file link for `simdjson.cpp` in the README.

Fix typos.

---

README.md
fuzz/Fuzzing.md

This puts back the fuzzer badge.
Note that I removed the badge since the link referred to code that we no longer had. I now understand that "all issues" includes "closed issues" and is apparently the default. For obvious reasons, I'd rather not to have to deal with "fixed issues", so let us link to just the open issues.
I am not going to merge this PR since I see that @pauldreik is working on this as well.

Putting back the fuzzer badge and extending the documentation.

---

README.md
include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h
include/simdjson/inline/error.h
tests/pointercheck.cpp

This adds support for JSON pointer in the DOM navigation model. Two things to note:
1. It deliberately doesn't support the # URI fragment syntax. As far as I can tell, that's easier handled by just URI escaping first, and it's also conflating two different syntaxes in a single interface.
2. This patch preserves support for backslash escapes, but as far as I can tell, JSON pointer doesn't support those ...

Support JSON pointer in DOM navigation model

---

tools/jsonpointer.cpp

Fixes #599. Also shows the error when it can't find something.
When running `./jsonpointer jsonexamples/small/demo.json /Image/Width /Image/Height /Image/IDs/2 /Image/IDs/10`:
```json
[
{"jsonpath": "/Image/Width","value":800},
{"jsonpath": "/Image/Height","value":600},
{"jsonpath": "/Image/IDs/2","value":234},
{"jsonpath": "/Image/IDs/10","error":"Attempted to access an element of a JSON array that is beyond its length."}
]
```
```json
[
{"jsonpath": "/Image/Width",
"value":800}
,
{"jsonpath": "/Image/Height",
"value":600}
,
{"jsonpath": "/Image/IDs/2",
"value":234}
,
null
]
```

Update jsonpointer tool to use new API

---

include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h
tests/pointercheck.cpp

Since it's not a part of JSON pointer.
Also speed up non-escaped key lookup by not copying keys unless there is an escape character.
Fixes #604 and #610.

Remove backslash unescaping from JSON pointer implementation

---

include/simdjson/padded_string.h
tests/basictests.cpp

This makes _padded work when you don't do `using namespace simdjson;`:
```c++
#include "simdjson.h"
int main(void) {
simdjson::padded_string json = "[1,2,3]"_padded;
}
```
I modified one of the basictests to use it, to confirm it failed before and succeeded after.

Make _padded available without using namespace simdjson

---

include/simdjson/jsonparser.h

This deprecates these methods. It does not deprecate the name `JsonParser`, mainly because doing that caused me lots of warnings last time I did it. But json_parse and build_parsed_json should be enough to warn existing users off.

Deprecate json_parse() and build_parsed_json()

---

include/simdjson/document.h
include/simdjson/inline/document.h
tools/jsonstats.cpp

Fixes issue https://github.com/simdjson/simdjson/issues/600
The output is now is JSON (duh).
I have added a few useful stats such as the number of keys, their maximal length, and the maximum depth of the document and so forth...
```
$./jsonstats jsonexamples/twitter.json 
```
```javascript
{
"integer_count"            =       2108,
"float_count"              =          1,
"string_count"             =      18099,
"ascii_string_count"       =       5263,
"backslash_count"          =       1230,
"non_ascii_byte_count"     =      95406,
"object_count"             =       1264,
"maximum_object_size"      =         40,
"array_count"              =       1050,
"maximum_array_size"       =        100,
"null_count"               =       1946,
"true_count"               =        345,
"false_count" …
```

Fixes issue 600

---

benchmark/parseandstatcompetition.cpp

This ports over the ./parseandstatcompetition benchmark to the new API. Unfortunately, it is one instance where the new API carries some overhead... or at least the way I use it...
```
$ ./parseandstatcompetition jsonexamples/twitter.json 
simdjson                                        :    1.629 cycles per input byte (best)    1.650 cycles per input byte (avg)    2.090 GB/s (error margin: 0.027 GB/s)
simdjson (new API)                              :    1.776 cycles per input byte (best)    1.785 cycles per input byte (avg)    1.917 GB/s (error margin: 0.010 GB/s)
RapidJSON                                       :    7.849 cycles per input byte (best)    7.869 cycles per input byte (avg)    0.434 GB/s (error margin: 0.001 GB/s)
sasjon                                          :    4.611 …
```

Fixing issue 601

---

CONTRIBUTING.md
HACKING.md
README.md
doc/basics.md
doc/implementation-selection.md
doc/performance.md

This breaks up the usage docs, performance docs, and "how to hack simdjson" docs into separate files. Also has a separate section for the implementation selection API. Makes everything more digestible, IMO.
The only actual content I changed was, I added an explanation of the source tree in HACKING.md and fixed a missing space from my `s/simdjson /The simdjson library/g` in the last checkin.

Split docs into multiple files

---

benchmark/distinctuseridcompetition.cpp

Trying to solve https://github.com/simdjson/simdjson/issues/623
Current solution is not satisfactory since the performance is down by 2x:
```
$ ./distinctuseridcompetition  jsonexamples/twitter.json 
...
simdjson (just dom)                             :    0.284 cycles per input byte (best)    0.301 cycles per input byte (avg)   14.686 GB/s (error margin: 0.845 GB/s)
simdjson(justdom,newapi)                        :    0.485 cycles per input byte (best)    0.504 cycles per input byte (avg)    8.651 GB/s (error margin: 0.365 GB/s)
```

Trying to migrate distinctuseridcompetition to new API.

---

benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp
benchmark/distinctuseridcompetition.cpp
include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h
tests/basictests.cpp
tests/errortests.cpp
tests/pointercheck.cpp
tests/readme_examples.cpp
tools/jsonpointer.cpp

We've talked about this elsewhere but I don't believe we came to a conclusion. Now that it's easier to create and use a parser, I think we should remove `document::load()` and `document::parse()` and leave the `parser` interface as the only way to do it:
```c++
document::parser parser;
parser.load(...)
```
* **Con -- More lines:** document::parse() is one line instead of two. (On the other hand, it's a pretty simple extra line.)
* **Pro -- It makes the default way the right way:** When you grow out of a simple use case, you're going to want to keep the parser around. But if your original use case uses `document::parse()`, the least friction is to copy/paste `document::parse()` all over the place. People tend to do whatever the least friction is.
* **Pro -- Easier to reason about …

Remove document::parse and document::load

---

.circleci/config.yml
include/simdjson/common_defs.h
include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h
include/simdjson/inline/padded_string.h
include/simdjson/padded_string.h
scripts/testjson2json.sh
tests/allparserscheckfile.cpp
tests/basictests.cpp
tests/integer_tests.cpp
tests/jsoncheck.cpp
tests/numberparsingcheck.cpp
tests/singleheadertest.cpp
tests/stringparsingcheck.cpp
tools/jsonpointer.cpp

This uses the C++ lvalue operator to enforce moves in and out of simdjson_result, allowing us to use a single class for owned and non-owned things. We never call std::move() anymore, instead relying on `forward` to figure out whether to copy (in the case of references) or move (in the case of values).
Specifically:
* `tie()` can only be done on an rvalue now (i.e. once you tie() you have to throw away the simdjson_result).
* `operator T` is changed to `operator T&&` and requires the simdjson_result to be an rvalue.
* The constructor always takes `T&&`, requiring the input to be an rvalue.
With that, we now use simdjson_result<padded_string> for load() and can remove simdjson_move_result<T> entirely.
Fixes https://github.com/simdjson/simdjson/issues/622

Remove simdjson_move_result

---

benchmark/distinctuseridcompetition.cpp
benchmark/minifiercompetition.cpp
benchmark/parseandstatcompetition.cpp
benchmark/parsingcompetition.cpp
include/simdjson/common_defs.h
include/simdjson/document.h
include/simdjson/inline/document.h
include/simdjson/inline/parsedjson_iterator.h
tests/allparserscheckfile.cpp
tests/basictests.cpp

We're trying to move to a world where the parser doesn't store error information anymore, it's returned from parse and forgotten, so that there's only one place errors exist. To do that, we have to deprecate these methods. (They won't do what you want unless you're using json_parse and build_parsed_json anyway--we only set them from those methods--but deprecating them makes it harder to accidentally do it.)
This patch also fixes any makes the competitions compile without warnings. At this point `make everything` compiles with no warnings!

Deprecate error/valid methods on parser

---

README.md
benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp
benchmark/distinctuseridcompetition.cpp
benchmark/parseandstatcompetition.cpp
benchmark/statisticalmodel.cpp
doc/basics.md
doc/performance.md
include/simdjson/document.h
include/simdjson/document_stream.h
include/simdjson/inline/document.h
include/simdjson/inline/document_stream.h
singleheader/simdjson.h
tests/basictests.cpp
tests/errortests.cpp
tests/pointercheck.cpp
tests/readme_examples.cpp
tools/jsonstats.cpp

Returns document::element from parser.parse(), load(), load_many() and parse_many(). Also removes the doc_result type and navigation methods on document, as they are no longer used.
This greatly simplifies user experience and explanation. It means the result of these functions can be used immediately without the extra call to root(). Further, it means there are fewer concepts to grok before using simdjson. It's elements all the way down.
On the **con** side, this patch removes the ability to take or copy the document, so you can no longer keep the document longer than the parser. This wasn't an ability we had before, so I don't feel terrible about it. It also encourages people to convert things to a form that's better for them if they need to keep it around--keeping things around as a …

Return document::element from parser.parse()

---

include/simdjson/document.h
include/simdjson/implementation.h
include/simdjson/inline/document.h
include/simdjson/jsonioutil.h

This removes most const char * variants and replaces them with string_view, which yields support for const char *, string, string_view and padded_string arguments. Removes a few variants. Also used const string_view &, which doesn't seem to make a difference but I see it in the standard library a lot.

Use string_view instead of const char * where possible

---

include/simdjson/document.h
include/simdjson/document_stream.h
include/simdjson/error.h
include/simdjson/inline/document.h
include/simdjson/inline/document_stream.h
include/simdjson/inline/error.h

This removes element_result, array_result and object_result, and uses simdjson_result<T> for *all* failable methods. The main challenge was how to allow specializations with error chaining methods without having to redefine tie() and friends: if you specialize a class, you are redeclaring everything in it! I solved that by creating a `internal::simdjson_result_base<T>` and deriving simdjson_result<T>, simdjson_result<element>, etc. from that.
I made simdjson_result redefine all the methods and call the superclass so that documentation could be had (I didn't want simdjson_result_base<T> to show up in doxygen, it's not something users should be concerned with).

Use simdjson_result for all _result classes

---

benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp
benchmark/distinctuseridcompetition.cpp
benchmark/parseandstatcompetition.cpp
benchmark/parsingcompetition.cpp
benchmark/statisticalmodel.cpp
doc/basics.md
include/simdjson/document.h
include/simdjson/error.h
include/simdjson/inline/document.h
include/simdjson/inline/document_stream.h
include/simdjson/inline/error.h
tests/basictests.cpp
tests/errortests.cpp
tests/integer_tests.cpp
tests/pointercheck.cpp
tools/jsonstats.cpp

OK, now we can implement get<> per #607:
Now we do:
```c++
std::string_view x = parser.parse(json).get<std::string_view>();
```
Instead of:
```c++
std::string_view x = parser.parse(json).get_string();
```
And the same with all other methods. It makes it explicit that this is about casting to to a user type, and lets the user write the types they are planning to use. This kind of type templatization also makes other generic capabilities easier, such as at<T> and at_key<T>, as well as type-casting tie<>. This patch doesn't implement said generic capabilities, however.
This is how nlohmann_json does value extraction, which is why I chose the specific name get (I like as better myself, but get isn't so bad and it lets people reuse muscle memory).
Note for integers: I only implemented uint64_t …

Replace as_X and is_X with get<T> and is<T>

---

doc/performance.md

The "-H" flag is probably import for users dealing with large files. It is currently hidden away whereas it should be documented as something convenient.

Better documentation for the -H flag.

---

.gitignore
Makefile
README.md
doc/basics.md
doc/performance.md
examples/quickstart/Makefile
examples/quickstart/quickstart.cpp
include/simdjson/document.h
include/simdjson/inline/document.h
include/simdjson/inline/parsedjson_iterator.h
tests/readme_examples.cpp
tests/readme_examples_noexceptions.cpp

This:
- Runs the quickstart, all the way up to and including the command line to compile and copying files into the directory. Everything except wget (it copies instead).
- Compiles all examples 
- Fixes anything that doesn't compile :)
- Adds begin()/end() to dom::element, which assumes it's an array (which is by far the common case for iteration).
- Makes ParsedJson::Iterator compile with -fno-exceptions (regression which will now be caught in CI)

Compile all .md examples in CI

---

README.md
benchmark/benchmark.h
benchmark/benchmarker.h
benchmark/parse.cpp
benchmark/parsingcompetition.cpp

Some users are interested, as a metric, in the number of documents parsed per second.
Obviously, this means reusing the same parser again and again. Suppose that you have a target, you want parse documents like "twitter_timeline.json" that you will receive in quick succession... how many could you parse per second? 
```
$ ./parse jsonexamples/small/twitter_timeline.json 
....
42110.6 documents parsed per second
```
So 42,000.
And, of course, for small documents (say demo.json), I achieve speeds in the millions of documents per second...
```
$ ./parse jsonexamples/small/demo.json 
number of iterations 200 
....
2341481.7 documents parsed per second
```
For an even smaller document (`{"status":"success"}`), I reach nearly 4 million documents per second.
The implementation is damn ugly, but …

Displaying the numbers of documents parsed per second

---

include/simdjson/document.h
include/simdjson/inline/document.h
include/simdjson/inline/error.h

This is very trivial PR which merely removes four semicolons which `g++ -pendantic` complains about.  
I left the `singleheader/*` file alone as it is generated anyway.

remove four trailing semicolons in three files which -pedantic dislikes

---

tests/basictests.cpp

Fixes https://github.com/simdjson/simdjson/issues/672
This test that we support std::ignore, as we should.

This adds a test for std::ignore

---

doc/basics.md

Currently, I cannot find anything explicit in the MarkDown basic documentation regarding the lifetime relationship between parser and documents. It is in the documentation in the sense that it is in the code and in the doxygen...
Helps to fix https://github.com/simdjson/simdjson/issues/696

Let us document the relationship between a parser instance and the parsed document.

---

doc/basics.md
tests/CMakeLists.txt
tests/extracting_values_example.cpp

Documentation update.
I think that casts and get<type>() are effectively equivalent which brings up the question: why do we bother with  get<type>() at all when exceptions are enabled?
Proof...
```C++
inline simdjson_result<dom::element>::operator bool() const noexcept(false) {
return get<bool>();
}
inline simdjson_result<dom::element>::operator const char *() const noexcept(false) {
return get<const char *>();
}
inline simdjson_result<dom::element>::operator std::string_view() const noexcept(false) {
return get<std::string_view>();
}
inline simdjson_result<dom::element>::operator uint64_t() const noexcept(false) {
return get<uint64_t>();
}
inline simdjson_result<dom::element>::operator int64_t() const noexcept(false) {
return get<int64_t>();
}
inline …
```

Trying to correct the documentation so that it actually describes how the code behaves. (Attempt two)

---

benchmark/bench_dom_api.cpp
include/simdjson/document.h
include/simdjson/inline/document.h

This PR introduces a much faster get<double> function.
Do...
```
mkdir build
cd build
cmake -DSIMDJSON_GOOGLE_BENCHMARKS=ON ..
./benchmark/bench_dom_api 
```
Here are my numbers using master:
```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            28986 ns        28986 ns        24070
numbers_size_scan                       17668 ns        17669 ns        39631
numbers_exceptions_scan                 37095 ns        37095 ns        18891
numbers_exceptions_size_scan            22905 ns        22905 ns        30558
```
Here are my numbers with this PR:
``` …
```

Massive performance boost for get<double>.

---

benchmark/bench_dom_api.cpp
include/simdjson/document.h
include/simdjson/inline/document.h

Before:
```
numbers_type_scan                       83977 ns        83978 ns         8325
numbers_type_size_scan                  78568 ns        78570 ns         8910
```
After:
```
numbers_type_scan                       31775 ns        31776 ns        21990
numbers_type_size_scan                  33834 ns        33835 ns        20686
```
The main "trick" is to avoid relying on a switch-case when converting the type read
from the tape (an ascii character value) to a C++ enum class. Instead we do some
branchless arithmetic.
Again, I lack any kind of good metric, so I am going out of instinct and experience. We need instrumented benchmarks where I can see what is going on. Anyhow, for now there are still low-hanging fruits, apparently.

This massively improves the performance of tight loops relying on a type() call.

---

.circleci/config.yml
.gitignore
CMakeLists.txt
examples/quickstart/CMakeLists.txt
tests/CMakeLists.txt
tests/basictests.cpp
tests/compilation_failure_tests/CMakeLists.txt

This:
1. Turns off all other implementations besides the one we're testing in each variant
2. Adds fallback tests
3. Shortens the test steps:
- Runs -march=haswell tests once rather than doing it again each variant
- Runs NO_COMPUTED_GOTO tests once rather than doing it again each variant
4. Removes some redundant test variants (only test the non-default flag for each--threads=off is one test, dynamic=on is another)
5. Fixes non-sanitize warnings so -Werror works on gcc7
6. Fixes the noexcept test variants (they weren't actually disabling exceptions)

Run fewer redundant steps and configs in CircleCI

---

doc/basics.md

I think it is required. We need to tell people which compilers we support, and we need to tell them that we require 64-bit systems. Visual Studio defaults on 32-bit builds, but we do not support 32-bit builds. We need to be explicit about it.
Fixes https://github.com/simdjson/simdjson/issues/742

We used to have a requirements section which went away. 

---

src/arm64/bitmanipulation.h

in the ARM 64-bit kernel. This intrinsic does not appear in the documentation
https://docs.microsoft.com/en-us/cpp/intrinsics/arm64-intrinsics?view=vs-2019
and should probably not be used. Note that we expect the compiler to produce
efficient code out of our implementation.

This removes the problematic use of the intrinsic _addcarry_u64 for Visual Studio

---

src/generic/stage2_build_tape.h

Being explicit regarding the initialization of two member variables.

---

benchmark/CMakeLists.txt

Currently, checkperf will fail (I think) on anything but a Linux platform. We guard it to avoid Visual Studio... but I don't think it is a strong enough guard.

We should not enable checkperf on anything but Linux.

---

.appveyor.yml

Right now we run 3 build flavors on VS2017 and one on VS2019. 2017 takes a few minutes longer per build, so let's run most of our build flavors on 2019. Should reduce usual appveyor runtime by 4-6 minutes, since it runs serially.
See [this CI run](https://ci.appveyor.com/project/lemire/simdjson-jmmti/builds/32345113) for an example.

Run most build flavors on VS2019

---

singleheader/CMakeLists.txt

This is distinct from the single-header tests we already have. It runs everywhere, including under Windows.

Building from the single-header files alone everywhere, including under Visual Studio

---

singleheader/CMakeLists.txt

This causes us to reamalgamate, and rebuild amalgamated_demo.cpp, when the header/source files change.
It generates the headers in the intermediate output directory, so you don't get littered with amalgamated header source changes. (It's also necessary, or at least very convenient, to do this because of how cmake's dependency trees work.)
On Windows, it only copies the headers from the source repository.
`make amalgamate` can be run to *update* the headers in the source repository.

Remalgamate when source/header files change

---

doc/basics.md
tests/readme_examples.cpp
tests/readme_examples_noexceptions.cpp

@pps83  wrote in issue https://github.com/simdjson/simdjson/issues/745:
> Firs of all, I tried really really hard to get these basics working with simdjson. TO the point that I though it's broken and I wanted to abandon it. I just couldn't figure out how to iterate members.
> The reason was that I was assigning to element result of parsing, while I had to assing to object I think. This is what I do now:
```
simdjson::dom::parser parser;
auto jObj = parser.parse(json);
if (jObj.error() || !jObj.is<simdjson::dom::object>())
{
LOG("failed to parse json");
return;
}
for (const auto& x: jObj.get<simdjson::dom::object>())
{
// x.key is "12345", x.value is {"a":12.34, "b":56.78, "c": 9998877}
}
```
(End quote)
So I decided to take his example, and make it one of our examples.

This adds another example

---

include/simdjson/inline/padded_string.h
include/simdjson/inline/parsedjson_iterator.h
include/simdjson/padded_string.h

Yesterday we set a rule that all members need to be initialized (Weffc++ discovered bunch of uninitialized) and that modern style for initialization should be used.
Two more cases that we missed yesterday.

default initialisaiton

---

.circleci/config.yml

Let us disable libcpp_clang9.
We now have freeBSD tests where clang is the default.

Let us drop libc++

---

fuzz/CMakeLists.txt
fuzz/build_fuzzer_variants.sh
fuzz/measure_coverage.sh
fuzz/ossfuzz.sh

This makes fuzzers builds WAY faster by only building the fuzzers instead of rebuilding the tree 6 times. We should really build fewer variants too, but I'm hoping this change will get us past what's plaguing master at the moment by not building checkperf ...

Only build fuzzers when fuzzing.

---

include/simdjson/parsedjson_iterator.h

This would have prevented *some* of the confusion that caused #819.

Fix deprecation message to point at correct doc name

---

benchmark/benchmarker.h
benchmark/parse.cpp

Right now, the documents/s includes the overhead from the loop itself as well as from timing collection. More importantly, it calculates an *average* speed rather than best, which is a highly variable number. As this is internal benchmarking, we want numbers that are easy to compare, so we should use best (which we use everywhere else). This fixes that by using the best full parse number to calculate documents/s.

Don't include benchmark overhead in documents/s

---

benchmark/checkperf.cmake
benchmark/parse.cpp

Currently, the parse benchmark does the `new` calls outside the hot loop, but it uses newly allocated memory for the first time in the hot loop. This memory, though allocated at the C++ level, has not been allocated by the OS yet, necessarily.
Now, it would seem that Windows and the Windows Subsystem for Linux allocate memory differently. Maybe, Windows has slower OS-level memory allocation.  Possibly there are different tradeoffs. Whatever. This is all irrelevant to simdjson.
So let us omit entirely any kind of memory allocation during the hot loop.
My expectation is that this would resolve a good chunk of the mystery behind issue https://github.com/simdjson/simdjson/issues/812
Please keep in mind that we do urge our users to use "hot buffers" (to reuse the same parser instance several …

This will change the default of the parse benchmark so that it work over hot buffers

---

HACKING.md
benchmark/CMakeLists.txt
benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp

The idea of this PR is to have a totally distinct approach from `parse` to run benchmarks.
Might help with https://github.com/simdjson/simdjson/issues/812
Usage:
```
mkdir build
cd build
cmake .. -DSIMDJSON_GOOGLE_BENCHMARKS=ON
cmake --build . --target bench_parse_call --config=Release
./benchmark/bench_parse_call
```
Or, under Windows,
```
mkdir build
cd build
cmake .. -DSIMDJSON_GOOGLE_BENCHMARKS=ON
cmake --build . --target bench_parse_call --config=Release
./benchmark/Release/bench_parse_call.exe
```
These numbers should match closely our parse benchmark, plus/minus a small margin of error given the different methodology. Huge discrepancies should be investigated.

Adding independent benchmarks using Google Benchmark

---

.appveyor.yml

When I checked in checkperf for Windows, I had to make it compare against a branch to get Windows command line arguments. Now master is fine.
This PR is mostly advisory and so that I can make sure appveyor doesn't break before checking in.

Compare against master on Windows

---

benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp
simdjson-flags.cmake

It takes a few extra seconds the first time you run `cmake` to do Google Benchmarks's configure, and it compiles gbench as well as our benchmarks, taking a few seconds more; but it's a pretty small cost to pay to have the benchmarks available by default.

Default SIMDJSON_GOOGLE_BENCHMARKS to ON.

---

include/simdjson/document.h
include/simdjson/inline/document.h
include/simdjson/portability.h

Ok. So this thing comes and goes. I think I need to convince @jkeiser that "my way" is better.
I wrote a whole blog post...
[For case-insensitive string comparisons, avoid char-by-char functions](https://lemire.me/blog/2020/04/30/for-case-insensitive-string-comparisons-avoid-char-by-char-functions/)
There is a benchmark and everything.
The tolower approach is a dog: 4ns/byte (on two systems). That's > 10 cycles to compare two bytes.
It is also more lines of code.
It is bad, bad, bad.
Am I convincing enough?
:smile:

Faster case-insensitive comparisons.

---

.circleci/config.yml
.cirrus.yml
.drone.yml

This is intended to speed up CI with newer (faster) compilers:
* Uses gcc9 and clang9 where possible
* Still has a clang6 and gcc7 test to make sure we still run on those compilers
* Uses conanio images where it can to reduce installation of dev tools
* Uses -j4 instead of -j2 on Cirrus, just in case it helps ...
gcc9 on ubuntu doesn't run the allparserscompetition, so I settled for gcc8 there.

Use gcc9 and clang9 where possible

---

include/CMakeLists.txt
singleheader/CMakeLists.txt

PR in #841 got a bit messy since it touches many parts (flags, amalgamation, sanitizer). I decided to divide that into patches.
This one only installs singleheader/simdjson.h instead of the include/ directory.
@jkeiser noted in #841 that singleheader/simdjson.cpp is also part of the public API but I wasn't sure if I should install that under include/ that is why I left it out for now (but I can add if there is a consensus).

Only install singleheader/simdjson.h as part of the public API

---

singleheader/amalgamate.sh

I don't understand why we would need the non-portable realpath in this script.
Fixes https://github.com/simdjson/simdjson/issues/863

Fixes issue 863

---

dependencies/CMakeLists.txt

Fixes https://github.com/simdjson/simdjson/issues/871
In some circonstances (unknown to me), git will refuse to pull a submodule except if we do so from the root. This seems to happen from time to time on some machines. I do not understand.
However, it seems harmless to just do it from root and be done with the problem.

Fixes issue 871

---

.drone.yml

We run perf tests on both circleci and drone, and they seem to fail spuriously more often on Drone. This removes all non-arm checkperfs from drone. We rely on circleci for those now.
I'm hoping this will remove most of the spurious checkperf failures without losing the huge value of a CI performance check.

Don't repeat circleci checkperf tests on drone

---

jsonexamples/generated/CMakeLists.txt

When using Ninja as generator, it failed to build:
```bash
$ cmake .. -G Ninja
$ ninja
```
> ninja: error: '/jsonexamples/generated/miss-templates/*.txt', needed by 'jsonexamples/generated/utf-8.json', missing and no known rule to make it
The build logs can be downloaded from here:
https://github.com/microsoft/vcpkg/runs/694967404

Fix Ninja build

---

src/arm64/stage2.cpp
src/fallback/stage2.cpp
src/generic/stage2/logger.h
src/generic/stage2/streaming_structural_parser.h
src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h
src/haswell/stage2.cpp
src/westmere/stage2.cpp

This has been helping me a lot when debugging various experiments since stage 2 is normally kinda opaque as to where and what went wrong. By default, LOG_ENABLED is false and there is zero performance penalty. If you set it to true, you get output like this:
```
| Event                          | Buffer               | Curr | Next | Next# | Detail                                             |
|--------------------------------|----------------------|------|------|-------|----------------------------------------------------|
| +document                      | {         "Image": { |    { |    " |     1 |                                                    |
|   +object                      | {         "Image": { |    { |    " |     1 |                                                    |
| …
```

Add logging to stage 2

---

windows/toni_ronnko_dirent.h

1. Add utf-8 compiler option for MSVC
For non-UTF-8 locals, there will be warnings for those files that may contain non-ASCII characters.
Because /WX is specified when using MSVC, these warnings are in turn treated as errors.
> simdjson\src\generic/stage1/utf8_lookup2_algorithm.h(1,1): error C2220: the following warning is treated as an error
> simdjson\src\generic/stage1/utf8_lookup2_algorithm.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
2. Fix build errors on UWP
For x64-uwp, size_t is 64-bit, DWORD is 32-bit. When /WX compiler option is specified, error occurs.

Fix MSVC build errors

---

.gitmodules
dependencies/CMakeLists.txt
tools/CMakeLists.txt
tools/json2json.cpp
tools/jsonstats.cpp
tools/minify.cpp

As suggested in #814, porting tools from getopt to cxxopts (https://github.com/jarro2783/cxxopts).
The port currently only applies to the tools referenced in CMakeLists from the tools folder.

Port tools to cxxopts

---

src/arm64/dom_parser_implementation.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/dom_parser_implementation.h
src/generic/stage2/structural_parser.h
src/haswell/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp

This moves the unclosed array check into stage 2 where it's measured. Moving it verbatim does in fact come at a cost; either way, it seems more natural to check for this when we find the first array marker instead of doing it separately.

Move unclosed array check to stage 2

---

simdjson-flags.cmake

The usual style of linking (Threads::Threads) works, but CMAKE_THREAD_LIBS_INIT doesn't since it is only used for linking the temporaries to the final object file and not when compiling the object files. 
This PR introduces a workaround but I do not like manually setting these flags (and I am not sure if it works other than GCC/Clang). 
I will try to make the Threads::Threads method work with CMake 3.9

Temporary fix to #914

---

include/simdjson/dom/document_stream.h
include/simdjson/error.h
include/simdjson/inline/document_stream.h
include/simdjson/internal/dom_parser_implementation.h
src/arm64/dom_parser_implementation.cpp
src/error.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/dom_parser_implementation.h
src/generic/stage1/allocate.h
src/generic/stage1/buf_block_reader.h
src/generic/stage1/find_next_document_index.h
src/generic/stage1/json_minifier.h
src/generic/stage1/json_structural_indexer.h
src/generic/stage2/logger.h
src/generic/stage2/streaming_structural_parser.h
src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h
src/haswell/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp
tests/basictests.cpp
tests/errortests.cpp
tests/parse_many_test.cpp

This simplifies parse_many(), fixes a bunch of bugs, and moves a lot of the logic to the implementation so it can be optimized.
This is the first in a series of 4 PRs which simplifies a lot of stage 2 and results in a performance improvement at the end.
1. Allows you to parse_many() an empty ndjson file and get back 0 documents. Previously it returned EMPTY.
2. Fixes a bug where if you had empty batches (batch_size bytes of whitespace between documents), it would return an error.
3. Fixes a bug where if you had errors in the middle of a document (like "1 2 [} 3"), it would just yield the first 2 documents and never tell you about the error.
4. Fixes a probable bug (I could repro it, but I am le tired) where, since we actually shrink the batch_size each time we encounter a partial UTF-8 …

[1/4] Simplify parse_many() and fix bugs

---

src/generic/stage1/json_structural_indexer.h
src/generic/stage2/logger.h
src/generic/stage2/streaming_structural_parser.h
src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h

This is the third in a series of 4 PRs which simplifies a lot of stage 2 and results in a performance improvement at the end.
This simplifies structural iteration by:
* Not storing `len` directly. Only needed at the beginning and at the end, don't waste a register on this.
* Storing `uint32_t *current_structural` instead of `uint32_t *structural_indexes` and `uint32_t next_structural`. (current_structural was used more than next_structural, so I changed the logic to fit and sure enough, got a reduction in instruction count.
* Removing cached versions of the current structural index and current structural *character*.
* Restructured the loop to fit, so that parse_value() just uses advance_char() directly instead of relying on some other branch having called advance_char().
Part of my hope …

[3/4] Remove unneeded structural_iterator variables

---

include/simdjson/internal/dom_parser_implementation.h
src/generic/stage2/logger.h
src/generic/stage2/numberparsing.h
src/generic/stage2/structural_parser.h
src/generic/stage2/tape_writer.h

This change makes it more likely the compiler will enregister the next tape write location (a very hot variable) by making it temporary to stage 2 (i.e. in structural_parser) instead of persisting it in dom_parser_implementation.
This is the last of a series of 4 PRs which simplifies a lot of stage 2 and results in a performance improvement at the end.
It looks like an overall average throughput improvement close to 2%. The improvements in instruction count and throughput are both pretty much universal. canada.json loses 6% or so overall, but other number parsing things gain substantially. Looking at the numbers, everything has a slightly larger number of cache references, and canada.json is large enough that almost all of them are cache *misses*, accounting for the difference. The …

[4/4] Stop persisting current_loc (+2% parse throughput)

---

.circleci/config.yml
include/simdjson/internal/dom_parser_implementation.h
singleheader/CMakeLists.txt
singleheader/README.md
singleheader/amalgamate.sh
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h
src/generic/stage2/logger.h
src/generic/stage2/numberparsing.h
src/generic/stage2/streaming_structural_parser.h
src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h
src/generic/stage2/tape_writer.h

Fixes https://github.com/simdjson/simdjson/issues/928

Put back the amalgamation files and add tests

---

.circleci/config.yml
.drone.yml
tests/CMakeLists.txt

Generally speaking, we should not have tests that fail constantly on good code. It is a bad policy. It trains us to ignore the results. Once something serious happens, we will miss it.
Fixes https://github.com/simdjson/simdjson/issues/869

Testing with GCC 10 and clang 10

---

benchmark/parseandstatcompetition.cpp

This is somewhat ugly code but it shows that our API is relatively slow compared to RapidJSON.
```
$ ./benchmark/parseandstatcompetition ../jsonexamples/canada.json 
API traversal tests
simdjson                                        :   3.457 GB/s 1535.553 documents/s 
rapid                                           :   5.013 GB/s 2227.072 documents/s 
```

New API traversal tests.

---

benchmark/parse.cpp
src/arm64/dom_parser_implementation.cpp
src/generic/stage1/json_string_scanner.h
src/haswell/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp

This wraps `find_escaped` in `if (backslash || prev_escape)`, short-circuiting roughly 9 instructions per loop iteration. I did not add an `if` for quote processing, because it'll only skip the clmul and strings are ridiculously common (I feel like it'll be rare for 64-bytes to *ever* lack a string, except in cases of > 64 byte strings).
I know this is all about branch-free, but ... backslashes just aren't that common. And in files where they happen a reasonable amount, they are going to be on the edge of predictable: like, they'll happen basically everywhere (multiline strings that use \n's all over), in runs (small spurts of strings that have weird characters), or in repeated patterns (because they are all objects of the same type.
This should be a discussion; you know a *lot* more …

Wrap backslash processing in a branch

---

src/arm64/dom_parser_implementation.cpp
src/generic/stage1/utf8_lookup3_algorithm.h
src/haswell/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp

This slightly improves stage 1 (UTF-8 validation).
On x64 with GNU GCC 9 
|filename | ref. instructions/byte |candidate instructions/byte | difference |
|:--------| ----------:| --------------:| ----------:|
|apache_builds.json|2.310|2.302|-0.3%|
|canada.json|2.596|2.588|-0.3%|
|citm_catalog.json|2.176|2.168|-0.4%|
|github_events.json|2.149|2.138|-0.5%|
|google_maps_api_compact_response.json|3.113|3.110|-0.1%|
|google_maps_api_response.json|2.279|2.271|-0.3%|
|gsoc-2018.json|1.685|1.666|-1.1%|
|instruments.json|2.370|2.362|-0.3%|
|marine_ik.json|2.959|2.952|-0.2%|
|mesh.json|2.852|2.846|-0.2%|
|mesh.pretty.json|2.285|2.277|-0.3%|
|numbers.json|2.387|2.380|-0.3%|
|random.json|3.424|3.391|-1.0%|
|repeat.json|3.105|3.066|-1.2%|
|tree-pretty.json|2.331|2.323|-0.3%| …

Introducing lookup3 (UTF-8 validation).

---

.circleci/config.yml
.drone.yml

The effect should be to disable three performance tests. 
The net result is that under circle ci, we will have just one perf test (gcc10).
All performance tests will now be disabled under drone.
The idea is to narrow down the noise to the bare essentials.

Fewer performance tests.

---

include/simdjson/dom/array.h
include/simdjson/dom/element.h
include/simdjson/dom/object.h
include/simdjson/inline/array.h
include/simdjson/inline/document.h
include/simdjson/inline/element.h
include/simdjson/inline/object.h
tests/basictests.cpp
tests/cast_tester.h
tests/test_macros.h

This fixes #781, adding to both element and result<element>:
- get_array, get_object, get_string, get_c_str, get_int64_t, get_uint64_t, get_double, get_bool
- is_array, is_object, is_string, is_c_str, is_int64_t, is_uint64_t, is_double, is_bool
I'm unsure about the naming of get_double, get_int64_t and get_uint64_t. I could see get_float, get_integer and get_unsigned as well, but went with this because then I don't have to introduce concepts.
To accomplish this, I also had to move `internal::tape_ref` out of the way: it has some methods with the same name, and that was causing C++ confusion. Instead of being a base class of element, internal::tape_ref is now a member. I did the same for array and object and their iterators as well, for consistency. This is nice in part because now there …

Add non-template get_xxx/is_xxx methods to element

---

benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp
benchmark/benchmarker.h
benchmark/distinctuseridcompetition.cpp
benchmark/parseandstatcompetition.cpp
benchmark/statisticalmodel.cpp
doc/basics.md
examples/quickstart/quickstart_noexceptions.cpp
fuzz/fuzz_dump.cpp
fuzz/fuzz_dump_raw_tape.cpp
fuzz/fuzz_minify.cpp
fuzz/fuzz_parser.cpp
fuzz/fuzz_print_json.cpp
include/simdjson/dom/document_stream.h
include/simdjson/dom/element.h
include/simdjson/error.h
include/simdjson/inline/document_stream.h
include/simdjson/inline/element.h
include/simdjson/inline/error.h
include/simdjson/inline/parser.h
include/simdjson/portability.h
tests/basictests.cpp
tests/cast_tester.h
tests/extracting_values_example.cpp
tests/readme_examples.cpp
tests/readme_examples_noexceptions.cpp
tools/jsonstats.cpp

This adds a get(v) method that acts as ergonomic shorthand for get<type>().tie(v, error). It returns the error code so you can use it in contorl flow. I like it even better than `auto [v,error]` as well, in most cases. It simplifies things considerably.
* New version:
```c++
int64_t val;
if ((error = obj["val"].get(val))) { cerr << error << endl; return; }
cout << val << endl;
```
* Old version with auto (C++14): *this feels like it buries the lead (the fact that we're getting an int64_t out)*
```c++
auto [val, error] = obj["val"].get<int64_t>();
if (error) { cerr << error << endl; return; }
cout << val << endl;
```
* Old version with tie (C++11): *this is verbose and not control flow friendly*
```c++
int64_t val;
obj["val"].get<int64_t>().tie(val, error);
if (error) { cerr << error << …
```

replace get<T>.tie(v,e) with get(v)

---

benchmark/parse_stream.cpp
doc/basics.md
include/simdjson/dom/document_stream.h
include/simdjson/dom/element.h
include/simdjson/dom/parser.h
include/simdjson/inline/document_stream.h
include/simdjson/inline/error.h
include/simdjson/inline/parser.h
singleheader/amalgamate.sh
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h
tests/basictests.cpp
tests/cast_tester.h
tests/errortests.cpp
tests/parse_many_test.cpp
tests/test_macros.h

This makes it so parse_many and load_many behave like other APIs and return simdjson_result<document_stream>. Previously, if there was an error while loading, we would stash the error in the document_stream and return it when you first iterated.
The purpose here is to ensure we handle errors the same way everywhere (and to allow users to check for and recover from them as soon as they like).
This is a win for us internally, but it makes the use of parse_many() harder when you have exceptions off. I think the control flow makes more *sense* if you have exceptions off--you would expect the file itself to have at least one error--but it definitely makes the code you have to write harder:
Now:
```c++
document_stream stream;
if ((error = parser.parse_many(json).get(stream)) { exit(1); }
for …
```

Return error from parse_many

---

benchmark/bench_dom_api.cpp
benchmark/distinctuseridcompetition.cpp
benchmark/minifiercompetition.cpp
benchmark/parseandstatcompetition.cpp
benchmark/parsingcompetition.cpp
benchmark/statisticalmodel.cpp
doc/basics.md
doc/performance.md
include/simdjson/dom/array.h
include/simdjson/dom/element.h
include/simdjson/dom/object.h
include/simdjson/dom/parser.h
include/simdjson/error.h
tests/allparserscheckfile.cpp
tests/basictests.cpp
tests/errortests.cpp
tests/integer_tests.cpp
tests/jsoncheck.cpp
tests/numberparsingcheck.cpp
tests/pointercheck.cpp
tests/readme_examples.cpp
tests/readme_examples_noexceptions.cpp
tests/singleheadertest.cpp
tests/stringparsingcheck.cpp
tests/test_macros.h
tools/json2json.cpp
tools/jsonpointer.cpp
tools/jsonstats.cpp
tools/minify.cpp

This PR takes converts almost all the following to use `error = x.get(v):
* `.get<T>()`
* `auto [x,error] =`
* for (auto [x,error] : )
* `.tie(x,error)`
Aside from tests that explicitly test them. The only thing it actually leaves around is a few .get<T>()'s in tests, and the `for (auto [key,value] : object)` pattern. That has value, but we might want to stop using it idiomatically internally just so all our code is C++11 clean. It's better, but not so much better that it's worth the trouble.
The main goal here is to teach users *one* way to do error codes (`e = .get(v)`) and *one* way to do exceptions (`T()` / `T v = `). There may be more than one way to do it, but the more ways you present, the less "choice bandwidth" people have to spend on other stuff. And .get(v) is pretty damn …

Convert simdjson to use .get()

---

singleheader/CMakeLists.txt
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h
src/generic/stage1/buf_block_reader.h

This adds a test that fails in the first commit, and then adds the fix to remove the unused variable.

Fix #953: simdjson.cpp fails -Wall compiled on its own

---

cmake/simdjson-flags.cmake
include/simdjson/common_defs.h
tools/json2json.cpp
tools/jsonstats.cpp
tools/minify.cpp

Turns out we haven't been compiling with these warnings on in CI because we have SIMDJSON_GOOGLE_BENCHMARKS enabled. This helps explain why I sometimes get extra warnings and sometimes don't--when I am running with different options!

Compile with -Weffc++ in CI

---

doc/basics.md

Links to other files need to be either relative to themselves (doc/performance.md -> performance.md) or absolute (doc/performance.md -> /doc/performance.md). This change fixes the documentation when read on GitHub.

Fix documentation links in basics.md

---

doc/basics.md
include/simdjson/dom/element.h
include/simdjson/inline/element.h

This makes get_string_length visible and it documents our aliasing of std::string_view.
Fixes https://github.com/simdjson/simdjson/issues/984

Fixing issue 984

---

include/simdjson/implementation.h

Fixes https://github.com/simdjson/simdjson/issues/985

Removing optional since it is not C++11, and it is not used

---

cmake/simdjson-flags.cmake
doc/parse_many.md
include/simdjson/portability.h

Some people want to compile simdjson with thread support, and yet they do not want simdjson to use threads. There is no runtime way to do this right now. This PR introduces a compile-time "overwrite" option (SIMDJSON_DO_NOT_USE_THREADS_NO_MATTER_WHAT) that would overwrite thread support and prevent simdjson from using threads, even if it is compiled with thread support.
This a temporary compile-time option. I expect that we will offer runtime control in the future.
Fixes https://github.com/simdjson/simdjson/issues/988

This introduces a new option to forcefully disable threads for people who also want them enabled

---

.drone.yml
include/simdjson/inline/tape_ref.h
include/simdjson/portability.h
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h
src/generic/stage2/numberparsing.h
src/haswell/bitmanipulation.h
src/jsoncharutils.h
src/simdprune_tables.h
src/westmere/bitmanipulation.h
tests/numberparsingcheck.cpp

We are not going to support 32-bit platforms. But this PR adds 32-bit tests (GCC and clang).
Fixes https://github.com/simdjson/simdjson/issues/976

Fix for issue 976 (something like 32-bit support)

---

cmake/simdjson-flags.cmake

According to https://gitlab.kitware.com/cmake/cmake/-/issues/17976, `CMAKE_VS_PLATFORM_TOOLSET` is set only when using a Visual Studio generator.
When we use a Ninja generator(in `vcpkg`, Ninja is prefered if available), `CMAKE_VS_PLATFORM_TOOLSET` will be empty.
As a result:
> if(${CMAKE_VS_PLATFORM_TOOLSET} STREQUAL "v140")
will be treated as:
> if( STREQUAL "v140")
The build log can be downloaded from here: https://github.com/microsoft/vcpkg/pull/12140/checks?check_run_id=821747528
Suppose we have a `CMakeSettings.json` which contains:
```json
{
// See https://go.microsoft.com//fwlink//?linkid=834763 for more information about this file.
"configurations": [
{
"name": "x86-Debug",
"generator": "Ninja",
"configurationType": "Debug",
"inheritEnvironments": [ "msvc_x86" ],
"buildRoot": …
```

CMAKE_VS_PLATFORM_TOOLSET might be empty

---

cmake/simdjson-flags.cmake

This seems to indicate that Visual Studio always accept our __force_inline calls... 
https://github.com/simdjson/simdjson/issues/829

I think that this should fail when we "force inline" and visual studio bypasses us.

---

cmake/simdjson-flags.cmake

This makes it easier to profile inside Intel VTune when needed.
(Windows-specific.)
Help with issue https://github.com/simdjson/simdjson/issues/829

Adding a new flag to tell Visual Studio to include debugging information in the release builds.

---

.appveyor.yml

Will cover it under GitHub action.

clang is busted under appveyor

---

.github/workflows/vs16-clang-ci.yml
benchmark/benchmark.h
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h
src/arm64/dom_parser_implementation.cpp
src/arm64/simd.h
src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h
src/haswell/dom_parser_implementation.cpp
src/haswell/simd.h
src/westmere/dom_parser_implementation.cpp
src/westmere/simd.h

Mostly, this PR removes several (but not all) of the functional programming idioms from the kernels. With the latest visual studio/clang updates, they made the clang builds fail.
With this PR, not only does the project builds (again) under Clang/Visual Studio, but also the performance is fantastic (2.65 GB/s on Twitter):
```
$ cmake --build . --target parse --config Release
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
Checking Build System
Building Custom Rule C:/Users/User/github/simdjson/jsonexamples/generated/CMakeLists.txt
simdjson.vcxproj -> C:\Users\User\github\simdjson\build\src\Release\simdjson.lib
Building Custom Rule C:/Users/User/github/simdjson/benchmark/CMakeLists.txt
parse.vcxproj -> …
```

Fixing clang under visual studio

---

src/generic/stage2/atomparsing.h

UndefinedBehaviorSanitizer alerts about loading of misaligned address:
```
../contrib/simdjson/src/generic/stage2/atomparsing.h:4:67: runtime error: load of misaligned address 0x0000156b65c2 for type 'const uint32_t' (aka 'const unsigned int'), which requires 4 byte alignment
0x0000156b65c2: note: pointer points here
6e 65  64 00 6e 75 6c 6c 00 61  6c 69 67 6e 6d 65 6e 74  00 6f 62 6a 65 63 74 2d  73 69 7a 65 00 69
^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../contrib/simdjson/src/generic/stage2/atomparsing.h:4:67
```
This PR fixes that.

Fix undefined behavior: load of misaligned address

---

include/simdjson/common_defs.h
src/generic/stage1/find_next_document_index.h

When compiling with "-Weverything" Clang is showing a lot of warnings like this
```
warning: 'parse' was marked unused but was used
[-Wused-but-marked-unused]
```
For example, I get such warnings in this simple program:
```
#include <string>
#include <iostream>
#include <simdjson.h>
#pragma clang diagnostic warning "-Weverything"
#pragma clang diagnostic ignored "-Wc++98-compat"
int main()
{
std::string_view json = "23.5";
simdjson::dom::parser parser;
auto doc = parser.parse(json.data(), json.size());
std::cout << "json parsed" << (doc.error() ? " with error" : "") << std::endl;
return 0;
}
```
It's because of these definition:
```
#define really_inline inline __attribute__((always_inline, unused))
#define never_inline inline __attribute__((noinline, unused))
```
Clang treats the …

Fix clang warning -Wused-but-marked-unused.

---

src/arm64/numberparsing.h
src/fallback/numberparsing.h
src/generic/stage2/numberparsing.h
src/generic/stage2/structural_parser.h
src/haswell/numberparsing.h
src/westmere/numberparsing.h

This simplifies integer parsing (and float parsing, a little bit), in particular removing a bunch of visible branches. (I say visible because I believe the compiler was getting rid of said branches given that performance and branch misses don't really change.) It does not change performance at all on Skylake / GCC 9.
The main changes:
1. **parse_digit:** Moved digit parsing to a common parse_digit() function, eliminating is_integer and doing the comparison against the parsed int. The compiler was already doing this for us, but this both makes the callers easier to read, and makes the intended flow clearer instead of having redundant operations in the code to be optimized.
2. **Remove `case '-'`:** Removed the `found_minus` parameter and the special cases for '-' in the structural_parser. …

Remove some branches from number parsing

---

src/generic/stage2/atomparsing.h

Eventually, we may want to write something like simdjson::unsafe_load_uint32, simdjson::unsafe_load_uint64 and so forth... thus hiding the ugly memcpy. I count about 10 uses of memcpy throughout the code.

Trying to document more carefully the use of memcpy.

---

CMakeLists.txt
Doxyfile
include/simdjson/simdjson_version.h
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h
src/implementation.cpp

We had a serious performance problem for small files and I want to patch the 0.4.x series with PR https://github.com/simdjson/simdjson/pull/1044 from @vitlibar. It only affects very small files.
Let us take the file `{"level":"INFO","message":"This is a log message that is long enough to be representative of an actual message.","msgType":1,"source":"Test","thread":"main","timestamp":1400000000000000000,"version":1}` from https://github.com/simdjson/simdjson/issues/1023
```bash
$ git checkout v0.4.6
$ cmake --build . --target parse
$ ./benchmark/parse f.json
number of iterations 200
f.json
======
3 blocks -        202 bytes -    28 structurals ( 13.9 %)
special blocks with: utf8         0 (  0.0 %) - escape         0 (  0.0 %) - 0 structurals         0 (  0.0 %) - 1+ structurals         4 …
```

Preparing new patch release for 0.4.x

---

include/simdjson/dom/array.h
include/simdjson/dom/object.h
include/simdjson/inline/array.h
include/simdjson/inline/object.h
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h

C++ 20 adds a new feature called "ranges", which provides components for dealing
with sequences of values: https://en.cppreference.com/w/cpp/ranges.
A range is like a normal object containing `begin` and `end`, except there are
also composable operations like maps, filters, joins, etc.
The iterator objects returned by a range's `begin` and `end` require a more
strict set of operations than is needed for a range-for loop.
This PR adds the extra operations needed to support turning `dom::array` and
`dom::object` into a range.
This PR does not depend on any C++ 20 behavior, the added operators are all
valid C++ 11, and are already part of the LegacyIterator concepts.
This PR adds extra code behind: `#if defined(__cpp_lib_ranges)` guards, which is
the new C++ 20 specified feature test macro …

Add support for C++ 20 ranges.

---

include/simdjson/portability.h

Add missing strings.h include for non-windows builds (required by strcasecmp)

---

.github/workflows/msys2.yml

The jobs were executed in powershell using the globally installed cmake.
This makes things actually run in a MSYS2 shell.
This also removes the msys/cygwin job because it doesn't build
(it complains about undeclared posix_memalign)

Make MSYS2 CI jobs actually use MSYS2

---

include/simdjson/error.h
include/simdjson/inline/error.h

It is potentially unsafe (especially when using dynamic libraries).

Avoid allocations in global objects

---

benchmark/parseandstatcompetition.cpp
doc/performance.md

Removing one character in the code is enough to boost our API traversal performance.
```
$ ./benchmark/parseandstatcompetition ../jsonexamples/twitter.json
API traversal tests
Based on https://github.com/miloyip/nativejson-benchmark
simdjson (old)                        :   0.454 cycles/byte 	  1.398 instructions/byte 	  7.483 GB/s 11850.026 documents/s
simdjson                                	:   0.360 cycles/byte 	  1.242 instructions/byte 	  9.447 GB/s 14959.982 documents/s
rapid                                   	:   0.471 cycles/byte 	  0.926 instructions/byte 	  7.212 GB/s 11420.218 documents/s
$ ./benchmark/parseandstatcompetition ../jsonexamples/gsoc-2018.json
API traversal tests
Based on https://github.com/miloyip/nativejson-benchmark
simdjson (old)                     	:   0.111 …
```

Turns out that passing dom::element by reference can be a performance killer.

---

src/arm64/dom_parser_implementation.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/dom_parser_implementation.h
src/generic/stage2/structural_parser.h
src/haswell/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp

Third in a three-part PR series: #1065 (anonymous namespaces) -- #1078 (remove computed GOTOs) -- 1079 (return errors instead of goto)
This eliminates the indirect "goto error, then decide what error to use" in favor of returning the detected error then and there. While there is no doubt that such a routine may ultimately be useful, all current errors are in fact knowable immediately.
The purpose here is to move towards a SAX model, where the actual methods return whatever error codes they want, and we honor them. I expect the SAX model to be very important for DOM-constructing language bindings. I'd also like stage 2 to be a consumer of this model, personally--even if it means stage 2 is a tiny bit slower than usual, eating our own dogfood will keep us from regressing performance for …

[3/3] Return errors immediately instead of using goto

---

src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h

This:
* Special cases empty objects and arrays, writing them immediately without incrementing / decrementing depth or involving the container stack.
* Simplifies start() somewhat (while I was in there).
* Reduces the work we do on start_document/end_document. More reduction could be done, but any further reduction seems to reduce performance, so I left it off for the time being.
When we open an array or object, there is already a special if statement to check for an immediate close, so this shouldn't change branchiness in any way. It does, however, move the check into the caller (the place we detect the { or [) so that it can branch to the correct place after handling the value, avoiding the need for the container stack.
Instruction count and throughput are both improved, as should be …

Special case empty objects and arrays

---

src/arm64/dom_parser_implementation.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/stage2/logger.h
src/generic/stage2/structural_iterator.h
src/generic/stage2/structural_parser.h
src/generic/stage2/tape_builder.h
src/haswell/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp

This PR splits stage 2 in half to create a (non-public) SAX interface. The purpose of starting with stage 2 is to ensure we start in a good place performance-wise, rather than building something separate and struggling to match the performance we already have in stage 2. It has a fairly clean separation of concerns, with structural_parser in particular never touching the output document.
* structural_parser handles JSON iteration and array / object / colon / comma matching. It maintains depth, structural_index iteration and is_array[] state. It does not reference or touch the document, tape, string_buf, or count.
* tape_builder handles tape construction and primitive parsing. It maintains tape index, string_buf index, and count. It is passed uint8_t *'s into the buffer, and never …

Split stage 2 in SAX fashion

---

include/simdjson/dom/array.h
include/simdjson/dom/object.h
include/simdjson/inline/array.h
include/simdjson/inline/object.h
singleheader/amalgamate_demo.cpp
singleheader/simdjson.cpp
singleheader/simdjson.h

Fixes #1083.
C++20 fails to compile simdjson on master.
I fixed the underlying problem (there were static_asserts that depended on simdjson/element.h, which had not yet been loaded).
I did not add a quickstart20 test to surface this issue earlier, because we have lurking C++20 warnings in the codebase (there is an issue filed somewhere). If this PR succeeds, however, we know this specific problem is fixed: reamalgamating triggers the issue and I reamalgamated.

Fix C++ 20 compilation

---

include/simdjson/dom/document_stream.h
include/simdjson/inline/document_stream.h
tests/document_stream_tests.cpp

This gives access to the underlying document that has been parsed as a string_view. The API is not ideal, but it is working... and the implementation is easy and performant...
```C++
document_stream stream = parser.parse_many(jsonstring);
for(auto i = stream.begin(); i != stream.end(); ++i) {
auto doc = *i;
std::string_view v = i->source();
}
```
Fixes issue https://github.com/simdjson/simdjson/issues/1088
cc @casperisfine

Fixes issue 1088

---

doc/basics.md

We used to be explicit with respect to standard compliance, but this has been left out when we cleaned the documentation. I think that this is needed.

Let us be explicit about standard compliance

---

singleheader/amalgamate.sh

`cp -u` is a GNU-ism.
The simdjson is not meant to be Linux-only. We support FreeBSD and macOS.

Please don't use GNU-specific flags.

---

benchmark/CMakeLists.txt
benchmark/bench_dom_api.cpp
benchmark/bench_sax.cpp
benchmark/twitter/sax_tweet_reader.h
benchmark/twitter/sax_tweet_reader_visitor.h
benchmark/twitter/tweet.h
benchmark/twitter/twitter_user.h
src/generic/stage2/logger.h
src/generic/stage2/numberparsing.h
src/generic/stage2/stringparsing.h

I wrote a benchmark that selectively deserializes twitter.json, gets the tweet ID, text, timestamp, user ID, screen name, # favorites, # retweets, and ID of the tweet it's replying to (if any).
Relevant design points:
* Primitive values we don't care about are not parsed or validated. Structure (objects and arrays) is fully validated, however.
* It keeps track of the `container` you are in (root, top object, statuses, tweet, user). There are other sub-object or sub-sub-objects we don't care about (twitter.json has a depth of 9)--we let the depth float and decide whether we're directly *in* a tweet or user by checking if depth == 3 or 4.
* Fields we care about are described in a static hash from [key+depth] -> [type, binary offset into tweet]. Types are unsigned, nullable unsigned, and …

SAX benchmark

---

src/generic/stage2/numberparsing.h
src/generic/stage2/tape_builder.h

I spent some time factoring number parsing, to get rid of the need to pass the writer to a function ... I haven't succeeded in that yet, but the small changes here seem to change some stuff so I thought I'd send it up. IMO it makes the flow a little clearer, which is the main reason to do it.
* Return error codes from parse_double(): this was actually the biggest jump. Now that we're just passing error codes all the way down to the caller, we get some savings!
* Make compute_float_64 return bool (and write to `double &d`): this simplifies our control flow usage a bit. This also gets rid of a "not quite bug" where one of the paths in compute_float_64 forgot to assign success = true, so you are forced to pre-assign it to true before calling.
* Collapses the code to remove leading zeroes …

Number refactorings with positive effects

---

src/generic/stage2/structural_parser.h
tests/errortests.cpp

Because number parsing will keep going as long as it can find new numbers, there is a case where it could trail off past SIMDJSON_PADDING:
```c++
const char *json = "{\"key\":122222222222222222222222222222222222222222222}";
parser.parse(json, strlen("{\"key\":1"));
```
We fix this for numbers we find at the root by copying the buffer and adding spaces; we fix it for arrays by checking if the array is closed. But we don't check if hashes are closed, so we can get into this situation still.
To make this a corruption bug, you just have to cut the array off after SIMDJSON_PADDING digits.
This closes off all possible corruption bugs where non-root primitives assume there is a structural or whitespace after them, I believe.
Incredibly and inexplicably, this PR improves performance and reduces …

Fix potential buffer overrun with heavily customized input and padding

---

benchmark/CMakeLists.txt
benchmark/bench_dom_api.cpp
benchmark/bench_sax.cpp
benchmark/twitter/sax_tweet_reader.h
benchmark/twitter/sax_tweet_reader_visitor.h
benchmark/twitter/tweet.h
benchmark/twitter/twitter_user.h
src/arm64/dom_parser_implementation.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/dom_parser_implementation.h
src/generic/stage2/allocate.h
src/generic/stage2/json_iterator.h
src/generic/stage2/logger.h
src/generic/stage2/numberparsing.h
src/generic/stage2/stringparsing.h
src/generic/stage2/structural_parser.h
src/generic/stage2/tape_builder.h
src/haswell/dom_parser_implementation.cpp
src/implementation.cpp
src/westmere/dom_parser_implementation.cpp

This is as far as I could push the SAX interface without affecting performance. Pretty much moving *any* line seems to be enough to hurt at least some files by 1-5% overall. 
It makes no functional changes. What it does:
* Removes structural_parser and structural_iterator, replacing them with a single, fairly thin json_iterator class. walk_document() was pretty much the only method left in structural_parser.
* Give visitor (tape_builder) methods the opportunity to return error codes
* Move more functionality into the visitor
* Make walk_document a little easier to read (IMO, we'll see what you think :))
What I *really* like, as a non-speculative benefit for our current code in particular, is the clean separation of concerns. `json_iterator` owns everything necessary to iterate (structural …

Basic SAX interface with benchmarks

---

doc/basics.md
doc/basics_doxygen.md

There is nothing specific to Visual Studio per se, but it covers package managers, and it points at how one can build a simdjson-dependent project using CMake with Visual Studio. The CMake instructions for Windows/Visual Studio used to be more complicated but now that Visual Studio 2019 defaults on x64 (on 64-bit Windows), it is pretty much as easy as under any other platform.
For package managers, we point at the wiki since these are things that are likely to change quickly over time (more packages, instructions that evolve, and so forth).
I really like the new CMake instructions. It is very neat.
Fixes https://github.com/simdjson/simdjson/issues/750

This improves our documentation.

---

.circleci/config.yml
doc/basics.md
doc/basics_doxygen.md
include/simdjson/dom/parser.h
tests/document_stream_tests.cpp
tests/readme_examples.cpp

When using `parse_many`, we do not copy the string input, and yet we parse several documents, going back to the input. If the user mistakenly provides us with a temporary memory buffer, they can be doing something unsafe.
This PR is a documentation update (with some added tests). We want to very clearly explain how to use safely the library. It would be nicer if the parser always took ownership of the data, but as long as you allow people to pass a pointer (something we want to allow), it is just not feasible for us to do so.
I have also simplified the circle CI tests. They keep randomly failing lately and I have to restart them. It gets on my nerve. Looking at the logs, it seems to have to do with memory failures. Well. Obviously, a parallel build will use more memory, so I think we will …

Adding test for issue 1133 and improving documentation

---

benchmark/bench_sax.cpp
benchmark/twitter/sax_tweet_reader_visitor.h
doc/ondemand.md
include/simdjson/error-inl.h
include/simdjson/error.h
src/generic/ondemand/array-inl.h
src/generic/ondemand/array.h
src/generic/ondemand/document-inl.h
src/generic/ondemand/document.h
src/generic/ondemand/field-inl.h
src/generic/ondemand/field.h
src/generic/ondemand/json_iterator-inl.h
src/generic/ondemand/json_iterator.h
src/generic/ondemand/object-inl.h
src/generic/ondemand/object.h
src/generic/ondemand/parser-inl.h
src/generic/ondemand/parser.h
src/generic/ondemand/raw_json_string-inl.h
src/generic/ondemand/raw_json_string.h
src/generic/ondemand/value-inl.h
src/generic/ondemand/value.h

Posted to help awareness--I'll likely merge back to the branch soon. I'm happy with the performance.
In debug builds, this:
* Asserts if you try to destroy the top-level document / json_iterator while iteration is still in progress.
* Asserts if you use a parent object or array iterator while you are still iterating *child* values (i.e. you try to get a second field while you are still looking at the first one).
* Asserts if you try to reuse value or document objects (you already iterated that value, you can't do it again!).
Since values can be checked multiple times (i.e. you can check if it's a string, and if it's not, try to parse as a number instead), there was a performance issue at first because the compiler was confused by the error case: if an error occurs, the parent can still …

Add API lifetime safety to on-demand parsing

---

benchmark/bench_sax.cpp
src/generic/ondemand/array-inl.h
src/generic/ondemand/json_iterator-inl.h
src/generic/ondemand/json_iterator.h
src/generic/ondemand/object-inl.h
src/generic/ondemand/value-inl.h

Going to merge into #947 . The skip() and skip_container() methods currently run off the end into corruption if there are missing end braces. This fixes it, at the cost of around 7-8% throughput on the tweet benchmark (and bringing it back below SAX). Presumably it will be less on things that skip fewer entries.
Aside from stage 2 shenanigans, maybe unrolling the loop or experimenting with decreasing indexes instead of pointers might help?
```
ondemand_tweets          178073 ns       178072 ns         3922 bytes=3.54639G/s docs=5.61569k/s tweets=561.569k/s
iter_tweets              170704 ns       170706 ns         4099 bytes=3.69944G/s docs=5.85804k/s tweets=585.804k/s
sax_tweets               162439 ns       162440 ns         4308 bytes=3.88767G/s docs=6.1561k/s tweets=615.61k/s …
```

Don't run off the end in on demand parsing

---

src/arm64/simd.h
src/haswell/dom_parser_implementation.cpp
src/haswell/simd.h
src/westmere/dom_parser_implementation.cpp
src/westmere/simd.h

This removes one subtraction per SIMD block when identifying operators (`,:[]{}`), and demystifies the algorithm and lookup table a bit (as well as adding comments).
EDIT: I added a second change, which uses simd8x64 abstractions and consequently reorders things a bit, and that brought even more substantial speedups. I do not understand why this code is so deeply in the hot path ... I expected the string detection path to be the long pole. But it doesn't matter *why* they help or even that they do, as the abstractions make the code lighter and easier to read.
Performance is better on gcc, probably down to the instruction count. clang fares worse, even though instruction count is down there too. I'm only showing stage 1 here, because that's all that's affected, and I saw some stage 2 …

Simplify operator classification lookup on Intel

---

benchmark/parse_records_benchmark.h

This is useful, even compulsory I'd say, because if the frequency tanks, then other numbers are suspect. In my tests, this is not a problem, but you want to keep an eye on the frequency of the processor. If it is not flat, then you don't want to trust the numbers. Also, to interpret the speeds, it is really helpful to know about the frequency of the processor.
This is a PR for jkeiser/stream-parse (not for master).
```
Running ./benchmark/bench_sax
Run on (16 X 3193.88 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 512 KiB (x8)
L3 Unified 16384 KiB (x8)
Load Average: 0.11, 0.09, 0.07
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

This adds a frequency column 

---

benchmark/largerandom/ondemand.h
benchmark/largerandom/sax.h

Another PR for jkeiser/stream-parse
The SAX change is a minor modification so that we do more validation. (It should be noted that the SAX code could eat garbage and be content.)
The on-demand change is, in my opinion, more legible code, and it also does more validation.

I think that this is better (fairer) code for the large random benchmark

---

benchmark/bench_ondemand.cpp
benchmark/bench_sax.cpp
benchmark/kostya/iter.h
benchmark/kostya/ondemand.h
benchmark/largerandom/iter.h
benchmark/largerandom/ondemand.h
benchmark/largerandom/sax.h
benchmark/partial_tweets/iter.h
benchmark/partial_tweets/ondemand.h
benchmark/partial_tweets/sax.h
benchmark/partial_tweets/sax_tweet_reader_visitor.h
cmake/simdjson-flags.cmake
include/simdjson.h
include/simdjson/arm64.h
include/simdjson/fallback.h
include/simdjson/portability.h
include/simdjson/simdjson.h
include/simdjson/westmere.h

This makes it possible to use ondemand on any system, and selects the fastest ondemand implementation for the compile flags you passed. Pass `-march=native` and no matter where you are, it'll use the best available (westmere, haswell, or arm64--or if none of them is available, fallback).
* Selects the minimum implementation based on variables like __ARM_NEON, __SSE4_2__, __AVX2__, __PCLMUL__, etc.
* Sets `SIMDJSON_BUILTIN_IMPLEMENTATION` to the minimum.
* Aliases `simdjson::builtin` to `simdjson::SIMDJSON_BUILTIN_IMPLEMENTATION`
* Turns lesser implementations off by default, because the program will never work on anything with a lesser instruction set anyway. This has the effect that, if you are on a haswell or neon machine, only one implementation will be turned on.
SAX is almost as slow …

Make ondemand easy to use when compiled for a specific system

---

.github/workflows/fuzzers.yml
fuzz/CMakeLists.txt
fuzz/FuzzUtils.h
fuzz/fuzz_atpointer.cpp
fuzz/fuzz_minify.cpp
fuzz/main.cpp

This adds a fuzzer for at_pointer() which recently had a bug.
The https://github.com/simdjson/simdjson/issues/1142 bug had been found with this fuzzer
Also, it polishes the github action job:
- cross pollinate the fuzzer corpora (lets fuzzers reuse results from other fuzzers)
- use github action syntax instead of bash checks
- only run on push if on master

fuzz atpointer

---

doc/basics.md
doc/basics_doxygen.md
tests/readme_examples.cpp

The non-parsing minify no longer requires padding but some of our documentation gives the wrong impression.

Some minor documentation fixes.

---

include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/array_iterator-inl.h
include/simdjson/generic/ondemand/array_iterator.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h

This allows you to do `for (auto val : doc)` instead of `for (auto elem : doc.get_array())`. It's a small thing, but iterating over top-level arrays is common enough that I didn't want people to mis-learn how to use the API (you can say `for (auto elem : val)` anywhere else _except_ document).
The reason it was hard is that document *owns* the iterator, while value and array *reference* the iterator. The array_iterator marks the iteration as finished by releasing the iterator, but you can't do that with an owned iterator. This fixes the problem by having array_iterator<value>, array_iterator<array>, and array_iterator<document>, which call `finished_iterating()` on the value/array/document when it's finished. document just stores that state differently.
This is the only API design wart I …

Allow direct document iteration in ondemand

---

benchmark/json_benchmark.h
benchmark/kostya/iter.h
benchmark/largerandom/iter.h
benchmark/partial_tweets/iter.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/raw_json_string-inl.h
include/simdjson/generic/ondemand/raw_json_string.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h

This allows you to try to parse a value multiple ways (for example, if `value.get_string()` fails, you can still try `value.get_double()`).
It also uses standard iterator code for parsing instead of special code in value, and fixes issues where we were advancing structural indexes multiple times when you parsed values at the root. (Or attempts to ... tests are still pending.)
By my measure, this improves things on gcc by a small amount (2% or so for PartialTweets and Kostya, both of which have skipping), and reduces instruction count slightly as well. On clang, however, it makes things a bit *worse* by about 5%, significantly increasing branch misses. I'm not sure why yet. I'll think on this one.
With this patch:
```
------------------------------------------------------------------------- …
```

Allow value parse to be retried

---

.drone.yml
fuzz/fuzz_implementations.cpp

This adds fuzzing on drone.io arm64
For some reason, leak detection had to be disabled. If it is enabled, the fuzzer falsely reports a crash at the end of fuzzing.
Closes: #1188

add CI fuzzing on arm 64 bit

---

.drone.yml
benchmark/benchfeatures.cpp
benchmark/minifiercompetition.cpp
benchmark/parse.cpp
doc/implementation-selection.md
fuzz/fuzz_implementations.cpp
fuzz/fuzz_minifyimpl.cpp
fuzz/fuzz_utf8.cpp
include/simdjson/implementation.h
src/implementation.cpp
tests/basictests.cpp
tests/document_stream_tests.cpp
tests/document_tests.cpp
tests/jsoncheck.cpp
tests/minefieldcheck.cpp
tests/readme_examples.cpp
tools/json2json.cpp
tools/jsonstats.cpp
tools/minify.cpp

The idea for this new method came via a discussion with @pauldreik
At compile-time, we generate several kernels. At runtime, they are all available. If you select the wrong one, you could crash your system. This function would tell you whether it is safe to call the kernel. This determination must be done at runtime.
This is highly specialized and not likely to be generally useful.
We should only merge this if it is actually useful to someone.
(This is the second and proper PR.)

Make it possible to check that an implementation is supported at runtime

---

.github/workflows/alpine.yml
benchmark/linux/linux-perf-events.h

The idea here is that if we can build and run tests on alpine, we should be pretty much set on all Linux systems given how minimalist alpine is. These tests revealed a hidden dependency on the linux headers which I had assumed were present on all systems.

Testing on minimalist alpine (linux) images

---

doc/basics.md
doc/parse_many.md

It seems that `parse_many` is confusing to some people who think that they should use it to parse their large documents.

Making it clearer that parse_many is meant for *small* documents.

---

.github/workflows/fuzzers.yml

forgot a place during refactoring, did not show up until run on the master branch

fix broken fuzzer action job

---

benchmark/kostya/ondemand.h
benchmark/largerandom/ondemand.h
benchmark/partial_tweets/ondemand.h
doc/ondemand.md
include/simdjson/builtin.h
src/implementation.cpp
tests/ondemand/ondemand_basictests.cpp

Currently, if you write an On Demand piece of code, you have no convenient way to tell which implementation is actually being used. So you could have someone, on a powerful Intel processor, compiling On Demand in fallback mode and getting terrible performance, and we would have no quick way to identify the problem.
It would be nice if we could ask the user for which implementation they are using, and to be able to point them to documentation as to how they can print it out, if only for debugging purposes.
For discussion.

This would allow users to find out what builtin is.

---

benchmark/largerandom/sax.h
include/simdjson/padded_string.h

For some reason, warnings started popping up in CI seemingly unrelated to what I was working on.
This fixes a "potentially use of uninitialized value" warning, as well as a cstyle cast to non-const.

fix some warnings in the sax benchmark

---

include/simdjson/generic/numberparsing.h

It seems like parse_unsigned is not used by anything running in CI.
This PR is here to prove that that either that function is not used and should be removed, or something needs to be added to CI.

demonstrate parse_unsigned is unused

---

.github/workflows/fuzzers.yml
doc/basics.md
doc/basics_doxygen.md
fuzz/CMakeLists.txt
fuzz/FuzzUtils.h
fuzz/Fuzzing.md
fuzz/fuzz_atpointer.cpp
fuzz/fuzz_element.cpp
include/simdjson/dom/element.h
include/simdjson/padded_string-inl.h
tests/CMakeLists.txt
tests/padded_string_tests.cpp

This is a new fuzzer to exercise more of the element api. The element-inl.h [is one of the most unfuzzed file in the project](https://github.com/simdjson/simdjson/issues/368#issue-522192008).
This fuzzer replaces both the at_pointer and one of the dump fuzzers but these are not removed at this time.
It also refactors how fuzz data is split into input, in a way that is more efficient for the fuzzer engine to mutate.
Also, creating a padded string from an empty string_view invoked undefined behaviour so I fixed that and added a unit test.

add fuzz element

---

.circleci/config.yml
doc/ondemand.md
include/simdjson/generic/ondemand/field-inl.h
include/simdjson/generic/ondemand/field.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/raw_json_string-inl.h
include/simdjson/generic/ondemand/raw_json_string.h
include/simdjson/generic/stringparsing.h
tests/ondemand/ondemand_basictests.cpp

It seems that @jkeiser had mysteriously disabled most of the ondemand tests? I think we want all of the tests enabled.
As part of my fiddling, I found that printing raw strings was really handy so I added an implementation of that.
Fixes https://github.com/simdjson/simdjson/issues/1231

Reenable the on-demand tests and allows us to convert a raw string into a C++ string.

---

doc/basics.md
doc/basics_doxygen.md

The motivation is to make it hard for users to be confused about how they can check the type of an element.

This fixes a typo and makes the types more explicit

---

.gitmodules
benchmark/parsingcompetition.cpp
dependencies/CMakeLists.txt

I think yyjson is the fastest C library I have ever seen.
```
$ cmake -B buildnewbench
$ cmake --build buildnewbench --target parsingcompetition
```
AMD Rome, GCC 9...
gsoc-2018.json:
```
getline                                 	:   0.706 cycles/byte 	  1.754 instructions/byte 	  4.809 GB/s 	1445.154 documents/s
simdjson (dynamic mem)                  	:   1.003 cycles/byte 	  2.548 instructions/byte 	  3.377 GB/s 	1014.902 documents/s
simdjson                                	:   1.001 cycles/byte 	  2.547 instructions/byte 	  3.385 GB/s 	1017.167 documents/s
RapidJSON                               	:  11.740 cycles/byte 	 45.576 instructions/byte 	  0.273 GB/s 	 82.185 documents/s
RapidJSON (accurate number parsing)     	:   8.622 cycles/byte 	 23.561 instructions/byte 	  0.365 GB/s …
```

Adds yyjson to our internal benchmarks.

---

benchmark/bench_ondemand.cpp
benchmark/distinctuserid/distinctuserid.h
benchmark/distinctuserid/dom.h
benchmark/distinctuserid/ondemand.h
doc/ondemand.md
tests/ondemand/ondemand_basictests.cpp

This benchmark extracts all user ids for a file. The On Demand approach is roughly twice as fast. So we get 4.6GB/s  (On Demand) vs 2.3GB/s for the DOM approach. So definitively worth it if you can have it.
@pauldreik : this is partially to answer your proposal that the release notes include some numbers.
Some extra documentation is needed. To be discussed.
```
cmake -DCMAKE_CXX_FLAGS="-march=haswell" -B newbuild
cmake --build  newbuild --target bench_ondemand
./newbuild/benchmark/bench_ondemand     
-----------------------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations UserCounters...
-----------------------------------------------------------------------------------
DistinctUserID<Dom>          292407 ns …
```

Adding a new benchmark for ondemand: distinct user id

---

doc/basics.md
doc/basics_doxygen.md
include/simdjson/dom/parser.h
tests/basictests.cpp

You can move a parser instance, but if you do so, it invalidates pointers to it (in our case elements). A sensible fix is to use `std::unique_ptr<dom::parser>`. This PR documents this recommended approach.
Fixes https://github.com/simdjson/simdjson/issues/1246
A real fix would be to look at https://github.com/simdjson/simdjson/issues/679

Fix for issue 1246. We document the relationship between parser instances and elements

---

.appveyor.yml
cmake/simdjson-flags.cmake
fuzz/fuzz_element.cpp

Projects that link simdjson from MSVC with exceptions off will
include simdjson headers which transitively include STL headers.
The MSVC STL stipulates that _HAS_EXCEPTIONS=0 be defined or code
requiring exceptions will be enabled. This change adds a new job
to the appveyor build matrix to verify the build and tests with
exceptions disabled, and disables exceptions at the compiler level
when SIMDJSON_EXCEPTIONS is specified to OFF.

Disable exceptions when compiling with MSVC

---

.github/workflows/ubuntu18-checkperf.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20-checkperf.yml
.github/workflows/ubuntu20.yml

Github already provides CMake 3.17 in the Ubuntu images for workflows.
Please refer to the following specifications:
* https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#tools
* https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#tools
This will enable #1258 to run more workflows, as it requires at least CMake 3.14 because of `FetchContent`.

Remove old CMake version from CI (Rely on CMake 3.17)

---

.github/workflows/fuzzers.yml
fuzz/build_fuzzer_variants.sh
fuzz/quick_check.sh

This builds the CI fuzzers with the intended clang version. It also allows users to set the clang version locally,
in case they need to.
It also switches the CI fuzzers to use an optimized sanitizer build, to do something oss-fuzz doesn't and get more done in the short time the CI fuzzer runs.

fuzz with the intended clang version

---

fuzz/fuzz_ondemand.cpp

include/simdjson/generic/numberparsing.h have several functions which are not reached. The ondemand fuzzer was extended to call those apis as well.

fuzz more of generic/numberparsing.h

---

include/simdjson/internal/numberparsing_tables.h
scripts/detect_nonascii_sourcefiles.py
singleheader/simdjson.cpp
singleheader/simdjson.h

There are two problems
* amalgamate being locale sensitive (will be fixed in #1269)
* source files with non-utf8 (numberparsing_tables.h), would have been detected earlier if #1269 had been in place
this fixes master to build again.

fix non ascii sources

---

include/simdjson/portability.h

Under compilers like MSVC the `#pragma message` about portability will be issued for each translation unit; regardless of whether or not `SIMDJSON_PORTABILITY_H` has already been defined. As such a new define `SIMDJSON_NO_PORTABILITY_WARNING`, can be defined prior to the inclusion of `<simdjson.h>` to silence it.

Additional define to silence the 32-bit portability warning.

---

.github/workflows/fix-trailing-whitespace.yml
scripts/remove_trailing_whitespace.sh

This adds a script for removing trailing whitespace from files.
It also adds a CI job which detects if the script needs to run, and provides instructions how to do so.
Note that the job currently fails - because a lot of files do have trailing whitespace. I did not want to touch a lot of files in this PR, so I won't fix it. That could be for another PR which only does that (runs the removal script and commits the results).

detect trailing whitespace in CI

---

singleheader/amalgamate.py

This is just to protect the users.

We do not want the amalgamate.py script to run *ever* if you do not have at least Python 3.

---

.circleci/config.yml
.cirrus.yml
.github/workflows/mingw-ci.yml
.github/workflows/mingw64-ci.yml

Follow up for #1282
This fixes an erroneous assumption about the presence of `cmake` at the fingerprint step in Cirrus CI and adds caching to Circle CI and the MinGW workflows in Github.
Regarding Drone CI, I think [this blogpost](https://laszlo.cloud/the-ultimate-droneci-caching-guide) is worth reading.  
It seems volume (filesystem) caching does not work properly on `cloud.drone.io`, which leaves only S3 buckets as a caching mechanism.

Improve CI workflows

---

.github/pull_request_template.md
CONTRIBUTING.md

It may not be obvious to some why some white-space tests are failing. I believe we need to document it.

Helping contributors (new rules regarding white space)

---

.github/workflows/alpine.yml
.github/workflows/fix-trailing-whitespace.yml
.github/workflows/fuzzers.yml
.github/workflows/mingw-ci.yml
.github/workflows/mingw64-ci.yml
.github/workflows/msys2.yml
.github/workflows/ubuntu18-checkperf.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20-checkperf.yml
.github/workflows/ubuntu20.yml
.github/workflows/vs16-ci.yml
.github/workflows/vs16-clang-ci.yml
.github/workflows/vs16-ninja-ci.yml

Forks that would like to contribute via PRs from feature branches needlessly run CI on those branches on top of the ones run for PRs.  
This is a waste of resources.

Disable Github CI in feature branches

---

.drone.yml
benchmark/parsingcompetition.cpp
dependencies/CMakeLists.txt

This will get boost json building again. The reason it did not work before was because it requires a working string_view in standalone mode (without the rest of boost).
Therefore, I added a check to see if string_view was available. I also added a c++20 CI job. 
I had to switch docker container to get the proper libc++. I made a docker image, which I am happy to contribute (with whatever license is appropriate, since I wrote it myself) to the project (perhaps put in the new simdjson/docker-images repo?): https://github.com/pauldreik/docker-images 
Seems like simdjson does not explicitly test different C++ versions in CI?

enable boost json

---

.travis.yml

Fixes #1294  
Related #1254
Somehow not all jobs in the matrix received a recent enough CMake version.  
This fixes that by using a [PPA from the simdjson organization](https://github.com/simdjson/debian-ppa) providing CMake 3.18.4 for Linux-ppc64el.

Use PPA in Travis

---

include/simdjson/padded_string-inl.h

If the allocator fails and returns nullptr, the memcpy should not happen.
See ossfuzz https://oss-fuzz.com/testcase-detail/6612227272212480
I don't know what the error strategy for padded_string is, I guess it should be kept noexcept so we can't throw here. Setting the size to zero and data to nullptr seems reasonable, but that looks exactly like a default constructed empty padded_string. Should those be kept separate? As of now, if the allocation fails, the padded string will be empty, and the program will proceed as if the input was empty which may be surprising.
One way to keep the failed alloc case apart from the zero size case would be to let the zero size point to a static buffer. That would make it always be padded, even in case of zero size. A member function could be added to …

don't memcpy after failed alloc

---

include/simdjson/dom/document_stream-inl.h
include/simdjson/dom/parser-inl.h
include/simdjson/dom/parser.h
tests/document_stream_tests.cpp

If someone were to set the batch size to, say, zero, things would not end well. This PR guards against that.

This will guard the batch_size so it cannot be so low as to accidentally burn through your CPU.

---

include/simdjson/generic/ondemand/array_iterator-inl.h
include/simdjson/generic/ondemand/array_iterator.h
include/simdjson/generic/ondemand/object_iterator-inl.h
include/simdjson/generic/ondemand/object_iterator.h

This fix is required for successful compilation with C++20. Without this fix clang is complaining about range-based for loops:
```
/home/mmatrosov/dev/simdjson/tests/ondemand/ondemand_basictests.cpp:35:37: error: use of overloaded operator '!=' is ambiguous (with operand types 'simdjson::simdjson_result<simdjson::fallback::ondemand::array_iterator<simdjson::fallback::ondemand::value> >' and 'simdjson::simdjson_result<simdjson::fallback::ondemand::array_iterator<simdjson::fallback::ondemand::value> >')
for (ondemand::object my_object : doc["mykey"]) {
^
/home/mmatrosov/dev/simdjson/include/simdjson/generic/ondemand/array_iterator.h:95:31: note: candidate function
simdjson_really_inline bool operator!=(const simdjson_result<SIMDJSON_IMPLEMENTATION::ondemand::array_iterator<T>> &) noexcept; …
```

Mark comparison operators as const

---

.github/workflows/ubuntu18-threadsani.yml
.github/workflows/ubuntu20-threadsani.yml
cmake/simdjson-flags.cmake
include/simdjson/dom/document_stream-inl.h

I believe I found a potential data race in our document_stream. I believe that it is never of any consequence because, in the worst case, we will do a bit more work than we should. However, the thread sanitizer cannot know this.
I have added tests where we run document_stream_test and parse_many_test with thread sanitizers. With this change, they run clean.
Credit to @pauldreik  for reporting potential data race.

Hunting for data races in document_stream

---

.travis.yml
doc/parse_many.md
tests/document_stream_tests.cpp

Suppose you have a stream of JSON documents, but the last JSON document has been truncated. You'd want to parse all JSON documents up to that point and then know where you are (in bytes) within the stream.
It turns out that our API already allows you to do it...
```C++
simdjson::dom::parser parser;
simdjson::dom::document_stream stream;
auto error = parser.parse_many(json, json.size()).get(stream);
if(error) { return; }
auto i = stream.begin();
for(; i != stream.end(); ++i) {
auto doc = *i;
if(!doc.error()) {
std::cout << "got full document at " << i.current_index() << std::endl;
}
}
size_t index = i.current_index();// start of the truncated document
```
And this will always work *except* if your JSON stream ends with a truncated string. Then it does not work anymore because stage 1 will …

Prototype test for issue 1299: using parse_many, find the location of the end of the last document

---

dependencies/CMakeLists.txt

This introduces a new option `SIMDJSON_ALLOW_DOWNLOADS` with default `ON`, which will enable or disable downloads of dependencies.
Relevant https://github.com/simdjson/simdjson/issues/1331

Allow build without download

---

include/simdjson/portability.h
tests/document_stream_tests.cpp

We will no longer enable threaded execution when BOOST_HAS_THREADS is defined since some users compile some of their code with BOOST_HAS_THREADS set and some with BOOST_HAS_THREADS unset.
Fixes https://github.com/simdjson/simdjson/issues/1337

Fixing issue 1337

---

fuzz/fuzz_utf8.cpp

Currently, the fuzzers are difficult to run locally and when they fail, they appear not to output a reproducible case. At least for UTF-8, we would like to see what the offending input is. This is my attempt at doing so.

This might make the fuzzer errors more debuggable.

---

benchmark/minifiercompetition.cpp

as described in the description for the allocate_padded_buffer function: // The caller is responsible to free the memory (e.g., delete [] (...)).
but your code used the function free.
I propose to fix this error.
Our tests check whether you have introduced trailing white space. If such a test fails, please check the "artifacts button" above, which if you click it gives a link to a downloadable file to help you identify the issue. You can also run scripts/remove_trailing_whitespace.sh locally if you have a bash shell and the sed command available on your system.
If you plan to contribute to simdjson, please read our
CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

fix memory malloc/free mismatch in minifiercompetition.cpp

---

.github/workflows/vs16-noexcept-ci.yml
benchmark/json_benchmark/diff_results.h

If x and y differ as numbers, it is not true that their naive string representation will differ. We need to be careful.

This makes the float errors explicit.

---

doc/basics.md
doc/ondemand.md
doc/ondemand_design.md
examples/quickstart/quickstart_ondemand_noexceptions.cpp
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
tests/ondemand/CMakeLists.txt
tests/ondemand/compilation_failure_tests/CMakeLists.txt
tests/ondemand/compilation_failure_tests/iterate_temporary_buffer.cpp
tests/ondemand/ondemand_active_tests.cpp
tests/ondemand/ondemand_compilation_tests.cpp
tests/ondemand/ondemand_dom_api_tests.cpp
tests/ondemand/ondemand_error_tests.cpp
tests/ondemand/ondemand_key_string_tests.cpp
tests/ondemand/ondemand_number_tests.cpp
tests/ondemand/ondemand_ordering_tests.cpp
tests/ondemand/ondemand_parse_api_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp
tests/ondemand/ondemand_twitter_tests.cpp

This is the equivalent of basics.md, but for On Demand. Should be a decent start for users who want to use it.
It also adds associated tests for the examples in the doc, to ensure they compile and work.
While adding tests for it, I realized I was writing `auto doc = parser.iterate("[]"_padded);` a lot, but this will never, ever actually work. Iteration requires the JSON text to stay in scope, so the padded_string *must* live longer than the iterate call. This means the Quick Start from the other PR would compile, but wouldn't work.
So I disallowed `iterate(padded_string &&)`, which disallows temporaries. That required that I allow simdjson_result<X> to cast to X&, allowing you to call methods taking `const X&` with a simdjson_result<X>.
Fixes …

Add On Demand documentation

---

src/from_chars.cpp
tests/basictests.cpp
tests/random_string_number_tests.cpp

This would only happen if you are really eager on the number of trailing zeros so it is unlikely that anyone would ever experience this bug in the real world... but it is a trivial logical error.
The idea is that when we have long mantissa, we mark the value as "truncated" if we can't parse all digits, we just truncate after many hundreds of digits... but if what we truncate is all made of zeroes, then we may get the wrong final results because the truncated flag assumes that you have a non-zero truncated part.

Taking a float and adding hundreds of zeros, you may get a truncated value that is just one over the desired value (bug fix)

---

include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h

Fixes #1358.
It's clearly better. In fact, it's unequivocally better, in all circumstances. Oddly, in a couple of important cases, the *fallback* frontend beats the haswell frontend. Not sure what to think of that. Maybe jitters. I ran all of them twice to check (all 4 once, then all 4 again).
| Branch | Stage 1 | On Demand | partial tweets | large random | large random unordered | kostya | distinct user id | find tweet | Host | Compiler | cmake |
|---|---|---|---|---|---|---|---|---|---|---|---|
| PR | haswell | haswell | **4.10 GB/s** | 0.69 GB/s | 0.70 GB/s | 2.25 GB/s | 3.97 GB/s | 5.80 GB/s | Skylake | Clang 10 | CXX_FLAGS=-march=native |
| PR | haswell | fallback | 3.55 GB/s | **0.70 GB/s** | **0.71 GB/s** | **2.27 GB/s** | **4.23 GB/s** | **5.83 GB/s** | Skylake | Clang 10 | |
| …

Use runtime-selected implementation for stage 1 on demand

---

.github/workflows/alpine.yml
.github/workflows/fuzzers.yml
.github/workflows/mingw-ci.yml
.github/workflows/mingw64-ci.yml
.github/workflows/msys2.yml
.github/workflows/power-fuzz.yml
.github/workflows/ubuntu18-checkperf.yml
.github/workflows/ubuntu18-threadsani.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20-checkperf.yml
.github/workflows/ubuntu20-threadsani.yml
.github/workflows/ubuntu20.yml
.github/workflows/vs16-ci.yml
.github/workflows/vs16-clang-ci.yml
.github/workflows/vs16-ninja-ci.yml
CONTRIBUTING.md

This will enable usage of `[skip ci]` and `[skip github]` for Github workflows and documents it in the contribution guidelines for changes that are not necessary to be tested in CI.
Fixes https://github.com/simdjson/simdjson/issues/1313

[skip ci] Skip CI for Github

---

tests/basictests.cpp

The following has always worked:
```C++
dom::element node = object["a"];
auto mylambda = [](dom::element e) { return int64_t(e); };
ASSERT_EQUAL( mylambda(node), 1 );
```
What the issue is, is to make the following work...
```C++
simdjson_result<dom::element> node = object["a"];
auto mylambda = [](dom::element e) { return int64_t(e); };
ASSERT_EQUAL( mylambda(node), 1 );
```
Related to https://github.com/simdjson/simdjson/issues/1341

This adds a test to explain better the issue 1341: Support conversion of simdjson_result lvalue to dom::element

---

include/simdjson/arm64/bitmanipulation.h
include/simdjson/dom/document-inl.h
include/simdjson/dom/parser-inl.h
include/simdjson/fallback/numberparsing.h
include/simdjson/generic/jsoncharutils.h
include/simdjson/generic/numberparsing.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/raw_json_string-inl.h
include/simdjson/haswell/bitmanipulation.h
include/simdjson/haswell/simd.h
include/simdjson/haswell/stringparsing.h
include/simdjson/internal/jsonformatutils.h
include/simdjson/padded_string-inl.h
include/simdjson/ppc64/bitmanipulation.h
include/simdjson/westmere/bitmanipulation.h
include/simdjson/westmere/simd.h
src/fallback/dom_parser_implementation.cpp
src/generic/stage1/buf_block_reader.h
src/generic/stage1/utf8_validator.h
src/generic/stage2/logger.h
src/implementation.cpp

No bug replacement
No performance change
All tests passed by "make test"
Only changes are old c-style casts to modern c++ casts to compile with 
CXXFLAGS = -Werror=old-style-cast -pedantic -Wpedantic -Wall -Wextra
Please suggest to change coding style to only use c++ casts

partly replacement for old-style-cast (*) to c++-casts *_cast<>()

---

CMakeLists.txt

A recent refactoring cleaned up the list of exported targets and introduced the use of the `CMakePackageConfigHelpers` utilities. Unfortunately it seems that the generated `simdjson-config.cmake` file was not added to the `install` target. This oversight trips up downstream users of the library that rely on the exported targets mechanism.
Specifically, the code `find_package(simdjson)` will fail. This can be worked around by adding
```
find_package(simdjson
CONFIGS
"simdjson-config.cmake"
"simdjson-targets.cmake")
```
But figuring that out costs time, especially for users that are not familiar with CMake.
Additionally, the 3rd commit adds a `simdjson-config-version.cmake` file to allow a version check in `find_package`.
Additionally, the library's soversion was still at "7.0.0". I'm not …

Fix the CMake generated install target

---

include/simdjson/dom/array-inl.h
include/simdjson/dom/array.h

So I propose to rename 'slots' to 'number_of_slots'. This is an API breaking change but I believe that the number of users is small.

It appears that Qt uses macros for common terms like slots, signals and so forth.

---

doc/basics.md
doc/basics_doxygen.md
include/simdjson.h
tests/readme_examples.cpp

The examples currently fail under the latest Xcode (Apple clang version 12.0.0):
```
readme_examples.cpp:84:21: error: loop variable 'key_value' is always a copy because the range of type 'dom::object' does not return a reference [-Werror,-Wrange-loop-analysis]
for(const auto& key_value : obj) {
^
readme_examples.cpp:84:9: note: use non-reference type 'simdjson::dom::key_value_pair'
for(const auto& key_value : obj) {
```
Hopefully, `simdjson::dom::key_value_pair` is a lightweight object?
Note that we do not appear to use this construction anywhere else, but in our examples.

Why would you use a reference when looping?

---

include/simdjson/generic/numberparsing.h

On partial_tweets, this moves the performance from 2.95 GB/s (on jkeiser/array-assert) to over 3 GB/s (on par with our main branch).
Note that this a PR to be applied on jkeiser/array-assert at https://github.com/simdjson/simdjson/pull/1414

Potential optimizations applied to jkeiser/array-assert

---

tests/document_stream_tests.cpp

Under the clang compiler and in one particular CI setting (drone) we very rarely get (non reproducible) failure in one particular test. This test was poorly named. I have renamed it and I have introduced a loop so that the same test is repeated 1000 times instead of being one test. In case of failure, it will also provide more information.
Running it locally with all sorts of sanitizers seems to do no good. No data trace or anything gets detected.
This is an odd one.
Helps with https://github.com/simdjson/simdjson/issues/1370

This should make issue 1370 easier to track.

---

include/simdjson/error.h
include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/object-inl.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
src/internal/error_tables.cpp
tests/ondemand/ondemand_error_tests.cpp

Because On Demand keeps a single cursor across multiple iterators, arrays and objects can only be iterated through when the cursor is in position at the array or object. If used incorrectly, the cursor will move to the wrong places.
This PR gives people runtime errors when iteration happens out of order, instead of weird, hard to diagnose errors. It creates a new error_code, OUT_OF_ORDER_ERROR, and yields it in these scenarios:
* Yields OUT_OF_ORDER_ERROR if you attempt to iterate (begin()) an array or object when the cursor is *anywhere* except the start of the array or object.
* Yields OUT_OF_ORDER_ERROR if you look up an object field when the cursor is outside the object (at a low depth).
The above checks can be done using information we already have, comparing the object / array index …

Add safety checks for out of order array/object iteration+indexing

---

.github/workflows/vs15win32-ci.yml

Hunting for build issues with respect to https://github.com/simdjson/simdjson/issues/1437
Note that Win32 builds are not officially supported, we offer some fallback but users should not use Win32 with simdjson.

Adding legacy Win32 / Visual Studio 2017 CI tests to GitHub Actions.

---

include/simdjson/dom/document-inl.h
include/simdjson/dom/document.h
include/simdjson/dom/document_stream-inl.h
include/simdjson/dom/parser-inl.h
include/simdjson/dom/parser.h
tests/basictests.cpp
tests/readme_examples_noexceptions.cpp

In the DOM API, we tied the parser to the document leading to issue https://github.com/simdjson/simdjson/issues/1332 where people who want to use the DOM for storage have to also keep the parser. This separates the two effectively. You can now provide your own document instance, and while there will still be a parser's document instance, it may never be used (and allocated) if you don't want it. 
You can now do the following...
```C++
auto input = "[1, 2, 3]"_padded;
dom::document doc;
{
dom::parser parser;
element doc_root = parser.parse_into_document(doc, input);
if(simdjson::to_string(doc_root) != "[1,2,3]") { return false; }
// parser will go out of scope here.
}
if(simdjson::to_string(doc.root()) != "[1,2,3]") { return false; }
dom::parser parser; // new parser
element doc_root1 = …
```

This makes it possible to a have document instance (DOM) that is separate from the parser if you would like.

---

benchmark/bench_dom_api.cpp
fuzz/fuzz_dump.cpp
include/simdjson/dom/element.h
include/simdjson/dom/object.h
include/simdjson/error-inl.h
include/simdjson/generic/implementation_simdjson_result_base-inl.h
include/simdjson/generic/ondemand/document.h
tests/basictests.cpp
tests/integer_tests.cpp

The intention is to remove the `get<T>()` methods from our public API so users will need to write `get_object()` instead of `get<simdjson::dom::object>()`, and write `get_uint64()` instead of `get<uint64_t>()`. In practice, we found that the templated API seemed to some users as 'extensible' when it is not. That is, some users felt that they should be able to provide any type (e.g., `get<QString>()`) when there never was any mechanism for that. 
Note that it is still possible for people to write templated code on top of simdjson such as `(T)e` ( cast) or `T x; e.get(x)` (non-templated get function).
I do not deprecate the functions formally because we use them all over the place internally, and I see no reason for the moment to refactor our code. So we just take it off of our public API …

Fixing issue 1449.

---

include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/array_iterator-inl.h
include/simdjson/generic/ondemand/object-inl.h
include/simdjson/generic/ondemand/object_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
tests/ondemand/ondemand_array_error_tests.cpp
tests/ondemand/ondemand_object_error_tests.cpp
tests/ondemand/ondemand_scalar_tests.cpp
tests/test_macros.h

Right now, loops aren't reporting the out of order iteration error when you actually descend into the loop. This masked a bug where we were reporting out of order iteration error for empty arrays! This fixes both bugs.
It has no impact on performance, as far as I can tell.
This PR is based against #1432, to avoid conflicts.

Fix bug reporting out of order iteration

---

include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/object-inl.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
tests/ondemand/ondemand_array_error_tests.cpp
tests/ondemand/ondemand_object_error_tests.cpp

This is the same potential buffer overrun we found in DOM, where you must have an invalid document that:
* Has an unclosed array or object at the top level
* Terminates with a number that goes right up to EOF
* Has the padding filled entirely with digits
* And in ondemand's case, you also need to be trying to *parse* the number instead of just skipping it
This didn't even change instruction count when I checked performance, which surprised me. But the tests demonstrate it's definitely being checked.
This is the final known bug in ondemand. All that's left are API changes (.type() and iterate() over a user-owned buffer being the main ones) and features, if we decide to do those. (JSON Path is pretty tempting and super easy.)
This is based off of #1452 .

Fix ridiculously unlikely buffer overrun in ondemand

---

include/simdjson/dom/element.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value.h

Lesson learned. When you use a template in a public API, people will expect the template to work with any type that they may provide. If you fail to provide a definition for their chosen type, the compiler should issue a warning, but more importantly, it will let it compile and the fatal error will occur at link time when no definition is found. This leads users to think that there is some problem with the build.
To put it differently, when using templates in C++ as part of a public API, you should expect users to try anything at all... and unless you are ok with mysterious failures, you want to validate somehow the type that they provide.
Instead, we want the code to fail immediately at compile time when using a template function that is undefined. You can achieve the result with a …

Guarding undefined templates with a static_assert.

---

include/simdjson/generic/ondemand/json_iterator-inl.h

It seems that some compilers require that SIMDJSON_ASSUME(x) has no side-effects. The following PR should satisfy them.

Workaround for SIMDJSON_ASSUME "side-effect" warning under some compilers.

---

.github/workflows/ubuntu20-noexcept.yml
cmake/simdjson-flags.cmake

Should be self-explanatory. Currently we only check for the no-exception usage under Windows.

This adds tests for the no-exception variant of the library usage under linux.

---

.github/workflows/ubuntu20-nothread.yml

We do not fully test the usage without threads under Linux (complete with installation).

This adds tests without threads under linux.

---

cmake/simdjson-flags.cmake

It probably cannot harm performance but even so, the issue is less about performance than hygiene. It seems that GNU GCC tunes by default for Sandy Bridge processors... yet we don't use AVX under such old processors. The flags are chosen to target a specific problems whereas unaligned loads/stores under AVX are executed as two instructions by GNU GCC instead of one obvious instructions. Note that clang does not have this problem.
Fixes https://github.com/simdjson/simdjson/issues/1461

Throwing -mno-avx256-split-unaligned-load -mno-avx256-split-unaligned-store at GNU GCC under x86/x64 systems.

---

include/simdjson/dom/document_stream-inl.h
include/simdjson/dom/document_stream.h

Hello,
I’ve changed dom::document_stream::iterator to hold a pointer to underlying document_stream instead of reference. This allowed to implement default constructor and make the iterator copyable (#1447 ).
Looking forward for you feedback.
Alexey

Make dom::document_stream::iterator copyable and default-constructible

---

tests/document_stream_tests.cpp

Minimal tests for  https://github.com/simdjson/simdjson/pull/1463
Fixes dlemire/issue1446

Test that we can copy the document_stream iterators.

---

doc/tape.md
include/simdjson/dom/document-inl.h

Should be self-explanatory. The tape specification changed slightly with the introduction of saturated counts and we did not update the documentation or the dump_tape function.
Fixes https://github.com/simdjson/simdjson/issues/1446

Update the tape description and the dump_tape function

---

.github/workflows/vs15-ci.yml
.github/workflows/vs16-ci.yml
include/simdjson/arm64/simd.h
include/simdjson/haswell/simd.h
include/simdjson/ppc64/simd.h
include/simdjson/westmere/simd.h
src/arm64/dom_parser_implementation.cpp
src/generic/stage1/json_minifier.h
src/generic/stage1/json_scanner.h
src/generic/stage1/json_string_scanner.h
src/generic/stage1/json_structural_indexer.h
src/haswell/dom_parser_implementation.cpp
src/ppc64/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp

We have found some inlining issues under Visual Studio 2017 when compiling a DLL. See issue https://github.com/simdjson/simdjson/issues/1475
Some of these functions return a json_block using an implicit struct constructor.
What this PR does is to specify very precisely which constructor should be called.
We also make json_block uncopyable, so it is being passed by reference. 
None of this should make any difference given that all these functions are forceably inlined... so any copy that may happen should be elided.
However, the theory is that the compiler will find it easier to figure out that all of this can be inlined.
Fixes https://github.com/simdjson/simdjson/issues/1475

Ensuring that stage 1's json_block and cie are never copied and using explicit constructors (issue 1475)

---

doc/ondemand.md
include/simdjson.h
include/simdjson/error.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
include/simdjson/padded_string-inl.h
include/simdjson/padded_string.h
include/simdjson/padded_string_view-inl.h
include/simdjson/padded_string_view.h
src/internal/error_tables.cpp
tests/ondemand/compilation_failure_tests/CMakeLists.txt
tests/ondemand/compilation_failure_tests/iterate_char_star.cpp
tests/ondemand/compilation_failure_tests/iterate_string.cpp
tests/ondemand/compilation_failure_tests/iterate_string_view.cpp
tests/ondemand/ondemand_parse_api_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

This allows On Demand to parse user-provided buffers. It differs from the DOM implementation in that it requires a third "capacity" parameter to communicate the padding requirement to the user (you can't pass in a raw string without at least passing the number of allocated bytes, and that will prompt looking up the docs for *why* you need to pass that). It supports std::string without parameters, because std::string publishes its capacity.
```c++
ondemand::parser parser;
char json[3+SIMDJSON_PADDING];
strcpy(json, "[1]");
ondemand::document doc = parser.iterate(json, strlen(json), sizeof(json));
```
If the padding is insufficient, parser.iterate() will return an INSUFFICIENT_PADDING error.
This, along with #1472 , is the last of the On Demand fixes that seemed crucial to me.

Support user-provided buffers in On Demand

---

include/simdjson/error.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/CMakeLists.txt
tests/ondemand/ondemand_misc_tests.cpp

Someone was asking for the ability to parse numbers themselves, their own way, and I think it's a really good thing to have around (it makes it easy to bring strings and numbers into your own format).

Add value.raw_json_token()

---

doc/ondemand_design.md
include/simdjson/generic/ondemand/field.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/raw_json_string-inl.h
include/simdjson/generic/ondemand/raw_json_string.h
include/simdjson/generic/ondemand/value.h
include/simdjson/generic/ondemand/value_iterator-inl.h
tests/ondemand/ondemand_compilation_tests.cpp
tests/ondemand/ondemand_object_tests.cpp

The raw_json_string is unsafe in some ways and this PR makes it better. One key design constraint is that raw_json_string is unaware of this length. It has no idea. You have do everything manually. This exposes you to buffer overruns and to incorrect comparisons.
Two problems could happen:
A. The comparator  just did byte-by-byte (memcmp) comparison without checking for the final quote. So the keys "ab" and "ac" would both match "a". That's pretty bad.
B. Just as bad, you could pass "ababaababababababababababa...aaa" (make it very long) as a potential key against the json document `{"a":1}` and it would just happily compare, reading inside the JSON input for as long as you want (buffer overflow!!!).
So there are two types of algorithm you could use:
1. Find some bound on how far off you …

fixing issue 1480

---

README.md
doc/dom.md
doc/performance.md
tests/readme_examples.cpp

What I did is push the DOM specific performance notes in the new dom.md document. I removed irrelevant (DOM) content from the performance notes and update a subset of it, along with new tests.
It exposes some limitations of On Demand. I will open issues.

Port the performance notes to "on demand".

---

.travis.yml

We use travis for POWER testing. The sanitizer runs always fail. This could be fixed, but we have more urgent matters. So I am just disabling them.

This will disable the sanitizer runs on travis.

---

tests/document_stream_tests.cpp

This comment is the result from a bad copy-paste.

Removing a misleading comment in the tests.

---

include/simdjson/common_defs.h
include/simdjson/generic/ondemand/json_iterator-inl.h
tests/ondemand/ondemand_object_tests.cpp

The core issue seems to be with skip_child. The skip_child function makes some assumption regarding the state you are in. In particular, it seems that you cannot be right before a key so that the first step of skip_child is to bring you to a key. That's never a problem when the key you are searching for is found. When the key you are searching found is not found, then it is possible that you may end up just before a key.
By convention, keys are at the level of the object, so the code in the main branch and in the 0.9.x is wrong in such cases because skip_child will encounter a key, it will decrement the depth and conclude that it is back in the parent. This is bad.
This is not the nicest fix in the world and it may have small negative impact on performance but I am preoccupied by patching …

My third attempt at fixing issue 1521 (not being merged due to performance concerns)

---

.github/workflows/fuzzers.yml
fuzz/quick_check.sh

bintray is sunsetted May 1:st, switching to github action cache instead.
Using the github action cache is previously tested on the boost json project (by me) and it seems to be good enough for this purpose. The bad thing is that it is not easy to get hold of the corpus as before (as needed in the fuzz/quick_check.sh script), one has to download it manually, being logged in into github. 
If merging, don't forget to remove the bintray secrets from the github config.

use github action cache instead of bintray

---

doc/basics.md

Updates basics.md with typo correction of were --> where.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Fix minor typo in basics.md

---

benchmark/benchmarker.h
benchmark/statisticalmodel.cpp
doc/parse_many.md
include/simdjson/dom/document_stream-inl.h
include/simdjson/dom/document_stream.h
include/simdjson/generic/dom_parser_implementation.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/internal/dom_parser_implementation.h
src/arm64/dom_parser_implementation.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/stage1/find_next_document_index.h
src/generic/stage1/json_structural_indexer.h
src/haswell/dom_parser_implementation.cpp
src/ppc64/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp
tests/basictests.cpp
tests/document_stream_tests.cpp
tests/document_tests.cpp
tests/errortests.cpp
tests/parse_many_test.cpp
tests/readme_examples.cpp

Currently, when using parse_many, if there is an unclosed final string, then a whole block (e.g., 1 MB) of stage 1 processing is wasted since stage 1 ends in error. Thus we must instruct users not to provide ndjson inputs with unclosed final string...
This PR would tolerate a final unclosed string. What it does is to exclude the unclosed string (it is virtually removed) as well as other "trailing garbage".
The downside of this approach is that a final unclosed string gets ignored, so it is possible to have garbage as part of your stream and be unaware if the garbage is part of an unclosed string. Users are expected to call the `truncated_bytes()` to see whether truncation occurs. If so, they have to handle these leftover bytes somehow.
It is mostly a quality-of-life issue.

Document stream: truncate final unfinished document and give access to the number of truncated bytes.

---

include/simdjson/dom/parser-inl.h

Use the dom::parser internal loaded_bytes buffer as a tmp padded buffer when realloc_if_needed is true.
Motivation: 
* Avoid allocating a new buffer for every parse when realloc_if_needed
* If it's good enough for file parsing (doesn't adjust capacity downwards) it should be good enough for this use case

Use the dom::parser internal loaded_bytes buffer as a tmp padded buffer when realloc_if_needed

---

benchmark/Dockerfile
include/simdjson.h
include/simdjson/common_defs.h
include/simdjson/dom/document-inl.h
jsonexamples/small/jsoniter_scala/README.md
tests/document_tests.cpp

Switch links (mostly in comments) from old repository URL <https://github.com/lemire/simdjson/> to the current URL <https://github.com/simdjson/simdjson/>.

adjust GitHub links to current repository URL

---

src/arm64/implementation.cpp
src/fallback/implementation.cpp
src/haswell/implementation.cpp
src/ppc64/implementation.cpp
src/westmere/implementation.cpp

Or else we can hit nullptr segfault in various places such as
https://github.com/simdjson/simdjson/blob/master/src/generic/stage2/tape_builder.h#L193
This issue is found in ClickHouse when using JSON functions in memory intensive environment

Return err when encountering memory allocation failures

---

include/simdjson/generic/ondemand/serialization.h
tests/ondemand/ondemand_tostring_tests.cpp

When calling `simdjson::to_string` on an `simdjson_result<T>` instance, the code would default to DOM even when `T` was part of the ondemand API.
Fixes https://github.com/simdjson/simdjson/issues/1579

Fixing issue 1579 (to_string compilation errors)

---

doc/basics.md
tests/ondemand/ondemand_misc_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

Some users want to access the values, granting them types that we do not natively support (e.g., big integers). It is possible to do it, and this PR improves the documentation.

Documenting raw string access.

---

.github/workflows/msys2-clang.yml
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/logger-inl.h
include/simdjson/generic/ondemand/logger.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
tests/ondemand/ondemand_object_tests.cpp

We have an issue where when we search for a key and it is not found, we can end up in a poor state from which follow-up queries will cause trouble. See discussion https://github.com/simdjson/simdjson/discussions/1569
This is closely related to bug https://github.com/simdjson/simdjson/issues/1521
I had fixed that bug by allowing us to sometimes end the search while pointing at an arbitrary key within the object, see https://github.com/simdjson/simdjson/pull/1530 But that fix was not sufficient.
I tried harder to make it work in PR https://github.com/simdjson/simdjson/pull/1573 but the complexity seems to only grow.
The new PR goes back to an earlier idea expressed by PR https://github.com/simdjson/simdjson/pull/1524
The idea, simply put, is that instead of allowing us to finish the call to …

Restricting how we can end key searches

---

include/simdjson/generic/ondemand/value_iterator-inl.h
tests/ondemand/ondemand_object_tests.cpp

When find_field_unordered is used on an empty object, it calls
json_iterator::reenter_child. reenter_child asserts that it doesn't
rewind too far back by consulting parser->start_positions.
When the On Demand parser sees an empty object, it fails to update
parser->start_positions. This means that the assertion in
json_iterator::reenter_child reads stale data, or potentially
uninitialized memory. Reading uninitialized memory can cause spurious
assertion failures and Valgrind memcheck reports:
Running missing_keys_for_empty_top_level_object ...
==170679== Conditional jump or move depends on uninitialised value(s)
==170679==    at 0x4943D7: reenter_child (json_iterator-inl.h:208)
==170679==    by 0x4943D7: find_field_unordered_raw (value_iterator-inl.h:197)
==170679==    by 0x4943D7: …

Fix UB in dev checks when iterating empty object

---

benchmark/bench_ondemand.cpp
benchmark/kostya/nlohmann_json_sax.h
benchmark/kostya/rapidjson_sax.h

This adds RapidJSON and nlohmann_json SAX API for kostya benchmark. Using SAX is much faster than using their regular counterparts:
<table>
<tr><td>
|-----|-----|
|kostya<rapidjson>/manual_time|0.57GB/s|
|kostya<rapidjson_lossless>/manual_time|0.53GB/s|
|kostya<rapidjson_insitu>/manual_time|0.63GB/s|
|kostya<rapidjson_sax>/manual_time|0.85GB/s|
|kostya<nlohmann_json>/manual_time|0.08GB/s|
|kostya<nlohmann_json_sax>/manual_time|0.17GB/s|
</td></tr>
</table>
For reference simdjson_ondemand has a throughput of 2.29GB/s.
(edit: fix wrong value for rapidjson_sax)

Add RapidJSON and nlohmann_json SAX to kostya benchmark

---

CMakeLists.txt

It is a good idea to only build the library by default, but it can be hard for people who want to run the tests to figure out  how to do it. This PR adds a warning message with instructions.

Adds a warning message when SIMDJSON_DEVELOPER_MODE is OFF.

---

cmake/developer-options.cmake
windows/getopt.h

By default CMake does not set /permissive- but it is the default for new projects with Visual Studio 2019.

This adds /permissive- to recent visual studio builds

---

benchmark/bench_ondemand.cpp
benchmark/distinct_user_id/nlohmann_json_sax.h
benchmark/distinct_user_id/rapidjson_sax.h

This adds RapidJSON SAX and nlohmann_json SAX for distinct_user_id benchmark. Results:
<table>
<tr><td>
|-----|-----|
|distinct_user_id<rapidjson>/manual_time |0.41GB/s|
|distinct_user_id<rapidjson_insitu>/manual_time|0.77GB/s|
|distinct_user_id<rapidjson_sax>/manual_time|0.43GB/s|
|distinct_user_id<nlohmann_json>/manual_time|0.08GB/s|
|distinct_user_id<nlohmann_json_sax>/manual_time|0.16GB/s|
|distinct_user_id<simdjson_ondemand>/manual_time|3.51GB/s|
</td></tr>
</table>
For nlohmann_json, performance is doubled. However, for RapidJSON, SAX is slightly better than base RapidJSON, but is quite under …

Add RapidJSON and nlohmann_json SAX to distinct_user_id benchmark

---

benchmark/bench_ondemand.cpp
benchmark/find_tweet/nlohmann_json_sax.h
benchmark/find_tweet/rapidjson.h
benchmark/find_tweet/rapidjson_sax.h

This adds RapidJSON and nlohmman_json SAX to find_tweet benchmark. Performance results:
<table>
<tr><td>
|-----|-----|
|find_tweet<rapidjson>/manual_time |0.40GB/s|
|find_tweet<rapidjson_insitu>/manual_time|0.59GB/s|
|find_tweet<rapidjson_sax>/manual_time|4.68GB/s|
|find_tweet<nlohmann_json>/manual_time|0.08GB/s|
|find_tweet<nlohmann_json_sax>/manual_time|1.31GB/s|
|find_tweet<simdjson_ondemand>/manual_time|4.72GB/s|
</td></tr>
</table>
Very significant increase between SAX and their dom couterparts. rapidjson_sax is very close to simdjson_ondemand for this benchmark, but simdjson_ondemand still holds the edge. …

Add RapidJSON and nlohmann_json SAX to find_tweet benchmark

---

benchmark/bench_ondemand.cpp
benchmark/top_tweet/nlohmann_json_sax.h
benchmark/top_tweet/rapidjson.h
benchmark/top_tweet/rapidjson_sax.h

This adds RapidJSON and nlohmann_json SAX to the top_tweet benchmark. Performance results:
<table>
<tr><td>
|-----|-----|
|top_tweet<rapidjson>/manual_time |0.41GB/s|
|top_tweet<rapidjson_insitu>/manual_time|0.57GB/s|
|top_tweet<rapidjson_sax>/manual_time|0.60GB/s|
|top_tweet<nlohmann_json>/manual_time|0.07GB/s|
|top_tweet<nlohmann_json_sax>/manual_time|0.14GB/s|
|top_tweet<simdjson_ondemand>/manual_time|3.46GB/s|
</td></tr>
</table>
rapidjson_sax is ahead of rapidjson_insitu (+5%) and same for nlohmann_json_sax and nlohmann_json (+100%).

Add RapidJSON and nlohmann_json SAX to top_tweet benchmark

---

benchmark/bench_ondemand.cpp
benchmark/partial_tweets/nlohmann_json_sax.h
benchmark/partial_tweets/rapidjson_sax.h

This adds RapidJSON and nlohmann_json SAX to the partial_tweets benchmark. Performance results:
<table>
<tr><td>
|-----|-----|
|partial_tweets<rapidjson>/manual_time |0.42GB/s|
|partial_tweets<rapidjson_insitu>/manual_time|0.76GB/s|
|partial_tweets<rapidjson_sax>/manual_time|0.65GB/s|
|partial_tweets<nlohmann_json>/manual_time|0.08GB/s|
|partial_tweets<nlohmann_json_sax>/manual_time|0.14GB/s|
|partial_tweets<simdjson_ondemand>/manual_time|3.04GB/s|
</td></tr>
</table>
rapidjson_sax is still behind rapidjson_insitu, so there might be some optimisations or a better approach than the one I used, but for now, this is …

Add RapidJSON and nlohmann_json SAX to partial_tweets benchmark

---

tests/dom/CMakeLists.txt
tests/dom/numberparsingcheck.cpp
tests/dom/stringparsingcheck.cpp

This makes numberparsingcheck and stringparsingcheck use simdjson.cpp / simdjson.h. Because number / string parsing are now inline functions in the headers, our callbacks will be called just fine without having to include simdjson.cpp.
Fixes #1604.

Don't #include "simdjson.cpp" in tests

---

doc/parse_many.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_parse_api_tests.cpp

This took me a ridiculous amount of time because I assumed that `operator=` copied all of the fields. Somehow it omitted the error field.
Fixes https://github.com/simdjson/simdjson/issues/1601

Verification and bug fix of issue 1511

---

.circleci/config.yml
.drone.yml
.github/workflows/ubuntu18-threadsani.yml
.github/workflows/ubuntu20-threadsani.yml
.travis.yml
cmake/developer-options.cmake
include/simdjson/common_defs.h

For some unclear reasons, @jkeiser 's latest PR (no-padding-scalar) has CI failures related to sanitized tests. I suspect a stack issues. Thus this PR introduces a new CMake option that may help (SIMDJSON_NO_FORCE_INLINING).

I suspect that sanitizers might increase stack usage, to combat that you may set SIMDJSON_NO_FORCE_INLINING

---

benchmark/bench_ondemand.cpp
benchmark/distinct_user_id/simdjson_dom_json_pointer.h
benchmark/distinct_user_id/simdjson_ondemand_json_pointer.h

This adds two JSON pointer benchmark (DOM and On Demand) for the distinct_user_id benchmark.
Performance:
<table>
<tr><td>
|-----|-----|
|distinct_user_id<simdjson_dom>/manual_time |2.41GB/s|
|distinct_user_id<simdjson_dom_json_pointer>/manual_time|2.34GB/s|
|distinct_user_id<simdjson_ondemand>/manual_time|3.49GB/s|
|distinct_user_id<simdjson_ondemand_json_pointer>/manual_time|3.02GB/s|
</table>
DOM is not that much affected by the usage of JSON pointer (-2.9%) while On Demand is significantly slower (-15%). Comparing both JSON pointers approach, we see that On Demand JSON pointer is much faster than DOM JSON pointer.
Remark: I used a relative path by iterating over each tweet in the json file instead of …

Add JSON pointer benchmark for distinct_user_id

---

doc/basics.md

@erichutchins wrote:
> That iterate doesn’t fully validate the JSON input. Maybe this is more broadly a “when to use DOM vs OnDemand” observation, but it just surprised me when OnDemand happily extracted a field that DOM (and jq) wouldn’t because of an error/typo elsewhere on the log line. Makes perfect sense, but might be a good thing to emphasize
> I don’t understand the escaped vs unescaped key nuance. Could you provide an example?
This is my attempt at improving the documentation to answer these questions.

Improving the documentation: escaping keys and "validate what you use"

---

include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_json_pointer_tests.cpp

`at_pointer` now automatically rewinds each call (as per #1622). The rewind is done at the beginning of the call, before any parsing is done. This is something we would want to mention in the documentation. Furthermore, it will also be important to mention to the user that `rewind` invalidates certain values (objects/arrays), and so it is important to store/consume them independently between each call of `at_pointer` which rewinds automatically now. This PR just implements the automatic rewind feature, the documentation issue will be fixed by #1618.
Fixes #1622

Add automatic rewind for at_pointer

---

include/simdjson/generic/ondemand/document.h
tests/ondemand/ondemand_json_pointer_tests.cpp

When calling `at_pointer` under the On Demand front-end, we invalidate all previous values. This needs to be clearly stated.

This better documents invalidation.

---

.gitattributes
.gitignore
.vscode/extensions.json
.vscode/settings.json
tests/docker/Dockerfile

This adds some workspace level settings for .vscode. As best I can tell, workspace-level settings.json is considered something you check in to the project, while user-level settings are for, well, the user :)
The main reason I did this is I want it to auto-trim whitespaces at the end of the line when saving. It's driving me crazy having to patch up my PRs :)
This also adds a few recommended extensions for the project (which VS Code can show the user if they bring it up).

Add .vscode workspace settings

---

.vscode/settings.json
include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h

I think is_at_container_start() is useless and should be removed.
I have added some documentation regarding is_at_iterator_start(), move_at_start(), enter_at_container_start(). They appear to be used only for arrays.

Removes is_at_container_start() and documents is_at_iterator_start(), move_at_start(), enter_at_container_start() 

---

include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_json_pointer_tests.cpp

In https://github.com/simdjson/simdjson/pull/1618, @NicolasJiaxin documents the general usage of JSON pointers on top of On Demand. For document instances, we rewind/invalidate between each query at the beginning of each JSON pointer query. To recap, we rewind and reset the string buffer. The expectation is that people consume the result of a JSON pointer by, for example, copying the data into their own data structures.
However, somewhat discreetly, we also allow JSON pointer queries on arrays and object types. They are not formally supported by the standard. In such cases, we do not rewind. Rewinding at the component level would be problematic because the general JSON pointer implementation calls the component's JSON pointer implementation.
Currently, the behavior is as follows:
1. For …

Partial documentation regarding relative JSON pointers.

---

include/simdjson/generic/ondemand/logger-inl.h

This might improve the usability of the logging.

This should print out (once) some instructions to interpret the logging traces.

---

.drone.yml
.github/workflows/fuzzers.yml
.github/workflows/power-fuzz.yml
fuzz/Fuzzing.md

This stores the the corpus on my server. The main github action fuzzer uploads the corpus repeatedly. The other fuzz jobs take the corpus from the server.
The arm64 fuzzer job was disabled, it is now enabled again.
The power fuzzer job was not running because of an .yml syntax error. It is now working.

Get fuzzing working again

---

.vscode/settings.json
src/generic/stage1/json_structural_indexer.h
tests/dom/document_stream_tests.cpp

In document streaming, we divide the input in non-overlapping windows. The end of the windows needs to be adjusted. In particular, you cannot end a window in the middle of an UTF-8 character.
In some cases, in document streaming, you would get a window containing what looks like trailing UTF-8 garbage. The code trims it out because it assumes that it needs to be processed as part of the next window (so we get full UTF-8 characters). It could leave you with a window of size zero in some adversarial cases. It would then return EMPTY, and the document stream would try to process it again, and again and again, thinking that there is just a lot of leading white space. This PR fixes the issue by returning an UTF8_ERROR when the window ends up containing only trailing UTF-8 garbage.
Credit to …

Fuzzing timeout  (bug fix)

---

.vscode/settings.json
benchmark/linux/linux-perf-events.h

Some symbolic files would never be closed. It never causes any problem but, in theory, it could exhaust the number of files that can be open at once... especially if the process was long lived.
(This is nitpicking.)

This solves a minor issue with our legacy benchmark tools.

---

.vscode/settings.json

It is fine to have settings.json in the repo, but only if the editor is forbidden from automatically updating it.

Let us stop visual studio code from constantly updating settings.json

---

fuzz/build_fuzzer_variants.sh
fuzz/quick_check.sh

When run, gives stuff like this.
Build with:
fuzz/build_fuzzer_variants.sh
run with:
build-threadsanitizer-O1/fuzz/fuzz_ndjson 
And get something like this:
```
INFO: Seed: 3844882090
INFO: Loaded 2 modules   (4268 inline 8-bit counters): 3757 [0x7f7bdf0b5cc8, 0x7f7bdf0b6b75), 511 [0x533ea8, 0x5340a7), 
INFO: Loaded 2 PC tables (4268 PCs): 3757 [0x7f7bdf0b6b78,0x7f7bdf0c5648), 511 [0x5340a8,0x536098), 
INFO:     3832 files found in out/ndjson/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 3832 min: 1b max: 4089b total: 780813b rss: 103Mb
==================
WARNING: ThreadSanitizer: data race (pid=22655)
Write of size 1 at 0x000000533ff2 by main thread:
#0 std::unique_lock<std::mutex>::unique_lock(std::mutex&) …
```

[WIP] ndjson thread sanitizer

---

benchmark/amazon_cellphones/simdjson_ondemand.h
benchmark/large_amazon_cellphones/simdjson_ondemand.h
doc/basics.md
doc/iterate_many.md
include/simdjson/generic/implementation_simdjson_result_base-inl.h
include/simdjson/generic/implementation_simdjson_result_base.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/document_stream-inl.h
include/simdjson/generic/ondemand/document_stream.h
include/simdjson/generic/ondemand/serialization-inl.h
include/simdjson/generic/ondemand/serialization.h
tests/ondemand/ondemand_document_stream_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

@erichutchins identified a bug with our unreleased On Demand stream support. In case of error, you could get a null pointer access and a crash.
The problem is not that our code did not catch the error. It did. However, it would never pass it to the user. So the user would just happily continue after the error, and get a crash.
This commit updates the previous behavior of the On Demand stream support by returning a value type (`document_reference`) instead of a reference to a document. This allows us to bridge with the usually simdjson
error system, with its `simdjson_result` types. We had discussed such a design but it felt complex at the time. It is still a mess... since it requires a lot of copying and pasting... but I think it is a net win for the usability.
It makes error handing more …

verify and fix issue 1668

---

doc/basics.md
include/simdjson/dom/document_stream-inl.h
include/simdjson/generic/ondemand/document_stream-inl.h
tests/dom/document_stream_tests.cpp
tests/ondemand/ondemand_document_stream_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

@erichutchins reported that in some case, the truncated-byte functions could report erroneous results. This PR fixes the issue. This PR ports over some tests we recently added from On Demand to DOM. It adds a few checks on truncated-byte functions that we had omitted.

Fix an issue with truncated-byte functions

---

include/simdjson/nonstd/string_view.hpp

@lemire:
This is a rebased version of #1675. Changes are the same, just the parent commit is different.
I submitted this in the hope that it will not encounter the same GitHub Actions issues (_"This request was automatically failed because there were no enabled runners online to process the request for more than 1 days."_) as the other pull request.
__Original message:__
This is the string_view lite header as seen in the current master branch, commit [d27d7b5081406a35b41cb16b321be8833b4cd811](https://github.com/martinmoene/string-view-lite/commit/d27d7b5081406a35b41cb16b321be8833b4cd811), on <https://github.com/martinmoene/string-view-lite>.

update string_view lite to version 1.6.0, attempt 2

---

doc/basics.md
tests/ondemand/ondemand_error_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

We want the document to be as detailed as possible. Let us throw examples.

Adding error handing examples to the documentation

---

include/simdjson/error.h
tests/ondemand/ondemand_error_tests.cpp

These tests illustrate two proper ways to handle error in simdjson: you either catch the exception or you handle error codes. It also fixes a related bug that we uncovered: there is one extra `noexcept` in the operator `<<`. A related test was added.

Fixing noexcept on operator << with simdjson_result.

---

.vscode/settings.json
doc/basics.md
include/simdjson/error.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/parser.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
src/internal/error_tables.cpp
tests/ondemand/ondemand_array_tests.cpp
tests/ondemand/ondemand_json_pointer_tests.cpp
tests/ondemand/ondemand_misc_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp
tests/test_macros.h

This might ease the work of people writing wrappers and so forth.
Note that this was de facto possible with `at_pointer("")`. Except that it was buggy because scalar documents cannot be used as `value` instances. Now we check and throw an error.
credit to @NicolasJiaxin for the idea

Makes it possible to cast a document to a value.

---

benchmark/bench_dom_api.cpp
benchmark/bench_parse_call.cpp
examples/quickstart/quickstart.cpp
examples/quickstart/quickstart2.cpp
examples/quickstart/quickstart2_noexceptions.cpp
examples/quickstart/quickstart_noexceptions.cpp
examples/quickstart/quickstart_ondemand.cpp
examples/quickstart/quickstart_ondemand_noexceptions.cpp
fuzz/fuzz_implementations.cpp
fuzz/fuzz_minifyimpl.cpp
fuzz/fuzz_utf8.cpp
include/simdjson/dom/parsedjson_iterator.h
include/simdjson/internal/jsonformatutils.h
tests/dom/jsoncheck.cpp
tests/dom/minefieldcheck.cpp
tests/dom/numberparsingcheck.cpp
tests/dom/parse_many_test.cpp
tests/dom/random_string_number_tests.cpp
tests/ondemand/test_ondemand.h
tests/test_macros.h
tests/unicode_tests.cpp

Including \<iostream\> has two problems:
* Compile times are worse because of over-inclusion
* Binary sizes are worse when statically linking libstdc++ because
iostreams cannot be dead-code-stripped
simdjson only needs std::ostream. Include the header declaring only what
we need (\<ostream\>), omitting stuff we don't need (std::cout and its
initialization, for example).
This commit should not change behavior, but it might break users who
assume that including \<simdjson/simdjson.h\> will make std::cout
available (such as many of simdjson's own files).
Our tests check whether you have introduced trailing white space. If such a test fails, please check the "artifacts button" above, which if you click it gives a link to a downloadable file to help you identify the issue. You can also run …

Reduce #include bloat (<iostream>)

---

fuzz/Fuzzing.md
fuzz/quick_check.sh

bintray is gone and the fuzz corpus is stored on my server, with publicly available download (but password protected upload). this means the quick fuzz script can use the latest corpus.

[no ci] remove references to bintray

---

include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/value_iterator-inl.h
tests/ondemand/ondemand_array_error_tests.cpp
tests/ondemand/ondemand_misc_tests.cpp

When accessing root arrays and root objects, we would not "abandon" on error. This PR fixes that. credit @NicolasJiaxin 
This PR adds a public "is_alive()" method to do document class. It has not be spread to other related classes such as document_reference since it is expected that it has a narrow usefulness (mostly for us).
The "at" method of the array class is made public (it was protected). Note that it was de facto publicly accessible via the simdjson_result wrapper.
The assert_iterate helper function in ondemand_array_error_tests.cpp has been made more verbose so we can understand what is happening.

Alive fix.

---

include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/object-inl.h
include/simdjson/generic/ondemand/object.h
tests/ondemand/ondemand_array_tests.cpp
tests/ondemand/ondemand_object_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

I am not super happy about exposing these methods, but it appears that we need to be able to scan arrays and objects twice (@NicolasJiaxin ?) in some instances. These rewind functions will do just that.
It is somewhat dangerous and should be used with caution because if you access string values multiple times, it will be unsafe (and inefficient). That is, they do not rewind the string buffer.
Note that this functionality competes with @jkeiser 's 'fork' idea but I really would prefer to release 1.0 in the near future and the fork functionality seems speculative. Currently, we have always just one json_iterator instance, and it seems that fork would allow us to copy that... which could potentially expose other bugs.
The benefit of this implementation is that it is non-invasive, so …

This exposes 'reset' for object and array instances.

---

include/simdjson/arm64/simd.h
include/simdjson/haswell/simd.h
include/simdjson/ppc64/simd.h
include/simdjson/westmere/simd.h
src/generic/stage1/json_minifier.h

This is an optimisation of the arm64 implementation of `simd8x64::compress` for the Apple M1, which increases `fast_minify` benchmark speed by ~39%. The idea is to do twice as many stores, but significantly fewer loads and SIMD operations. I also reduce the number of population counts (as they are four instructions on ARM64, with 15c latency on Apple M1 Firestorm). This PR has not been tested on other CPUs.
The second commit could be removed, as it only accounts for a 3-3.5% speedup, and required changes to non-ARM64-specific code. Theses changes shouldn't change behaviour, performance or code generation, but I'm not set up to test properly.
This PR:
```
------------------------------------------------------------------------------------------------
Benchmark …
```

simd8x64::compress optimisation for Apple M1

---

doc/basics.md
include/simdjson/generic/ondemand/array-inl.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/object-inl.h
include/simdjson/generic/ondemand/object.h
tests/ondemand/ondemand_array_tests.cpp
tests/ondemand/ondemand_object_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

Fixes #1711 
This adds `count_fields()` for objects. It works the same way as `count_elements()` for arrays. Returns a `simdjson_result<size_t>`.

Add count_fields method for objects

---

doc/basics.md
include/simdjson/generic/numberparsing.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/json_type.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
singleheader/simdjson.cpp
singleheader/simdjson.h
tests/ondemand/ondemand_number_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

[@NicolasJiaxin wrote a superb R wrapper using simdjson On Demand](https://github.com/eddelbuettel/rcppsimdjson/pull/75). The wrapper might be limited in performance due to two calls to "get_number()" per number. The first call to "get_number()" is only used to gather the number type. This PR introduces a direct "get_number_type()" function which makes it easy to avoid "get_number(). get_number_type()".

Adding fast "get_number_type()" function, bypassing "get_number()"

---

include/simdjson/generic/ondemand/document-inl.h

Fix regression as per: https://github.com/simdjson/simdjson/pull/1695#pullrequestreview-757266665
```
include/simdjson/generic/ondemand/document-inl.h:530:137: error: extra ';' [-Werror=pedantic]
simdjson_really_inline simdjson_result<const char *> document_reference::current_location() noexcept { return doc->current_location(); };
```

fix redundant ; in document-inl.h

---

fuzz/fuzz_ndjson.cpp
tests/dom/document_stream_tests.cpp
tests/ondemand/ondemand_document_stream_tests.cpp

Recently @pauldreik [made some changes to a fuzz test](https://github.com/simdjson/simdjson/compare/3bd8b0b575f43403705dcce57d427944c11421f8...d28e5534d96a57aae44a6604aa08ab6cea36fa84) and some (incomprehensible to me) warning/bug are reported. I have been unable to reproduce the issue, but this PR aims to help flush it out. The error seems to occur when we take in garbage (a non-UTF8 string input).

Additional ndjson tests.

---

doc/ondemand_design.md
doc/performance.md

Fixes https://github.com/simdjson/simdjson/issues/1718

Moving documentation "Server Loops: Long-Running Processes and Memory Capacity" section  to the right location.

---

doc/basics.md
doc/dom.md
include/simdjson/error.h

This fixes issue 1755 by clearly documenting that error codes are transient: one's application should not depend on specific error codes. We guarantee that the "false" error code (SUCCESS) indicates success, and that other error codes (evaluating to true) are errors... but specific error codes could change over time, and they are even kernel-specific.
Fixes https://github.com/simdjson/simdjson/issues/1755

Fixing issue 1755

---

doc/basics.md

Link `runtime CPU detection` in `Including simdjson` was broken.

Fix broken link in basics documentation.

---

include/simdjson/arm64/bitmanipulation.h
include/simdjson/generic/numberparsing.h
include/simdjson/haswell/bitmanipulation.h
include/simdjson/portability.h
include/simdjson/ppc64/bitmanipulation.h
include/simdjson/westmere/bitmanipulation.h
src/implementation.cpp
tests/checkimplementation.cpp
tests/dom/basictests.cpp
tests/dom/readme_examples.cpp
tests/ondemand/test_ondemand.h
tools/json2json.cpp

This patch is aimed to solve [macro name collisions with third-party libraries](https://github.com/search?q=%22define+NO_SANITIZE_UNDEFINED%22&type=Code). 
Also i guess it makes macro names conforming to CONTRIBUTING.md which states that
>All C macros introduced in public headers need to be prefixed with either SIMDJSON_ or simdjson_.

Added SIMDJSON_ prefix to STRINGIFY and to NO_SANITIZE_UNDEFINED macros.

---

include/simdjson/generic/ondemand/serialization-inl.h
include/simdjson/generic/ondemand/serialization.h
tests/ondemand/ondemand_tostring_tests.cpp

We were missing ADL for some operator<< functions.
Fixes https://github.com/simdjson/simdjson/issues/1768
credit :  @madhur4127

Verify and fix 1768.

---

include/simdjson/generic/ondemand/value-inl.h

Small usability issue that prevents following code from compiling unless `get_number()` is called first on value type when getting a number:
```
simdjson::ondemand::number number;
doc.find_field("number").get(number);
doc["number"].get(number);
```
This would be on par with getting other types directly from value using get() via template argument deduction and it seems that only specialization for number type was missing. I am unsure whether this fix should require unit tests. However, I did manage to check that all tests are compiling and passing.

Missing value::get() template specialization for number

---

include/simdjson/ppc64/numberparsing.h

FreeBSD uses sys/endian.h and bswap64().

Fix build on FreeBSD/powerpc64*

---

doc/basics.md

Removes some superfluous words in the documentation that seem to be there by accident.

fix a typo in documentation

---

include/simdjson/icelake/simd.h
include/simdjson/implementations.h

update the implementation of simd8<bool> operator> and simd8<bool> operator<, to reduce the usage of avx512 intrinsics.

update the implementation of operator> and operator<

---

singleheader/amalgamate.py

Currently the Python script assumes that git is installed. It will crash if git is not found. It should not do so.

Making the python script more robust.

---

benchmark/amazon_cellphones/amazon_cellphones.h
benchmark/amazon_cellphones/simdjson_dom.h
benchmark/amazon_cellphones/simdjson_ondemand.h
benchmark/large_amazon_cellphones/large_amazon_cellphones.h
benchmark/large_amazon_cellphones/simdjson_dom.h
benchmark/large_amazon_cellphones/simdjson_ondemand.h

In the large case, we find that the threaded scenario with
ondemand has a 40% speed benefit over the unthreaded scenario.
```
2022-05-20T16:25:50+00:00
Running ./build/benchmark/bench_ondemand
Run on (4 X 1396.9 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 1024 KiB (x4)
L3 Unified 8448 KiB (x1)
Load Average: 0.72, 0.33, 0.13
simdjson::dom implementation:      haswell
simdjson::ondemand implementation (stage 1): haswell
simdjson::ondemand implementation (stage 2): fallback
-----------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                   Time             CPU   Iterations UserCounters... …
```

This runs the streaming amazon benchmarks in two modes: threaded and unthreaded

---

.github/workflows/ubuntu20-gcc8.yml

This is a follow-up on issue #1831  and the corresponding fix in #1832 to make sure simdjson can be built with GCC 8.
As far as I can see, there are already tests for GCC 7 and GCC 9, but GCC 8 was not covered - yet.

CI: run tests with GCC 8, too

---

benchmark/benchfeatures.cpp
benchmark/benchmarker.h
benchmark/event_counter.h
benchmark/json_benchmark/run_json_benchmark.h

Under ARM, it might be fruitful to only count cycles and instructions. Some ARM processors simply return 0s when you try to read more (e.g., graviton 3).

Simpler counters.

---

doc/implementation-selection.md

IceLake was not mentioned in the part of the documentation that mentions how to disable a certain implementation.
Furthermore, this fixes a whitespace error on line 20.

add SIMDJSON_IMPLEMENTATION_ICELAKE to implementation-selection.md

---

.vscode/settings.json
benchmark/bench_ondemand.cpp
benchmark/distinct_user_id/rapidjson.h
benchmark/distinct_user_id/sajson.h
benchmark/find_tweet/rapidjson.h
benchmark/find_tweet/sajson.h
benchmark/json2msgpack/json2msgpack.h
benchmark/json2msgpack/nlohmann_json.h
benchmark/json2msgpack/rapidjson.h
benchmark/json2msgpack/sajson.h
benchmark/json2msgpack/simdjson_ondemand.h
benchmark/json2msgpack/yyjson.h
benchmark/kostya/nlohmann_json_sax.h
benchmark/kostya/rapidjson.h
benchmark/kostya/sajson.h
benchmark/large_random/nlohmann_json_sax.h
benchmark/large_random/rapidjson.h
benchmark/large_random/sajson.h
benchmark/partial_tweets/rapidjson.h
benchmark/partial_tweets/sajson.h
benchmark/top_tweet/nlohmann_json_sax.h
benchmark/top_tweet/rapidjson.h
benchmark/top_tweet/sajson.h

Should be self-explanatory: adding benchmarks where we transcode from json to msgpack.
```
$ cmake --build build --target bench_ondemand && ./build/benchmark/bench_ondemand --benchmark_filter="json2msgpack"
[  0%] Built target generated-data
Consolidate compiler generated dependencies of target simdjson
[  0%] Building CXX object CMakeFiles/simdjson.dir/src/simdjson.cpp.o
[ 10%] Linking CXX static library libsimdjson.a
[ 10%] Built target simdjson
Consolidate compiler generated dependencies of target yyjson
[ 20%] Built target yyjson
Consolidate compiler generated dependencies of target benchmark
[ 90%] Built target benchmark
Consolidate compiler generated dependencies of target bench_ondemand
[100%] Building CXX object benchmark/CMakeFiles/bench_ondemand.dir/bench_ondemand.cpp.o
[100%] …
```

adding msgpack benchmarks

---

dependencies/CMakeLists.txt

As far as I understand, it is only used in benchmarks. Nevertheless we should use the current version of nlohmann/json to get a more accurate comparison.

update dependency nlohmann/json for benchmarks to current version 3.10.5

---

doc/basics.md
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_object_tests.cpp

In on-demand, you should visit each field only once, which means that once you have access to the value of a key, you need to consume the content. You cannot just 'save it' and parse it later, you must eagerly parse it even if you may need to throw away the result later.
Fixes https://github.com/simdjson/simdjson/issues/1864

Documenting a specific use case where you need a value if and only if it is another key is not present

---

include/simdjson/arm64/stringparsing.h
include/simdjson/fallback/stringparsing.h
include/simdjson/haswell/stringparsing.h
include/simdjson/icelake/stringparsing.h
include/simdjson/ppc64/stringparsing.h
include/simdjson/westmere/stringparsing.h
src/generic/stage2/stringparsing.h
tests/ondemand/ondemand_misc_tests.cpp

@MashPlant has identified a very interesting bug where it is possible, in the simdjson, to get back UTF-8 invalid strings, if you use the right escape sequences.
This PR also deletes an empty file that is no longer needed.
Fixes https://github.com/simdjson/simdjson/issues/1870

Fixing issue 1870

---

src/generic/stage2/stringparsing.h

I guess it will be thrown away by the compiler's optimizer anyway, but there is no need to keep this in the code.
For reference: Those lines were added in #1871.

remove empty if block

---

benchmark/bench_ondemand.cpp
benchmark/distinct_user_id/rapidjson.h
benchmark/distinct_user_id/yyjson.h
benchmark/find_tweet/rapidjson.h
benchmark/find_tweet/yyjson.h
benchmark/json2msgpack/rapidjson.h
benchmark/json2msgpack/yyjson.h
benchmark/kostya/rapidjson.h
benchmark/kostya/yyjson.h
benchmark/large_random/rapidjson.h
benchmark/large_random/yyjson.h
benchmark/partial_tweets/rapidjson.h
benchmark/partial_tweets/yyjson.h
benchmark/top_tweet/rapidjson.h
benchmark/top_tweet/yyjson.h
dependencies/CMakeLists.txt

This sets yyjson and rapidjson their latest releases and it disables by default several competitors.

cleaning on-demand benchmarks

---

doc/basics.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_array_tests.cpp
tests/ondemand/ondemand_object_tests.cpp

Calling `count_fields` on an empty document, and then instantiating an object over the document might currently be unsafe. Instantiating an object and then calling `count_fields`  on it is safe, which is the recommended usage.
Users are commended to use `count_fields`  sparingly.
Fixes https://github.com/simdjson/simdjson/issues/1876

Verifying and fixing issue 1876

---

include/simdjson/error.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/value_iterator-inl.h
src/internal/error_tables.cpp
tests/ondemand/ondemand_number_tests.cpp

Scalar JSON documents are peculiar because you only access one token (typically). This opens up  the possibility that there might be 'trailing content' that is never verified.
When accessing a scalar root element, this PR will add a check to ensure that there is only one token in the document. If so, we fail even if the current scalar element is fine (e.g., `1232 aaa`).
Fixes https://github.com/simdjson/simdjson/issues/1878

Fixes and verifies issue 1878.

---

.github/workflows/debian.yaml
CMakeLists.txt
cmake/JoinPaths.cmake
simdjson.pc.in

Fixes #1763
I chose the "dynamic" route :)
It is a bit more complex than a more static solution, but it has the advantage of requiring just two lines of code (module inclusion and function call) in "user" code and should also work in every project. Of course this is not perfect (for example, it doesn't currently handle cases like generating a .pc file of a library that links to an imported target that has no imported location but only a list of more than one interface libraries), but works in most cases. Definitely works in a project like simdjson that doesn't have external dependencies ;)
Edit: oh right, tests... To test this you would need to test the library as installed - compiling the library, installing it, and compiling a sample program that links to this using pkg-config. I don't …

build: add pkg-config support

---

include/simdjson/generic/numberparsing.h
include/simdjson/generic/ondemand/logger-inl.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/internal/isadetection.h
src/generic/stage1/utf8_lookup4_algorithm.h

A rather small change to fix a few small warnings that could potentially trigger bugs/UB. I've added explicit casts for bool -> int and fixed 3 small issues. I've also tried introducing `if constexpr` in 3 places but used a preprocessor directive based on `__cplusplus` and `_MSVC_LANG` to only use it if the library is being compiled with C++17 or newer. Though I don't think it's properly placed... should I instead put the `IF_CONSTEXPR` definition into some general header?

Fix various warnings

---

src/generic/stage2/stringparsing.h
tests/ondemand/ondemand_misc_tests.cpp

Closes #1894
Reject low surrogates outside of the range U+DC00—U+DFFF
Related to https://unicodebook.readthedocs.io/unicode_encodings.html#utf-16-surrogate-pairs
A surrogate pair should consist of a high surrogate and low surrogate. They're used to represent 0x010000-0x10FFFF in the JSON spec because the JavaScript specification originally only supported `\uXXXX`.
Previously, simdjson would accept some combinations of valid high surrogates and invalid low surrogates due to a bug in the check. (e.g. `\uD888\u1234` was accepted)
U+D800—U+DBFF (1,024 code points): high surrogates
U+DC00—U+DFFF (1,024 code points): low surrogates

fix: Reject surrogate pairs with invalid low surrogate

---

benchmark/bench_dom_api.cpp
src/generic/stage2/stringparsing.h

Load 2 bytes at a time and compare 2 bytes at a time against `"\u"`.
Compilers with optimizations turned on will turn this into a 16-bit load then 16-bit compare on supported platforms
(with smaller compiled code size).
Make it obvious to the compiler that it's reading two consecutive bytes of the same pointer
Add parse_surrogate_pairs to show the difference exists. See discussion in #1896

Micro-optimization for parsing surrogate pairs

---

HACKING.md

vim syntax highlighting doesn't work properly without space between a bulleted list and the start of a code snippet.

[skip ci] Fix typo, formatting nit in HACKING.md

---

.editorconfig
.gitattributes

Make it less likely to accidentally introduce tabs, trailing whitespace, carriage returns, non-utf8 in files, or files without trailing newlines.
https://editorconfig.org/ has plugins for various editors/IDEs and is enabled by default in some IDEs.
For now, introduce it only for the most commonly modified filetypes - I'm not familiar with the style guidelines/preferences for other files, and more extensions would increase the time to review this

[skip ci] Add an .editorconfig for .cpp/.h/.md for whitespace settings

---

include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/parser.h

The On Demand API is "lazy" so that the user is in (full) control. Hence, the user has access to the current depth of the parsing (through the document instance) at all times. If a user wants to limit the depth, they can do so on their own. However, when the development checks are enabled, we write a buffer some positions to help debugging, and this requires a memory allocation, hence the need for a maximal depth.
This PR guards the accesses to this buffer so that it is safer and it also documents the max_depth value.
Fixes https://github.com/simdjson/simdjson/issues/1903

Minor fix (documentation and safety) regarding max. depth in ondemand.

---

doc/basics.md
tools/json2json.cpp

Fixes https://github.com/simdjson/simdjson/issues/1904

Documenting how one can check for the end of the document.

---

benchmark/json2msgpack/simdjson_ondemand.h

The GCC compiler does well with by-value passing in recursive calls, but other compilers are not as great.
It seems that GCC has superior recursive inlining:
* https://stackoverflow.com/questions/29186186/why-does-gcc-generate-a-faster-program-than-clang-in-this-recursive-fibonacci-co
* https://godbolt.org/z/TeK4doE51
Fixes https://github.com/simdjson/simdjson/issues/1910

We branch on GCC for performance.

---

doc/basics.md
doc/dom.md
include/simdjson/common_defs.h
include/simdjson/dom/array-inl.h
include/simdjson/dom/element-inl.h
include/simdjson/dom/object-inl.h
include/simdjson/internal/tape_ref-inl.h
include/simdjson/internal/tape_ref.h
singleheader/simdjson.cpp
singleheader/simdjson.h

In debug mode, this adds some checks to help DOM users who rely on unsafe patterns.
Fixes https://github.com/simdjson/simdjson/issues/1914

Adding more development checks to the DOM front-end

---

include/simdjson/dom/parser-inl.h
include/simdjson/dom/parser.h

Unsure why the `dom::parser::parse` function did not have a overload with `padded_string_view` yet. Noticed this because clang gave me a warning about the `padded_string_view` being downcasted to a `std::string_view` because `padded_string` has a constructor overload for `std::string_view` from which `padded_string_view` inherits, which would be valid but would discard data because `sizeof(padded_string_view) == sizeof(std::string_view) + 8`. Now I wonder if the overload for `padded_string` could be removed because it already has a conversion operator to a view, so that constructor might be redundant.

Fix: Add padded_string_view overload for parser::parse

---

src/to_chars.cpp

Note that JavaScript does not have a trailing zero...
```JavaScript
> t={"a":0.0}
> JSON.stringify(t)
'{"a":0}'
```
See https://github.com/TkTech/pysimdjson/pull/102#issuecomment-1323400524

Serialize 0 as 0.0

---

.github/workflows/fuzzers.yml

In CI, the fuzzer is currently failing because it cannot install LLVM 11. Upgrading.

Trying fuzzer with llvm 14.

---

.github/workflows/fuzzers.yml

Currently, the fuzzer in CI no longer builds. We need to update it to LLVM 15. New packages are seemingly needed.

The fuzzer needs to be updated.

---

LICENSE
doc/basics.md
doc/implementation-selection.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
include/simdjson/simdjson_version.h
tests/checkimplementation.cpp
tests/dom/readme_examples.cpp
tests/ondemand/ondemand_document_stream_tests.cpp
tests/ondemand/ondemand_number_in_string_tests.cpp
tests/ondemand/ondemand_scalar_tests.cpp
tools/json2json.cpp

This PR improves several things...
Note: few people use single-value JSON documents so two of these issues are edge cases.

complete number_in_string for documents, stringify the version macro and improving trailing content errors

---

include/simdjson/icelake/simd.h

We test under GCC9 (Ubuntu) but RedHat GCC9 is apparently different (maybe a different standard library).
Fixes https://github.com/simdjson/simdjson/issues/1950

Fix for issue 1950

---

CMakeLists.txt
doc/basics.md
include/simdjson/generic/dom_parser_implementation.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/field-inl.h
include/simdjson/generic/ondemand/field.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
include/simdjson/generic/ondemand/raw_json_string-inl.h
include/simdjson/generic/ondemand/raw_json_string.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
include/simdjson/internal/dom_parser_implementation.h
src/arm64/dom_parser_implementation.cpp
src/fallback/dom_parser_implementation.cpp
src/generic/stage2/stringparsing.h
src/generic/stage2/tape_builder.h
src/haswell/dom_parser_implementation.cpp
src/icelake/dom_parser_implementation.cpp
src/ppc64/dom_parser_implementation.cpp
src/westmere/dom_parser_implementation.cpp
tests/ondemand/ondemand_misc_tests.cpp

Some users receive strings that cannot be decoded into valid UTF-8 due to a bad sequence of escaped code points. A reasonable solution is to fallback on [WTF-8](https://simonsapin.github.io/wtf-8/). This is allowed by RFC...
> When all the strings represented in a JSON text are composed entirely of Unicode characters [[UNICODE]](https://xml2rfc.tools.ietf.org/cgi-bin/cat.cgi/rfc8259.html?input=a76e3edb9610a98045f4a1729262df1867b28097abc973cd69fdc1-1513534632#UNICODE) (however escaped), then that JSON text is interoperable in the sense that all software implementations that parse it will agree on the contents of names and of string values in objects and arrays. However, the ABNF in this specification allows member names and string values to contain bit sequences that cannot encode Unicode …

Adding support for wobbly strings to On Demand and lossy trancoding from escaped (with replacement)

---

CMakeLists.txt

This fixes a bug that caused simdjsonTargets.cmake not to be included in CPack-generated packages, which—unlike `cmake --install`—does not pick up this mislabeled install component.
I git-grepped through the code base, after this change all components are either `simdjson_Development` or `simdjson_Runtime`.

Fix export component for simdjsonTargets.cmake

---

CMakeLists.txt
tests/dom/document_stream_tests.cpp
tests/dom/errortests.cpp
tests/dom/integer_tests.cpp
tests/ondemand/ondemand_document_stream_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

Credit to @spnda for this better approach. It should cover ClangCL which is nice.

Better way to put -Og in debug mode

---

include/simdjson/dom/parser-inl.h

We were noticing memory allocation issues with the `dom::` parser, and it led to this line, where potentially a different comparison operator should have been used.
If it is indeed the case, the `if`-`else` statement can be replaced with a simpler one-liner.
```cpp
max_capacity_ = std::max(MINIMAL_DOCUMENT_CAPACITY, max_capacity)
```

Fix: Defining maximal DOM parser capacity

---

doc/basics.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
include/simdjson/padded_string-inl.h
tests/ondemand/ondemand_error_location_tests.cpp
tests/ondemand/ondemand_object_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

This adds extra checks when `get_value()` is called on a document.
We also document that we consider a number or a scalar value that appears at the end of the document an error in a non-scalar JSON document.
Fixes https://github.com/simdjson/simdjson/issues/1974

Avoiding the issue where doc.get_value().get_object() differs from doc.get_object() in how errors are reported.

---

.vscode/settings.json
tests/dom/basictests.cpp
tests/ondemand/ondemand_object_tests.cpp

To verify https://github.com/simdjson/simdjson/issues/1979

Trying to verify issue 1979

---

README.md

As requested, here is a pull request with the link to the Perl module.
Closes #1990.

Add link to Perl binding (JSON::SIMD)

---

doc/implementation-selection.md
doc/ondemand_design.md

Since the creation of the IceLake implementation there are now four available implementations on Intel/AMD x64 processors. However, it was omitted in some parts of the documentation.

Mention IceLake in documentation about implementation selection.

---

include/simdjson/portability.h
tests/dom/stringparsingcheck.cpp

We should only use runtime asserts in simdjson when the software is built in debug mode.

Some systems release without NDEBUG set, let us not assert in these cases.

---

tests/dom/basictests.cpp
tests/ondemand/ondemand_number_tests.cpp

See https://github.com/simdjson/simdjson/issues/2017

Adding tests for issue 2017

---

include/simdjson/generic/ondemand/value_iterator-inl.h
tests/ondemand/ondemand_error_tests.cpp

But reset_array and reset_object were missing a check which could lead to really bad outcomes when processing bad JSON.

fix: bug identified by Yagiz Nizipli

---

doc/iterate_many.md
include/simdjson/generic/ondemand/document_stream-inl.h
include/simdjson/generic/ondemand/document_stream.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
tests/ondemand/CMakeLists.txt
tests/ondemand/ondemand_iterate_many_csv.cpp

`iterate_many` can now parse comma separated documents.
However, this mode will not support batched processing in chunks. This is because it is difficult to find the border between 2 documents efficiently when comma is used as the delimiter. Hence, the batch size is increased to be as large as the json passed in.
It is the user's responsibility to create a parser that has capacity large enough to handle the minimum batch size, failing which will return a capacity error. Because `allow_comma_separated` is a parameter after `batch_size` and defaulted to false, users enabling comma separated parsing will have to explicitly set the batch size and thus would be conscious to check that their parser's capacity is large enough to handle the batch size.
This closes #1999

Add comma separated value parsing as an option in iterate_many

---

.github/workflows/fuzzers.yml
.github/workflows/power-fuzz.yml
.github/workflows/ubuntu22-cxx20.yml
.github/workflows/vs17-ci-cxx20.yml

The updated actions are [actions/cache](https://github.com/actions/cache), [actions/checkout](https://github.com/actions/checkout) and [actions/upload-artifact](https://github.com/actions/upload-artifact).
Changes in [actions/cache](https://github.com/actions/cache):
> ### 3.0.0
> - Updated minimum runner version support from node 12 -> node 16
> 
> ### 3.0.1
> - Added support for caching from GHES 3.5.
> - Fixed download issue for files > 2GB during restore.
> 
> ### 3.0.2
> - Added support for dynamic cache size cap on GHES.
> 
> ### 3.0.3
> - Fixed avoiding empty cache save when no files are available for caching. ([issue](https://github.com/actions/cache/issues/624))
> 
> ### 3.0.4
> - Fixed tar creation error while trying to create tar with path as `~/` home folder on …

update various actions in GitHub Actions to v3

---

.clangd
HACKING.md
include/simdjson/arm64/numberparsing.h
include/simdjson/fallback/numberparsing.h
include/simdjson/generic/numberparsing.h
include/simdjson/generic/ondemand.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/json_type-inl.h
include/simdjson/generic/ondemand/json_type.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/haswell/numberparsing.h
include/simdjson/icelake/numberparsing.h
include/simdjson/ppc64/numberparsing.h
include/simdjson/westmere/numberparsing.h

Since number parsing is outside of ondemand at generic/numberparsing.h (which is arguably correct), we should keep its stuff out of the ondemand namespace. We do have documentation (and possible code out in the wild) that relies on `number_type` being in ondemand, so we use a `using` statement to alias that type into ondemand.
Noticed this when I tried to make a copy of ondemand for an experiment and couldn't access number functions anymore :)

Move numberparsing functions to architecture top level

---

include/simdjson/common_defs.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/logger-inl.h
include/simdjson/generic/ondemand/logger.h
include/simdjson/generic/ondemand/object-inl.h
include/simdjson/generic/ondemand/token_iterator.h

This fixes #2004 and #2021 
Unfortunately, I still have to allocate memory to do the string formatting, because the message is logged this way, where the message length is capped.
```c++
printf("| %*s%s%-*s ",
indent, "",
title_prefix,
LOG_EVENT_LEN - indent - int(strlen(title_prefix)), msg.c_str());
```
However, the memory allocation is now deferred till the end when a log line really happens.
The `log_level` enum class is also changed to have values `info` and `error`

Add info and error logging, defer log message evaluation

---

doc/dom.md
include/simdjson/dom/serialization-inl.h
include/simdjson/dom/serialization.h
tests/CMakeLists.txt
tests/prettify_tests.cpp

Add pretty print for DOM with documentation.
Currently, the indentation is fixed to four spaces.
Close #1329.

Add pretty print for DOM

---

.github/workflows/ubuntu20.yml
.github/workflows/ubuntu22.yml

User @bgemmill reports that when compiling with SIMDJSON_DEVELOPER_MODE=OFF, the build fails due to missing internal definitions. I am adding build/install/build command tests to our Ubuntu CI tests. It is a cheap test that we can run quickly.
See https://github.com/simdjson/simdjson/issues/2037

Adding tests for issue 2037.

---

.github/workflows/ubuntu22-clang13.yml
.github/workflows/ubuntu22-clang14.yml

These lines should not be necessary: clang-14 and clang-13 are documented as being available by default with ubuntu-22 under GitHub Actions.

Simplifying CI

---

.github/workflows/ubuntu22-threadsani.yml

It no longer seems possible to run the thread sanitizer without installing further dependencies under ubuntu 20 on GitHub actions. Upgrading to ubuntu 22 should fix the issue.

Fixing failing thread sanitizer

---

include/simdjson/icelake/stringparsing_defs.h

When processing strings, the haswell and icelake kernels call the `simd8<uint8_t>` each time a string is accessed.
```
simd8<uint8_t> v(src);
```
For haswell, `simd8<uint8_t>` is a wrapper around `__m256i` (32 bytes), for icelake, it is a wrapper around `__m512i` (64 bytes). Yet we consider currently that both of them read 32 bytes. This potentially means that the icelake kernel will advance by only 32 bytes even though it reads 64 bytes. It should still provide the correct answers, but it will be wasteful.
For westmere, we call two constructors, consuming 16 bytes each...
```
simd8<uint8_t> v0(src);
simd8<uint8_t> v1(src + 16);
```
For neon, it is much the same:
```
simd8<uint8_t> v0(src);
simd8<uint8_t> v1(src + sizeof(v0));
```
Credit @jkeiser

Icelake processes 64 bytes at a time when processing strings.

---

.github/ISSUE_TEMPLATE/feature_request.md

Our tests check whether you have introduced trailing white space. If such a test fails, please check the "artifacts button" above, which if you click it gives a link to a downloadable file to help you identify the issue. You can also run scripts/remove_trailing_whitespace.sh locally if you have a bash shell and the sed command available on your system.
If you plan to contribute to simdjson, please read our
CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

Fix issue template bold text

---

CMakeLists.txt
cmake/simdjson-config.cmake.in

- Fix #2066
- Chose variable name `SIMDJSON_BUILD_STATIC_LIB` as `SIMDJSON_BUILD_STATIC` is mkared as deprecated
- Please confirm that `simdjson_xxx_props` are used properly
- ~~Still WIP, as~~ I am at the same time trying this branch on Conda-Forge https://github.com/conda-forge/simdjson-feedstock/pull/56
Note: if any maintainer of this project would like to become a co-maintainer of the Conda-Forge package, you are most welcome.

Add simdjson_static lib

---

src/generic/stage2/json_iterator.h

Originally, simdjson relied on computed gotos but given that it is not a standard C/C++ feature, it made the code ugly as you needed fallback code.
Cleverly @jkeiser showed that you could get much of the same performance using switch/cases. Unfortunately, switch/cases are a high level abstraction: it can be compiled in different manners. We would want them compiled as computed gotos, but that's not when GCC and LLVM do.
We can try to bypass them if we think we can do better. In particular, the compiler has no idea that most JSON is made of strings and numbers. We can try to tell it. The gains might be modest, but widespread.
The current PR will only affect the DOM performance.
We can use an array of strings as a test case:
```Python
print("[")
for i in range(1000000): …
```

Redesigning visit_primitive so that it is optimized for strings and numbers (DOM backend)

---

include/simdjson/dom/element-inl.h
include/simdjson/dom/element.h
tests/dom/document_tests.cpp

Add a total order for `element`s (ie `operator<` and `operator==`) based on the tape position of each element.
This allows to keep `element`s in an C++ ordered STL container.
Why would I use such an expensive operation - which includes allocation - such as adding `element`s to a `map`?
I am using `simdjson`s internal `dom` to keep a parsed copy of a JSON file in memory to be accessed on-demand by a Node.js program. This addition allows me to keep references to the JavaScript proxy objects that I am returning. Ie, if the user code calls:
```
document.path('/some/path')
```
I can return the previously created object in an environment where creating objects can be expensive.

add a total order for elements

---

include/simdjson/dom/element.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value.h

The get template seems to still cause confusion. In retrospect, it is probably a design mistake to include an open-ended template in a public API. People repeatedly do the following:
```C++
myclass class;
my_simdjson.get(class); // fails!!!
```
In C++20 and better, we can use concepts which can bring some sanity back.

This provides verbose static_assert messages

---

doc/basics.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
singleheader/simdjson.cpp
singleheader/simdjson.h
tests/ondemand/CMakeLists.txt
tests/ondemand/ondemand_readme_examples.cpp
tests/ondemand/ondemand_to_string.cpp

It is mostly syntactic sugar.
```C++
std::string name;  
auto err = doc["name"].get_string(name);  
if(err) { /* handle error */ }
```

Adding the ability to write directly to an std::string. 

---

doc/basics.md
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
tests/ondemand/ondemand_parse_api_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

We want the following to just work...
```C++
std::string json = "12345642314123421321321321321321312321321321321312";
json.shrink_to_fit();      
parser.iterate(json);
```

Automating string reallocation when it is possible

---

doc/basics.md
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_readme_examples.cpp

This PR allows you to call `raw_json()` on values, without having to first check if you have an array or an object.
It is syntactic sugar.

raw_json() on values

---

doc/basics.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
include/simdjson/generic/ondemand/value_iterator-inl.h
include/simdjson/generic/ondemand/value_iterator.h
tests/ondemand/ondemand_readme_examples.cpp

```C++
auto json = R"({ "foo1": "3.1416" } )"_padded;
ondemand::parser parser;
ondemand::document doc = parser.iterate(json);
std::optional<std::string> value;
if(doc["foo1"].get_string(value)) { /* error */ }
```

Allowing users to write directly to std::optional<std::string>

---

include/simdjson/dom/document_stream.h
include/simdjson/dom/parser-inl.h
include/simdjson/dom/parser.h
include/simdjson/generic/ondemand/document_stream.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
include/simdjson/padded_string_view-inl.h
include/simdjson/padded_string_view.h
tests/dom/basictests.cpp
tests/dom/document_stream_tests.cpp
tests/ondemand/ondemand_document_stream_tests.cpp
tests/ondemand/ondemand_misc_tests.cpp

Currently, if you want to parse a string that might have a BOM, you have to do something like this...
```C++
std::string input;   
load(input);
input.reserve(input.size() + simdjson::SIMDJSON_PADDING);   
std::string_view json_string(input);   
if (input.size() >= 3 && 0 == memcmp(input.data(), "\xEF\xBB\xBF", 3)) {    
json_string.remove_prefix(3);  // Skip UTF-8 BOM.   
}   
parser.iterate(json_string, json_string.max_size());
```
This PR would simplify the code to...
```C++
std::string input;   
load(input);
parser.iterate(input);
```

skip UTF-8 BOM if present

---

include/simdjson/arm64/simd.h

This PR replaces a function-based workaround for Visual Studio ARM constant initialization with a macro-based approach. The macro approach might lead to more efficient code for ARM-based Visual Studio builds. Other systems are unaffected.

Macro-based workaround for Visual Studio ARM

---

doc/basics.md
singleheader/simdjson.cpp
singleheader/simdjson.h
src/generic/stage2/stringparsing.h

Essentially, we are removing code that should not be there. This should help make https://github.com/nodejs/node/pull/50930 unnecessary.

Fixing warnings issued by clang (Node issue 50930)

---

.github/workflows/alpine.yml
.github/workflows/debian.yaml
.github/workflows/documentation.yml
.github/workflows/fix-trailing-whitespace.yml
.github/workflows/fuzzers.yml
.github/workflows/macos.yml
.github/workflows/msys2-clang.yml
.github/workflows/msys2.yml
.github/workflows/power-fuzz.yml
.github/workflows/ppc64.yml
.github/workflows/riscv64.yml
.github/workflows/s390x.yml
.github/workflows/ubuntu20-checkperf.yml
.github/workflows/ubuntu20-gcc8.yml
.github/workflows/ubuntu20-noexcept.yml
.github/workflows/ubuntu20-nothread.yml
.github/workflows/ubuntu20-sani.yml
.github/workflows/ubuntu20.yml
.github/workflows/ubuntu22-clang13.yml
.github/workflows/ubuntu22-clang14.yml
.github/workflows/ubuntu22-cxx20.yml
.github/workflows/ubuntu22-gcc12.yml
.github/workflows/ubuntu22-glibcxxassertions.yml
.github/workflows/ubuntu22-threadsani.yml
.github/workflows/ubuntu22.yml
.github/workflows/vs17-arm-ci.yml
.github/workflows/vs17-ci-cxx20.yml
.github/workflows/vs17-ci.yml
.github/workflows/vs17-clang-ci.yml
.github/workflows/vs17-noexcept-ci.yml

This updates [actions/checkout](https://github.com/actions/checkout) to v4, it's current version.
Changelog:
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20
As far as I can tell this should be backwards compatible, so I do not expect any breakage.

update actions/checkout in GitHub Actions to v4

---

include/simdjson/dom/parser-inl.h
include/simdjson/dom/parser.h
tests/dom/basictests.cpp

I've found `parse_into_document` quite useful, but there was previously no `load` counterpart to `parse_into_document`. It seemed simple enough to add so this PR does exactly that.

Add `load_into_document` to `simdjson::dom::parser`

---

src/arm64.cpp
src/generic/dom_parser_implementation.h
src/generic/stage1/utf8_lookup4_algorithm.h
src/haswell.cpp
src/icelake.cpp
src/ppc64.cpp
src/westmere.cpp

Hello, I just thought of this optimization while refactoring the code in simdjzon.
For Zig, which uses LLVM, this optimization does not occur automatically. For that, I have [submitted an issue to LLVM](https://github.com/llvm/llvm-project/issues/79690).
However, this project compiles with multiple compilers which may or may not do this optimization automatically, so I have edited your code to reflect the optimization idea. It is very basic, and I did not test the modified C++ code. But it looks right to me. (I did test my Zig implementation)
Hope it works for you.
‒ Validark
P.S. I assumed `simd8<uint8_t> must23_80 = must23 & uint8_t(0x80);` splats the `0x80`. Is that correct?

[utf8-validator] eliminate unnecessary comparison from must_be_2_3_continuation

---

include/simdjson/dom/array.h
include/simdjson/dom/object.h
include/simdjson/generic/ondemand/document_stream.h
tests/dom/basictests.cpp
tests/ondemand/ondemand_document_stream_tests.cpp

Some iterators are implemented to be like `std::iterator` but don't actually allow themselves to be used where `std::iterator` can usually be used, because of some missing trait information. This PR adds that information.
I've not touched `simdjson::ondemand::{array,object}_iterator` as I don't think these can be valid standard iterators given the `MUST ONLY BE CALLED ONCE PER ITERATION` comment for `operator*`.

Allow some iterators to be used in standard C++ iterator functions

---

HACKING.md
doc/implementation-selection.md
src/implementation.cpp

This updates the documentation to indicate that the fallback implementation might be omitted (if it is not needed). A documentation issue reported by @TkTech 
We also skip runtime dispatching when a single implementation is available.
See https://github.com/simdjson/simdjson/issues/2117

Better documentation and support for the case where you have a single implementation.

---

include/simdjson/generic/ondemand/json_iterator-inl.h
tests/dom/basictests.cpp
tests/dom/document_stream_tests.cpp
tests/dom/document_tests.cpp
tests/dom/pointercheck.cpp
tests/ondemand/ondemand_document_stream_tests.cpp
tests/ondemand/ondemand_json_pointer_tests.cpp
tests/ondemand/ondemand_misc_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp
tests/ondemand/ondemand_scalar_tests.cpp

Instead of `std::string("my string")`, one can do `"my string"s`. Because it is C++14/C++17, we don't want to use it in the core library, but it can make for nicer code sometimes.
cc @FranciscoThiesen 
Related to https://github.com/simdjson/simdjson/pull/2127

adopting string literals

---

README.md
benchmark/json_benchmark/file_runner.h
benchmark/json_benchmark/string_runner.h
doc/basics.md
doc/dom.md
fuzz/fuzz_atpointer.cpp
include/simdjson/generic/ondemand/array.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/object.h
include/simdjson/generic/ondemand/value.h
include/simdjson/padded_string-inl.h
include/simdjson/padded_string.h
include/simdjson/padded_string_view-inl.h
include/simdjson/padded_string_view.h
tests/ondemand/ondemand_readme_examples.cpp

This is mostly documented with some additional examples/tests.

Documenting Unicode support in JSONPath and JSON Pointer

---

README.md

I believe simdjson-java is currently a fully-fledged port of simdjson (with all fundamental features implemented, and on-demand parsing coming soon), so we can add a link to it.

Add link to simdjson-java

---

include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
tests/ondemand/ondemand_error_tests.cpp

In some cases, clang might get confused when constructing an ondemand document in a constructor: instead of calling the move constructor, it somehow ends up trying to cast a document to a document. We can easily disallow this behavior with std::enable_if.

Unconfusing clang

---

include/simdjson/generic/ondemand/field-inl.h
include/simdjson/generic/ondemand/field.h
tests/ondemand/ondemand_key_string_tests.cpp

Close #2149.
In this PR, `escaped_key()` is added to `ondemand::field` to retrieve the unproccessed escaped key without the double quote.
Feel free to comment since I'm not sure if there's a better way to implement it.

Add `escaped_key` method to `ondemand::field`

---

include/simdjson/arm64/numberparsing_defs.h
include/simdjson/fallback/numberparsing_defs.h
include/simdjson/haswell/numberparsing_defs.h
include/simdjson/icelake/numberparsing_defs.h
include/simdjson/portability.h
include/simdjson/ppc64/numberparsing_defs.h
include/simdjson/westmere/numberparsing_defs.h
singleheader/simdjson.cpp
src/internal/isadetection.h

This PR solves compilation errors when building for the [Windows ARM64EC ABI](https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/).
You can repro in an [ARM64 Visual Studio Developer Command Prompt](https://devblogs.microsoft.com/cppblog/arm64ec-support-in-visual-studio/#developer-command-prompt):
```
>cl /nologo /c /EHsc /std:c++17 /arm64EC simdjson.cpp
simdjson.cpp : error C7303: AVX512 types (__m512) are not currently supported in ARM64EC code
simdjson.cpp : error C7302: AVX types (__m256) are not currently supported in ARM64EC code
simdjson.cpp : error C7303: AVX512 types (__m512) are not currently supported in ARM64EC code
simdjson.cpp : error C7302: AVX types (__m256) are not currently supported in …
```

add Windows ARM64EC support

---

.github/workflows/vs17-arm-ci.yml
include/simdjson/arm64/numberparsing_defs.h
include/simdjson/fallback/numberparsing_defs.h
include/simdjson/haswell/numberparsing_defs.h
include/simdjson/icelake/numberparsing_defs.h
include/simdjson/portability.h
include/simdjson/ppc64/numberparsing_defs.h
include/simdjson/westmere/numberparsing_defs.h
singleheader/simdjson.cpp
src/internal/isadetection.h

This is a re-land of #2165, with the issue of the incorrect inclusion of `<intrin.h>` on non-Windows platforms addressed.
I tested building this locally using the following combinations:
- Mac / `arm64`
- Mac / `x86_64`
- Linux / `x86_64`
- Windows / `X64`
- Windows / `ARM64`
- Windows / `ARM64EC`
I also tested running the tests on a Windows 11 ARM64 VM and they all passed.
This PR also adds an `ARM64EC` architecture CI build workflow to `windows-vs17`. See [here](https://github.com/jblazquez/simdjson/actions/runs/8609992925/job/23594796093?pr=1) for an example of a passing CI run. I had to switch the `vs17-arm-ci` builds to [target the Windows 11 SDK](https://stackoverflow.com/a/77651884) because ARM64EC is Windows 11 only.
It's not currently possible (as far as I know) to actually run …

add Windows ARM64EC build and CI support

---

doc/basics.md
include/simdjson/implementation.h
src/implementation.cpp

This PR will make our static objects ('implementations' used for runtime dispatching) trivially destructible. Many compilers appear to never call the destructor when the class is trivially destructible. (This makes sense since the destructor is guaranteed to have no effect.)
cc @jkeiser

makes implementations trivially destructible

---

include/simdjson/dom/element-inl.h
include/simdjson/error.h
include/simdjson/generic/ondemand/value-inl.h
tests/dom/pointercheck.cpp
tests/ondemand/ondemand_json_pointer_tests.cpp

Fixes #2154
***Note that this approach doesn't affect jsonpath (`at_path()`).**
One will still get `INVALID_JSON_POINTER` if the pointer path is syntactically ill-formed, otherwise the `NO_SUCH_FIELD` error is raised.

fix: issue #2154

---

src/implementation.cpp

Fixes the following:
```
src/implementation.cpp:193:20: error: no template named 'is_trivially_destructible' in namespace 'std'; did you mean 'is_trivially_move_constructible'?
static_assert(std::is_trivially_destructible<detect_best_supported_implementation_on_first_use>::value, "detect_best_supported_implementation_on_first_use should be trivially destructible");
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
is_trivially_move_constructible
```

Fix building simdjson against libc++ with _LIBCPP_REMOVE_TRANSITIVE_INCLUDES defined

---

include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/json_iterator.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
singleheader/simdjson.cpp

1. Allows processing inclomplete, damaged, corrupted json to some extent.
2. Pariity with the Presto Java functionality.
3. Protected with SIMDJSON_EXPERIMENTAL_ALLOW_INCOMPLETE_JSON define.
4. Does not interfere with the normal path (can co-exist).
5. Tested in production forkflow.
Resolves issue #2188

Adding path for parsing incomplete json.

---

include/simdjson/portability.h
singleheader/simdjson.cpp

Fix #2190 
I have decided to use `std::size_t` in `nonstd/string_view.hpp` as there were already parts where it was used

pull size_t from the std namespace

---

doc/basics.md
doc/performance.md
tests/ondemand/CMakeLists.txt
tests/ondemand/ondemand_cacheline.cpp

Padding does not usually require allocation.

doc: explaining the page trick

---

include/simdjson/nonstd/string_view.hpp

This is the header as seen for the tag [v1.8.0](https://github.com/martinmoene/string-view-lite/releases/tag/v1.8.0), commit a47222b9855dd6e6d1eac38acaa495822e2caa69, on <https://github.com/martinmoene/string-view-lite>.

update string_view lite to version 1.8.0

---

include/simdjson/padded_string-inl.h

issue https://github.com/simdjson/simdjson/issues/2203

reset moved object's viable_size to 0 in the move ctor of padded_string

---

doc/basics.md
tests/ondemand/ondemand_readme_examples.cpp

This adds an example where we capture string_views and print them out later (after the parsing is concluded).

adding another example

---

include/simdjson/dom/array-inl.h
include/simdjson/dom/array.h
include/simdjson/dom/object-inl.h
include/simdjson/dom/object.h
tests/dom/basictests.cpp

closed: #2218 
Added the functionality to convert dom::object and dom::array to dom element.
Add the function "inline operator element() const noexcept" to the dom::object and dom::array classes, and add test for it.

Added the functionality to convert dom::object and dom::array to dom element.

---

dependencies/CMakeLists.txt
include/simdjson/generic/ondemand/field-inl.h
include/simdjson/generic/ondemand/field.h
include/simdjson/generic/ondemand/json_iterator-inl.h
include/simdjson/generic/ondemand/parser-inl.h
include/simdjson/generic/ondemand/parser.h
tests/ondemand/ondemand_object_tests.cpp
tools/json2json.cpp
tools/jsonstats.cpp
tools/minify.cpp

This PR does the following:
1. Upgrade cxxopts.
2. Allows field::unescape_key to take in a string parameter (syntactic sugar).
3. Adds a dev. check to detect a string buffer overflow (indicating broken code). Note that this is unrecoverable and indicates bad code.

Allows field::unescape_key to take in a string parameter + additional dev. checks for string overflow

---

include/simdjson/generic/ondemand/value-inl.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/CMakeLists.txt
tests/ondemand/ondemand_custom_types_tests.cpp

Now you can use tag_invoke to add a custom type or a group of custom types.
A follow up on [Daniel Lemire's tweet](https://x.com/lemire/status/1815544018979504145), here's a proposal on how we would use [tag_invoke](https://wg21.link/P1895) in simdjson.
There might be some small details like which namespace to use for some utilities, coding style, and other things that I have left after knowing the project's authors opinions and whether or not they want to go in this direction or not.
This allows you to:
```c++
struct Car {
std::string make;
std::string model;
friend simdjson_result<Car>
tag_invoke(simdjson::deserialize_tag, std::type_identity<Car>, simdjson::ondemand::value &val) {
// ...
return car;
}
};
```
or completely going general, like:
```c++
namespace simdjson {
// this is to …
```

tag_invoke based custom types

---

include/simdjson/common_defs.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
tests/ondemand/compilation_failure_tests/CMakeLists.txt
tests/ondemand/compilation_failure_tests/iterate_array.cpp
tests/ondemand/compilation_failure_tests/iterate_object.cpp
tests/ondemand/ondemand_compilation_tests.cpp
tests/ondemand/ondemand_json_pointer_tests.cpp

The core idea is that you should never hold either an `ondemand::array` or `ondemand::object` without a corresponding `ondemand::document` being alive.
See issue https://github.com/simdjson/simdjson/issues/2227

fix: add tests related to issue 2227

---

doc/parse_many.md

The link in the readme of parse_many links to a casino spam site

Fix ndjson spec link

---

.github/workflows/ubuntu24-cxx20.yml
.vscode/settings.json
doc/basics.md
include/simdjson/concepts.h
include/simdjson/generic/ondemand/amalgamated.h
include/simdjson/generic/ondemand/deserialize.h
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/tag_invoke.h
include/simdjson/generic/ondemand/value.h
tests/ondemand/ondemand_custom_types_document_tests.cpp
tests/ondemand/ondemand_custom_types_tests.cpp
tests/ondemand/ondemand_readme_examples.cpp

This is basically a small extension to an earlier PR by @the-moisrex
It helps a bit with https://github.com/simdjson/simdjson/issues/2230
With this PR, you can do...
```cpp
simdjson::padded_string json =
R"( [ { "make": "Toyota", "model": "Camry",  "year": 2018,
"tire_pressure": [ 40.1, 39.9 ] },
{ "make": "Kia",    "model": "Soul",   "year": 2012,
"tire_pressure": [ 30.1, 31.0 ] },
{ "make": "Toyota", "model": "Tercel", "year": 1999,
"tire_pressure": [ 29.8, 30.0 ] }
])"_padded;
simdjson::ondemand::parser parser;
simdjson::ondemand::document doc = parser.iterate(json);
std::vector<Car> cars(doc);
```

Extending the deserialization code with more defaults + docs

---

CMakeLists.txt

Fixes issue #2239 whereby a cmake install of the static build, the headers are not included as a property in the simdjson_static target. As a result, when linking against the simdjson_static target in an executable, the compiler can not find the headers.

Add missing include directives to static build targets of simdjson.

---

singleheader/amalgamate.py

With gcc it causes an error in `simdjson.cpp`:
```
simdjson.cpp:548:9: warning: #pragma once in main file
548 | #pragma once
|         ^~~~
```
It had previously been commented out in: https://github.com/simdjson/simdjson/commit/6ef555e6fb79363fae057a9a46b52cd208d9e305
However, this was lost in an upgrade: https://github.com/simdjson/simdjson/commit/2a4ff7346813b120f2b5b40e95d69352b593cc9c

Ignore pragma once when amalgamating source files

---

include/simdjson/generic/ondemand/value_iterator-inl.h
tests/ondemand/ondemand_scalar_tests.cpp

The function documentation states: `INCORRECT_TYPE If the JSON value begins with 'n'and is not 'null'.`, however, it previously failed to return any error.
The behavior has now been corrected and the unit test updated.

Make document::is_null behavior consistent with documentation

---

include/simdjson/concepts.h
include/simdjson/generic/ondemand/std_deserialize.h
tests/ondemand/ondemand_custom_types_tests.cpp
tests/ondemand/ondemand_stl_types_tests.cpp
tests/test_macros.h

The is a build-up on top of @lemire's PR (#2267).
This now supports:
Here is the list of types used in the code:
- std::vector
- std::list
- std::set
- std::stack
- std::queue
- std::deque
- std::priority_queue
- std::unordered_set
- std::multiset
- std::unordered_multiset
- std::unique_ptr<double>
- std::shared_ptr<double>
- std::optional<double>

Cheap General Madness

---

doc/basics.md
doc/iterate_many.md
include/simdjson/generic/ondemand/document-inl.h
include/simdjson/generic/ondemand/document.h
tests/ondemand/ondemand_car_tag_invoke_deserialization.cpp

We can do...
```cpp
padded_string json =
R"( { "make": "Toyota", "model": "Camry",  "year": 2018,
"tire_pressure": [ 40.1, 39.9 ] }
{ "make": "Kia",    "model": "Soul",   "year": 2012,
"tire_pressure": [ 30.1, 31.0 ] }
{ "make": "Toyota", "model": "Tercel", "year": 1999,
"tire_pressure": [ 29.8, 30.0 ] }
)"_padded;
ondemand::parser parser;
ondemand::document_stream stream;
[[maybe_unused]] auto error = parser.iterate_many(json).get(stream);
std::vector<Car> cars;
for(auto doc : stream) {
cars.push_back((Car)doc); // an exception may be thrown
}
```

More documentation regarding builder

---

include/simdjson/dom/array-inl.h
include/simdjson/dom/array.h
include/simdjson/dom/element-inl.h
include/simdjson/dom/element.h
include/simdjson/dom/object-inl.h
include/simdjson/dom/object.h
include/simdjson/generic/ondemand/array-inl.h
include/simdjson/jsonpathutil.h
tests/dom/CMakeLists.txt
tests/dom/json_path_tests.cpp
tests/ondemand/ondemand_json_path_tests.cpp

- Updated `json_path_to_pointer_conversion` to support JSONPath starting with the '$' prefix, while maintaining compatibility with the existing implementation.
- Moved `json_path_to_pointer_conversion` to a separate header file for better modularity and to support JSONPath queries in `dom` mode.
- Implemented `at_path` functionality in `dom` mode to enable querying JSON using JSONPath.
- Added unit tests to validate the new JSONPath support in `dom` mode and ensure compatibility with both standard and existing JSONPath formats.

Add support for JSONPath with '$' prefix and integrate into dom::at_path

---

doc/basics.md
doc/dom.md
include/simdjson/dom/parser.h
include/simdjson/generic/ondemand/parser.h
include/simdjson/padded_string_view-inl.h
include/simdjson/padded_string_view.h
tests/dom/readme_examples.cpp
tests/ondemand/ondemand_readme_examples.cpp

For convenience, we allow people to pass an `std::string` instance to our parsing functions. When needed, these function increase the capacity of the string to provide padding. Sadly, some recently introduced sanity checkers spot the fact that we access data beyond the string and they flag it as an error. It is a false positive, but it leaves our users with a warning to ignore.
To make life easier, this PR introduce a 'pad' function which grows the string and returns a `padding_string_view`.

adding pad function

---

include/simdjson/dom/element.h
include/simdjson/dom/object.h
include/simdjson/generic/ondemand/document.h
include/simdjson/generic/ondemand/value.h

prevent int to pointer implicit conversion for operator[](const char *)

---

tests/builder/builder_string_builder_tests.cpp

Fixing a typo in the append_float

Fixing appeand_float typo

---

include/simdjson/arm64/bitmanipulation.h
include/simdjson/arm64/simd.h
singleheader/simdjson.cpp

Our tests check whether you have introduced trailing white space. If such a test fails, please check the "artifacts button" above, which if you click it gives a link to a downloadable file to help you identify the issue. You can also run scripts/remove_trailing_whitespace.sh locally if you have a bash shell and the sed command available on your system.
If you plan to contribute to simdjson, please read our
CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

fix: processor checks inconsistently problem

---

include/simdjson/padded_string-inl.h
include/simdjson/padded_string.h

Otherwise simdjson doesn't build with V8's Node.js fork, which uses -Werror,-Wdeprecated-literal-operator and latest version of clang.

fix: fix deprecation from -Wdeprecated-literal-operator

---

include/simdjson/error.h

Our tests check whether you have introduced trailing white space. If such a test fails, please check the "artifacts button" above, which if you click it gives a link to a downloadable file to help you identify the issue. You can also run scripts/remove_trailing_whitespace.sh locally if you have a bash shell and the sed command available on your system.
If you plan to contribute to simdjson, please read our
CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

Fix missing override

---

src/arm64.cpp
src/fallback.cpp
src/haswell.cpp
src/icelake.cpp
src/lasx.cpp
src/lsx.cpp
src/ppc64.cpp
src/westmere.cpp

Memory sanitizers can trigger incorrect warnings. We'd prefer if they did not do that.
Relates to https://github.com/simdjson/simdjson/issues/2309

Disabling memory sanitizer with parse_string

---

.github/workflows/fuzzers.yml
.github/workflows/msys2-clang.yml

apt.llvm.org does not provide clang 15 anymore. switched to the latest released version 19 instead.
also, fixed a syntax error in an unrelated action.

use clang 19 in fuzzer job

---

include/simdjson/compiler_check.h

See https://github.com/nodejs/node/pull/56250

let us be more careful with concepts, we require __cpp_concepts >= 201907L and check for old versions of Apple clang

---

fuzz/fuzz_implementations.cpp

fuzzing locally on an icelake system does not work, seems like fallback+haswell+icelake+westmere is one too much to fit in the max capacity of 3.

fix fuzzing when running on icelake

---

LICENSE
LICENSE-MIT
README.md

This adds MIT licensing to help the RonDB to include simdjson in their project.
Fixes https://github.com/simdjson/simdjson/issues/2326

Introducing dual licensing

---

include/simdjson/icelake/simd.h

On a Zen 4 processor:
Before:
```
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean       505635 ns       505492 ns           10 Gigabytes=1.24931G/s docs=1.97828k/s
```
After:
```
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        29382 …
```

fixing performance issue under Zen 4 processors

---

doc/basics.md
doc/iterate_many.md

the `ndjson[dot]org` expired, and point to incorrect website with malware. more in https://github.com/ndjson/ndjson.github.io/issues/24
follow up #2234

doc: replace ndjson[dot]org with ndjson spec

---

README.md

Hi Daniel, I'm writting to you because I'm excited to show you [zimdjson](https://github.com/EzequielRamis/zimdjson), a Zig port of simdjson that took me a year and a half to develop. Besides it is a "port", I've added to it new features and resolved some open issues you have here, which may fit in the C++ implementation.
- I've removed the padding requirement following ideas from https://github.com/simdjson/simdjson/issues/1686, now the parser handles the end of the input with an internal buffer. In very old commits I've managed to have the DOM parser to have a constant-size buffer (because of inlining) but the code was horrible, so I've decided to opt-in with a variable-size buffer which On-Demand can also utilize. The good news is that this buffer has not an average O(n) of memory, …

Add link to zimdjson

---

include/simdjson/common_defs.h

In the unlikely/impossible case where we do not have C++17 but where __cpp_lib_string_view is defined, we would fail to include `string_view`. It never caused any problem, thankfully.

missing string_view include

---

include/simdjson/common_defs.h
include/simdjson/jsonpathutil.h

Doing that will emit warning at https://github.com/microsoft/STL/blob/vs-2022-17.13/stl/inc/string_view#L12.

do not try to include <string_view> without C++17 for MSVC

---

benchmark/static_reflect/citm_catalog_benchmark/CMakeLists.txt
benchmark/static_reflect/twitter_benchmark/CMakeLists.txt
p2996/Dockerfile
p2996/README.md
p2996/remove_docker.sh
p2996/run_docker.sh

Currently, we have added to the json_builder_init branch support for C++26 static reflection. Unfortunately, it is not easy for most people to test out this feature.
This PR adds a tested and documented procedure to do so.

adding docker config and instructions so that our users can test the static reflection

---

include/simdjson/generic/ondemand/json_string_builder-inl.h
tests/builder/builder_string_builder_tests.cpp

These a tiny optimizations on top of `json_builder_init`. On one system and one benchmark, it reduces the number of instructions by about 7% and it improves the speed by about 5%.
Before:
```
$ ./buildreflect/benchmark/static_reflect/twitter_benchmark/benchmark_serialization_twitter
bench_simdjson_static_reflection                             :  1848.61 MB/s   0.42 Ms/s   3.19 GHz   1.73 c/b   5.40 i/b   3.13 i/c
```
After:
```
$ ./buildreflect/benchmark/static_reflect/twitter_benchmark/benchmark_serialization_twitter
bench_simdjson_static_reflection                             :  1945.19 MB/s   0.44 Ms/s   3.19 GHz   1.64 c/b   5.04 i/b   3.07 i/c
```

JSON builder optimizations

---

CMakeLists.txt
doc/basics.md
doc/dom.md
include/simdjson/generic/numberparsing.h
tests/dom/basictests.cpp
tests/ondemand/ondemand_number_tests.cpp

Currently, in simdjson, -0 in the DOM API gets materialized as the integer 0. We would now interpret it as the double value -0.0 when the macro SIMDJSON_MINUS_ZERO_AS_FLOAT is set. The string 0 is still interpreted as the integer 0.
The same would apply with `get_number()` and  `get_number_type()` in the On-Demand API.
There is no perfect solution here. In most programming languages (e.g., C or Python), the string `-0` is interpreted as a integer. Here is what you get in Python...
```Python
>>> x = -0
>>> x.is_integer()
True
>>> x
0
```
The motivation for this change is that, in JavaScript, -0 becomes -0.0.
Fixes https://github.com/simdjson/simdjson/issues/1532

Treat -0 as -0.0 when SIMDJSON_MINUS_ZERO_AS_FLOAT is set

---

README.md

This PR adds [GreptimeDB](https://github.com/GreptimeTeam/greptimedb) to the real-world usage list.
Starting from the `v0.14` release, GreptimeDB uses [`simd-json`](https://crates.io/crates/simd-json) to speed up parsing JSON strings. The performance is compelling, see the original PR [here](https://github.com/GreptimeTeam/greptimedb/pull/5794).
Thanks for the awesome lib. 🚀

chore: add greptimedb to the real-world usage list

---

dependencies/CMakeLists.txt

Google Benchmarks does not support MSYS2. Disable Google Benchmark when something like MSYS2 is detected.

Fixing MSYS2 issue

---

cmake/developer-options.cmake

Follow up to https://github.com/simdjson/simdjson/pull/2383 by @xkszltl 
We obey CMAKE_POSITION_INDEPENDENT_CODE if it is set. 
Fixes https://github.com/simdjson/simdjson/issues/2384

guarding the POSITION_INDEPENDENT_CODE

---

include/simdjson/concepts.h
include/simdjson/generic/ondemand/deserialize.h
include/simdjson/generic/ondemand/json_builder.h
include/simdjson/generic/ondemand/serialization-inl.h
include/simdjson/generic/ondemand/serialization.h
include/simdjson/generic/ondemand/std_deserialize.h
include/simdjson/generic/ondemand/value.h
include/simdjson/ondemand.h
tests/builder/CMakeLists.txt
tests/builder/static_reflection_builder_tests.cpp
tests/builder/static_reflection_comprehensive_tests.cpp
tests/builder/static_reflection_edge_cases_tests.cpp
tests/builder/static_reflection_enum_tests.cpp

[AI generated summary]
🚀 C++26 Static Reflection Features Added
1. Optional Type Support
Files Modified:
- /include/simdjson/concepts.h:118 - Fixed optional_type concept
- /include/simdjson/generic/ondemand/std_deserialize.h:251-274 - Generic optional deserialization
- /include/simdjson/generic/ondemand/json_builder.h:122-129 - Optional serialization
What was added:
- ✅ Generic optional deserialization with proper null handling
- ✅ Optional serialization (null → null, value → serialized value)
- ✅ Concept fix removing problematic assignment requirement
- ✅ Explicit specializations for std::optional<std::string> and std::optional<int>
Example:
std::optional<std::string> opt = "hello";
// Serializes to: "hello"
std::optional<std::string> null_opt;
// Serializes to: null
2. Smart Pointer …

Bringing a bit more use-cases for reflection based serializations (optional). Also adding string-based enum handling as requested on X.

---

include/simdjson/generic/ondemand/json_string_builder-inl.h

This addresses non-inlined symbols leaking into public headers after a recent update. Adding an inline specifier to these symbols fixes linker errors for downstream users.
Fixes #2402

Fix linker errors for downstream users caused by non-inline symbols in header

---

.gitignore
CMakeLists.txt

`cmake_policy` was added in https://github.com/simdjson/simdjson/commit/d7d19db6aefdec1db1b8345f9b23ed5b052e4966 with a cryptic comment. Removing it doesn't seem to make a difference, but its presence leads to warnings CMake warnings with modern CMake versions (as CMake <3.10 was deprecated). Example of such a warning can be found here: https://github.com/simdjson/simdjson/actions/runs/16573693121/job/46872474324#step:4:10
Thus all projects using simdjson with CMake > 3.28 get riddled with CMake warnings.
A minor unrelated additional commit in this PR is properly "gitignoring" the Visual Studio IDE artifact directory.

remove cmake_policy

---

doc/builder.md
include/simdjson/generic/ondemand/json_builder.h
include/simdjson/generic/ondemand/json_string_builder.h
tests/builder/builder_string_builder_tests.cpp

Make it easy to serialize to an existing `std::string` instance.

allow string reuse

---

include/simdjson/lsx/stringparsing_defs.h
singleheader/simdjson.cpp

Short title (summary): **Fix compiler error on loong64 by correcting narrowing conversion**
Description
- What did you change and why? (1-3 sentences)
- Issue reproduced / related issue: link the issue if relevant (e.g. #123)
Fixed a narrowing conversion that caused build failures on the loong64 architecture. The to_bitmask() function
returns an int, which was being assigned to a uint64_t variable, causing a **compiler error** with the
-Werror=narrowing flag. This was resolved by adding an explicit static_cast<uint64_t> to the return value.
Type of change
How to verify / test
- Add additional tests to verify bugs or new features.
- If you claim performance gains, you should provide benchmark numbers using high quality benchmarking code.
This change can be verified by building on Arch …

Fix: Correct narrowing conversion in lsx string parsing
