.drone.yml, .travis.yml, CMakeLists.txt
Adds support for CPack so that you can make .deb and .rpm packages.
Also tried to improve `.travis.yml` and `.drone.yml`
=> Update CMakeLists.txt, .travis.yml and .drone.yml

CMakeLists.txt, src/CMakeLists.txt
Closes: https://github.com/lemire/simdjson/issues/52
=> CMake: Add version and soversion to library target properties.

src/jsonparser.cpp
=> fix memory free

benchmark/CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
This patch is part of https://github.com/Microsoft/vcpkg/pull/5509 .
=> Export CMake targets

singleheader/simdjson.cpp, src/jsonioutil.cpp
Reuse a core function, instead of repeating code.
=> Reuse aligned_malloc

Notes.md
=> Minor typos

README.md
Some minor edits to sentences that felt choppy/awkward while reading. 
- Combined two sentences in the first paragraph.
- Made one sentence less verbose.
- Added commas to make the sentence read better.
Hope this helps!
=> Minor update to "Scope" section

tests/allparserscheckfile.cpp
https://github.com/lemire/simdjson/blob/772919ef1185f0ae5d147f916ee7175c9d16ae21/tests/allparserscheckfile.cpp#L109
=> Fix syntax error introduced by 772919

singleheader/simdjson.cpp, src/parsedjsoniterator.cpp
Fix the bug described in Issue #145 in both original and single header code base.
=> Bug fix for Issue #145

include/simdjson/portability.h
=> Add explicit conversion for leading and tailing zeros.

include/simdjson/common_defs.h, src/parsedjson.cpp, src/stage2_build_tape.cpp
So that @geofflangdale  may spend a peaceful week-end.
=> Fix for https://github.com/lemire/simdjson/issues/58

include/simdjson/numberparsing.h
=> Remove MMX code

README.md
The readme is now aware of the namespace. Not sure if it needs to be more explicit.
#203
=> Update README documentation to account for the new namespace

Dockerfile, include/simdjson/numberparsing.h, include/simdjson/simdutf8check_neon.h, include/simdjson/stage1_find_marks.h, include/simdjson/stage2_build_tape.h, include/simdjson/stringparsing.h
The utf8 validation works for Neon. The Neon implementation is complete.
=> Neon utf8validation

include/simdjson/stage1_find_marks.h
This reduces slightly the instruction counts.
=> Optimizing stage1

include/simdjson/numberparsing.h
The extra work introduced recently is seemingly unnecessary.
=> This simplifies back the number parsing code... 

.travis.yml
We sometimes do not build all utilities. This PR fixes that.
=> Making sure everything builds.

include/simdjson/portability.h
https://github.com/lemire/simdjson/issues/265
=> Disable UBSan error in trailing_zeroes().

include/simdjson/common_defs.h, include/simdjson/jsonparser.h, include/simdjson/stage2_build_tape.h, include/simdjson/stage2_build_tape_common.h, include/simdjson/stringparsing.h, include/simdjson/stringparsing_common.h, src/jsonparser.cpp
Would close https://github.com/lemire/simdjson/issues/231
=> This gets rid of the silly ALLOW_SAME_PAGE_BUFFER_OVERRUN

.gitignore
Just so I'm not seeing red every time I run `git status` :)
=> .gitignore that ignores all the things

include/simdjson/parsedjsoniterator.h, tests/basictests.cpp
=> This is a bug fix: our prev function was buggy.

src/simdjson.cpp
Fixes https://github.com/lemire/simdjson/issues/318
=> Safer handling of error codes, fixes 318

src/parsedjson.cpp, tests/basictests.cpp
Fix for the overrun
https://github.com/lemire/simdjson/issues/345
=> Follow up test and fix for https://github.com/lemire/simdjson/issues/345

src/jsonioutil.cpp
Helps fix https://github.com/lemire/simdjson/issues/340
=> Making get_corpus safer

include/simdjson/padded_string.h, include/simdjson/parsedjson.h, src/parsedjson.cpp
This is mostly a quality-of-life issue.
cc @piotte13
=> Introducing move assignments.

README.md, fuzz/Fuzzing.md
I tried to describe how the fuzzing is setup, how to build and test locally etc.
=> Add fuzzer badge and improve fuzzer documentation

include/simdjson/isadetection.h, src/jsonparser.cpp, src/jsonstream.cpp
... as the test as it is currently implemented will always evaluate to true.
Fixes #389
=> Correct detection of NEON support

amalgamation.sh, src/parsedjson.cpp, tests/basictests.cpp
Fixes issue 
https://github.com/lemire/simdjson/issues/388
=> Fixes issue 388

include/simdjson/portability.h
=> STRINGIFY implemented

benchmark/benchmarker.h
@jkeiser : can you have a look at this? I am just moving numbers around so that they look more like a spreadsheet and less like a dump of values.
=> I think we can align the numbers better (so it is prettier).

.github/workflows/fuzzers.yml
This should hopefully resolve the recent errors in the github action
for running the fuzzers.
=> update apt repos before installing

doc/JsonStream.md
=> Update JsonStream.md : simple typo

README.md
=> Update README.md : Simple typo

benchmark/benchfeatures.cpp, benchmark/benchmarker.h
Same information, just prints stage 2 as well as stage 1 (and overall) numbers now.
=> Print stage 2 information in feature benchmarker

src/stage2_build_tape.cpp
It shaves probably 0.1% off our instruction count. Might be worth merging just to be neat.
This will not get your code to run faster!
=> This is implementing @jkeiser optimization idea regarding false markers

Makefile, benchmark/parse_stream.cpp, include/simdjson/jsonstream.h, include/simdjson/parsedjson.h, include/simdjson/simdjson.h, include/simdjson/stage1_find_marks.h, src/generic/stage1_find_marks.h, src/generic/stage2_build_tape.h, src/generic/stage2_streaming_build_tape.h, src/jsoncharutils.h, src/jsonstream.cpp, src/parsedjson.cpp, src/simdjson.cpp, tests/basictests.cpp, tests/jsonstream_test.cpp
Fixes https://github.com/lemire/simdjson/issues/424 (and provide tests for it), as well as https://github.com/lemire/simdjson/issues/401
=> Debugging jsonstream

include/simdjson/jsonstream.h, src/jsonstream.cpp
This is a bit of a simplification. This code still needs a lot of help. I have commented out untested methods: I do not expect them to work.
=> Simpler jsonstream

benchmark/json_parser.h, extra/dumpbits.h, include/simdjson/jsonformatutils.h, include/simdjson/parsedjson.h, include/simdjson/portability.h, src/generic/stage1_find_marks.h, src/jsonparser.cpp, src/jsonstream.cpp, src/parsedjson.cpp, src/stage2_build_tape.cpp
This remains a few std::cout/std::err and putchar from the main library.
See https://github.com/eddelbuettel/rcppsimdjson/issues/1
cc @eddelbuettel
=> Removing all stdout stderr from main library.

include/simdjson/parsedjson.h
https://github.com/lemire/simdjson/pull/445
=> This isolates a fix found in the large PR 445

include/simdjson/portability.h, src/arm64/numberparsing.h, src/haswell/numberparsing.h, src/westmere/numberparsing.h
This is in preparation for further work on https://github.com/lemire/simdjson/pull/333
=> Basically, haswell processor should be able to count on lzcnt.

include/simdjson/padded_string.h
This is a fix for the problem reported in PR https://github.com/lemire/simdjson/pull/454
cc @DBJDBJ
=> Fixing potential mem leak.

Makefile, benchmark/benchfeatures.cpp, benchmark/benchmarker.h, benchmark/genfeaturejson.rb
This change records the cost of blocks with escapes in them in benchfeatures.
=> Benchmark escapes

README.md
=> Fix simple typo: submiting -> submitting

README.md
This is related to https://github.com/lemire/simdjson/issues/312
=> Documenting the fact that we are doing ok with tiny documents.

benchmark/parsingcompetition.cpp
To produce my recent stats, I added the ability to run multiple files through parsingcompetition.
I also made it scale the number of iterations to document size (inversely) so when you pass both large and small files it still gets the right number of iterations. It is inversely scaled so that 50MB = 1 iteration, 5MB = 10 iterations, and 5KB = 10000 iterations.
I also added a "repeat multiplier" parameter `-r MULTIPLIER`, which when you pass `2` will run twice the normal number of iterations for any given file.
This can all definitely be generalized, but I wasn't planning on it anytime soon--I figured better to share it than not!
=> Add ability to run multiple files in parsingcompetition

Makefile
=> We should not need to specify the architecture under ARM.

benchmark/benchmarker.h, include/simdjson/error.h
=> std::tie does not work on some compilers

.drone.yml
Let us see what cloud.io thinks of this test.
=> Testing clang + libc++

README.md, include/simdjson/document.h, include/simdjson/padded_string.h, tests/readme_examples.cpp
Redoing #546 since that never properly went to master. No need for a re-approval, I'm putting up a PR to ensure it still passes the tests.
=> Support document::parse("[1,2,3]"_padded)

README.md
Not sure how this update didn't make it in, but it's necessary.
=> Correct quick start

README.md
This again uses the new API : cc @jkeiser
=> Trying to give better guidance regarding large files.

benchmark/parsingcompetition.cpp
@jkeiser  This is probably not going to happen overnight, but we ought to migrate our own code to the new API.
=> Migrating parsingcompetition to new API.

benchmark/minifiercompetition.cpp, benchmark/parsingcompetition.cpp
A lot of small busy work to clean up the old code. This is part of it.
=> migrating minifier competition to new API

tools/json2json.cpp
=> Fixes issue 598.

README.md
This does a few things:
* Adds usage docs for everything I could think of
* Reorganizes it a bit to get code closer to the top, without neglecting marketing material like performance numbers
* Adds a table of contents
I tried not to lose any information--the only thing I believe was truly removed was the ParsedJsonIterator documentation. I'd appreciate a once-over at least.
It's a little big, but I'm not ready to figure out a multi-file hierarchy right now.
=> Reorganize README and add documentation

benchmark/parsingcompetition.cpp
I imagine it got lost in a merge.
=> Fix compile error in master

benchmark/statisticalmodel.cpp
Fixes https://github.com/simdjson/simdjson/issues/602
=> Fixing issue 602

doc/performance.md, jsonexamples/small/jsoniter_scala/README.md
See https://github.com/simdjson/simdjson/issues/70
=> Better documentation for issue 70

doc/basics.md, include/simdjson/document.h, include/simdjson/inline/document.h, tests/basictests.cpp, tests/pointercheck.cpp
Instead of doing JSON pointer. Also removes array [].
Fixes #630 and #631.
=> Make object[] key lookup

doc/basics.md, include/simdjson/document.h, include/simdjson/inline/document.h, tests/basictests.cpp, tests/readme_examples.cpp
=> Add element.type() for type switching

doc/basics.md, tests/readme_examples.cpp
Turns out there's a couple of things that can be simplified here. I went back and forth on whether to do `dom::array cars = parser.parse(cars_json);`. It's an extra line, but it also helps clarify what's going on. I went with shorter for now since this is the canonical "real world example to show our expressiveness."
=> Simplify cars example

doc/basics.md, doc/parse_many.md
I think that this is more accurate and precise.
We also had some broken links.
=> Minor fixes to our documentation regarding thread safety.

include/simdjson/portability.h
Fixes https://github.com/simdjson/simdjson/issues/691
=> Disabling threads on apple's hardware when optimizer is turned off

.github/workflows/fuzzers.yml, fuzz/build_fuzzer_variants.sh
upstream script does not support clang 8 anymore
=> switch to clang 9 in the github action

fuzz/Fuzzing.md
- refresh links now when simdjson is an organization
- improve docs, see #573
=> improve the fuzzer documentation, refresh links

fuzz/fuzz_dump.cpp, fuzz/fuzz_dump_raw_tape.cpp, fuzz/fuzz_parser.cpp, fuzz/fuzz_print_json.cpp
simdjson has moved forward! The fuzzers have been refreshed to use the new api.
=> do not use deprecated apis in the fuzzers

include/simdjson/document.h
get and is are important functions and I think we can generate better doxygen for them.
=> Tweaking the doxygen.

include/simdjson/document.h, include/simdjson/padded_string.h, tests/basictests.cpp
=> It is inconvenient to be unable to print a padded_string.

tests/basictests.cpp
We don't test whether we get the right error message when cast to invalid types. This PR makes it so, testing variants:
- is<>, type(), get<>, implicit cast, explicit cast
- exception and non-exception
=> Test more variants of cast, get, etc.

tests/CMakeLists.txt
=> Fix cmake error when SIMDJSON_COMPETITION=OFF

src/error.cpp
Currently, one of our error messages is absolutely terrible. This makes it a bit better.
Yes: this can be improved further, but the idea is to improve it so that it is not a matter of shame.
Fixes https://github.com/simdjson/simdjson/issues/789
=> Trying to improve a bit.

HACKING.md
Fixes issue https://github.com/simdjson/simdjson/issues/774
=> Fixes issue 774 and improves documentation for contributors

.gitignore
+ ignore build.* or build-* top level dirs
=> Add cmake /build dir to gitignore

singleheader/amalgamate.sh, src/simdjson.cpp
1) **Amalgamate src/simdjson.cpp as-is**
amalgamation.sh shouldn't change contents of src/simdjson.cpp by forcing dmalloc.h that didn't exist in non-amalgamated version and shouldn't change order of includes by placing simdjson.h at the top
2) **Do not modify amalgamation_demo.cpp from amalgamation.sh**
and update amalgamated headers
=> Make amalgamated functionally equivalent to src/simdjson.cpp

.appveyor.yml
This relies on cmake having a version that supports parallel on appveyor, but there's a reasonable chance of that ...
=> Run Windows tests and builds in parallel

include/simdjson.h, include/simdjson/common_defs.h, src/haswell/intrinsics.h, src/simdjson.cpp
=> Fix clang-cl build with Visual Studio

src/jsoncharutils.h
This should help with https://github.com/simdjson/simdjson/pull/841
=> This function is unused.

src/isadetection.h
To ease https://github.com/simdjson/simdjson/pull/841
=> Hiding cpuid_*_bit as well as related enum.

src/isadetection.h
Trying to ease https://github.com/simdjson/simdjson/pull/841
=> Trying to avoid unused warnings in isa detection.

HACKING.md, README.md, benchmark/bench_parse_call.cpp, benchmark/benchmarker.h, benchmark/distinctuseridcompetition.cpp, benchmark/get_corpus_benchmark.cpp, benchmark/minifiercompetition.cpp, benchmark/parseandstatcompetition.cpp, benchmark/parsingcompetition.cpp, doc/performance.md, tests/allparserscheckfile.cpp, tests/readme_examples.cpp
This explains the apparent discrepancy between our benchmark numbers.
=> There is confusion between gigabytes and gigibytes. Let us standardize throughout.

include/simdjson/document.h, include/simdjson/inline/document.h
This is just some trimming to make the code cleaner and more maintainable.  And maybe faster too though this is less certain.
=> Cleaning string_view

include/simdjson/document.h, src/document_parser_callbacks.h, src/generic/stage2_build_tape.h, src/generic/stage2_streaming_build_tape.h
Maybe it's just randomly influencing how g++ chooses registers, but on my machine, the first commit here drops perf by around 2.5% and the second commit restores it. It's pretty consistent. Everything in here *looks* like they should generate exact same code.
=> [For introspection only] Pair of commits that creates, then fixes, a performance issue

include/simdjson/common_defs.h
I am hoping that this fixes https://github.com/simdjson/simdjson/issues/880
=> We should guard the include

tools/jsonstats.cpp
We now record how many bytes are used by *repeated* keys. (That is, many keys may appear once, we don't want to consider those.)
First observation: all of our test files have fewer than 128 repeated keys:
```
$ for i in ../jsonexamples/*.json; do echo $i; ./tools/jsonstats  $i|grep repeated_key_distin; done
../jsonexamples/apache_builds.json
"repeated_key_distinct_count"=          3,
../jsonexamples/canada.json
"repeated_key_distinct_count"=          1,
../jsonexamples/citm_catalog.json
"repeated_key_distinct_count"=         24,
../jsonexamples/github_events.json
"repeated_key_distinct_count"=        114,
../jsonexamples/google_maps_api_compact_response.json
"repeated_key_distinct_count"=          6,
../jsonexamples/google_maps_api_response.json
"repeated_key_distinct_count"=          6, …
```
=> The jsonstats utility becomes ever more powerful.

singleheader/CMakeLists.txt, tests/CMakeLists.txt
Fixes https://github.com/simdjson/simdjson/issues/770
=> Detect bash instead of relying on MSVC detection.

src/generic/stage2/structural_parser.h
Right now we write the start element of an object or array when we first encounter it, and then update it at the end. With this patch, we just write the whole thing at the end.
This reduces the number of instructions somewhat, and gives a *very* modest--almost imperceptible--performance boost. But there's no real reason I can think of not to do it.
=> Don't write the start element at all until the end

CMakeLists.txt, CONTRIBUTING.md, HACKING.md, singleheader/amalgamate_demo.cpp, singleheader/simdjson.cpp, singleheader/simdjson.h, src/generic/stage1/utf8_lookup2_algorithm.h, src/generic/stage2/numberparsing.h, tests/basictests.cpp
Should be self-explanatory. Related https://github.com/simdjson/simdjson/pull/896
=> Using just ASCII.

benchmark/benchmark.h, benchmark/distinctuseridcompetition.cpp, benchmark/parseandstatcompetition.cpp, benchmark/parsingcompetition.cpp, simdjson-flags.cmake
This should finally allow us to run library-to-library benchmarks everywhere (?).
=> The "competition tests" are being made portable

src/generic/stage2/numberparsing.h
It should be self-explanatory. It is a simplification of the code logic.
It seems to trigger some perf. regression in some tests, but I call BS on that.
=> This introduces a tiny simplification in number parsing.

benchmark/minifiercompetition.cpp, doc/basics.md, include/simdjson/dom/array.h, include/simdjson/dom/document.h, include/simdjson/dom/element.h, include/simdjson/dom/object.h, include/simdjson/implementation.h, include/simdjson/inline/array.h, include/simdjson/inline/element.h, include/simdjson/inline/object.h, include/simdjson/minify.h, src/implementation.cpp, tests/basictests.cpp, tests/readme_examples.cpp
We have a fast function to minify JSON strings, but it has not been advertised until now.
=> Exposing the string minifier.

src/generic/stage1/json_string_scanner.h
Things I forgot from #462. Using this to run CI out of an abundance of caution, but I'll probably just merge after that.
=> Remove unnecessary functions

doc/basics.md, doc/parse_many.md, doc/performance.md
Trying to make sure that all possible questions are answered.
=> Some tweaks to the documentation

include/simdjson/dom/document_stream.h, include/simdjson/inline/document_stream.h, tests/basictests.cpp
Fixes https://github.com/simdjson/simdjson/issues/937
=> Fixing issue 937

include/simdjson/dom/object.h
Fixing https://github.com/simdjson/simdjson/issues/678
=> Fixing issue 678

include/simdjson/dom/array.h
Fix for https://github.com/simdjson/simdjson/issues/680
=> Document the complexity of array.at

Doxyfile, doc/basics.md, doc/implementation-selection.md, doc/parse_many.md, doc/performance.md, doc/tape.md
Instead of a reference to README, we can reuse our documentation in doxygen.
=> Tweaks doxygen so that we have a better main page.

include/simdjson/inline/parser.h, simdjson-flags.cmake, tests/basictests.cpp
Verifies https://github.com/simdjson/simdjson/issues/938
Fixes https://github.com/simdjson/simdjson/issues/938
=> Verifying (and fixing) issue 938

doc/basics.md, tests/readme_examples_noexceptions.cpp
Motivated by some benchmark on the Internet.
The idea is to have many examples since this is how people learn best.
=> New examples.

doc/basics.md, include/simdjson/implementation.h, include/simdjson/simdjson.h, src/arm64/dom_parser_implementation.cpp, src/arm64/implementation.h, src/fallback/dom_parser_implementation.cpp, src/fallback/implementation.h, src/generic/stage1/buf_block_reader.h, src/generic/stage1/utf8_validator.h, src/haswell/dom_parser_implementation.cpp, src/haswell/implementation.h, src/implementation.cpp, src/westmere/dom_parser_implementation.cpp, src/westmere/implementation.h, tests/CMakeLists.txt, tests/basictests.cpp, tests/readme_examples.cpp, tests/unicode_tests.cpp
This would open up the string UTF8 validation functions to outside users in a convenient manner.
=> Expose the UTF-8 string validation functions

.circleci/config.yml, CMakeLists.txt, simdjson-flags.cmake
Related to PR https://github.com/simdjson/simdjson/pull/956
Also, I think it fixes https://github.com/simdjson/simdjson/issues/955
=> This might enable folks to just build the library.

include/simdjson/dom/element.h, include/simdjson/inline/element.h, tests/basictests.cpp, tests/cast_tester.h
=> Make simdjson_result<element>.is() return bool

include/simdjson/dom/object.h, include/simdjson/dom/parsedjson_iterator.h, include/simdjson/dom/parser.h, include/simdjson/padded_string.h
Mostly, this removes a class that should no longer appear in doxygen (deprecated).
=> Very minor cleaning.

doc/basics.md
I think we should help cmake users a bit.
=> This improves slightly the documentation, adding instructions for CMake users.

doc/basics.md, include/simdjson/dom/element.h, include/simdjson/inline/element.h, tests/cast_tester.h
Fixes https://github.com/simdjson/simdjson/issues/961
=> Fixing issue 961

.circleci/config.yml, .drone.yml
At some point, we went dynamic by default whereas the tests assume the opposite.
=> Because we are dynamic by default, we never test static!

singleheader/amalgamate.sh, singleheader/amalgamate_demo.cpp
=> Nitpicking: demo should not crash on missing input

.circleci/config.yml
=> Putting back the perf tests.

include/simdjson/inline/tape_ref.h, include/simdjson/portability.h, singleheader/amalgamate_demo.cpp, singleheader/simdjson.cpp, singleheader/simdjson.h, src/haswell/bitmanipulation.h, src/jsoncharutils.h, src/westmere/bitmanipulation.h
=> Permit 32-bit GCC compilation

.circleci/config.yml, CMakeLists.txt, Doxyfile, include/simdjson/simdjson_version.h, singleheader/amalgamate_demo.cpp, singleheader/simdjson.cpp, singleheader/simdjson.h
Fixes https://github.com/simdjson/simdjson/issues/1000
=> We do not properly test just library.

.appveyor.yml, cmake/simdjson-flags.cmake, include/simdjson/common_defs.h, include/simdjson/dom/parser.h, include/simdjson/inline/padded_string.h, include/simdjson/inline/parser.h, include/simdjson/portability.h, singleheader/amalgamate_demo.cpp, singleheader/simdjson.cpp, singleheader/simdjson.h
Amazingly, if you get the very latest Visual Studio 2015, it seems to work.
(The initial Visual Studio 2015 does not work.)
Fixes https://github.com/simdjson/simdjson/issues/999
=> This might enable building the core library under Visual Studio 2015

src/generic/stage1/utf8_lookup4_algorithm.h
I did a rather thorough analysis of the bits generated by lookup4 and found the bits still correspond pretty well to concrete error classes. The current lookup4 tables also do a lot of cross-pattern matching it doesn't need to (i.e. there are more bits set in the lookup table than need to be, making it harder to cleanly explain what each bit means). This patch eliminates redundant bits entirely (all bits now map to distinct patterns), and self-documents the code by naming each bit with an error class.
Here is what the bits map to with this patch. "Too Short (768)" in the title means the Too Short error class matches 768 12-bit values. REQ means some patterns are _only_ matched by that bit; FULL means _all_ patterns for that error are matched by that bit, and "X" means the bit is both …
=> Self-document lookup4 and clean up extra bits

src/generic/stage2/numberparsing.h
This handles overflow checking without reparsing. It should significantly reduce the number of instructions in the program, as well as instructions executed when things go bad. It also eliminates a never_inline function, which is always a happy thing.
It first separates negative and positive overflow checking (which, whether a number is negative is actually known at compile time due to detection of the initial `-`).
Negative numbers are simple:
* If it's more than 18 digits, it has overflowed.
* If it's greater than INT64_MAX+1, it has overflowed (won't fit). uint64_t can fit all 18 digit numbers without overflow, so this is safe.
Positive numbers are harder:
* If it's more than 19 digits, it has overflowed.
* If it's *equal* to 19 digits, and the first digit is not '1', it has …
=> Don't reparse large integers

src/generic/stage2/numberparsing.h
This is merely a code simplification. To be merged into https://github.com/simdjson/simdjson/tree/jkeiser/simplify-integer-parse
=> Minor tweak on number parsing

.circleci/config.yml, .github/workflows/ubuntu18.yml, .github/workflows/ubuntu20.yml
Circle ci has too many errors due to gcc 7 crashing.
=> Trying again to move gcc 7 out of circle ci

src/arm64/dom_parser_implementation.cpp, src/generic/stage1/utf8_lookup4_algorithm.h, src/haswell/dom_parser_implementation.cpp, src/westmere/dom_parser_implementation.cpp
Motivated by a tweet by Z. Wegner who pointed out that lookup3 was probably not optimal. I think he is correct.
This lookup4 is faster.
=> lookup4 (new UTF-8 validation)

CONTRIBUTING.md, include/simdjson/dom/parser.h
cc @casperisfine 
@jkeiser I have also changed the case of the constant. Did you put it all uppercase on purpose?
=> Better documentation of default_batch_size

include/simdjson/dom/array.h, include/simdjson/dom/object.h, singleheader/amalgamate_demo.cpp, singleheader/simdjson.cpp, singleheader/simdjson.h
The recently introduced C++ 20 features fail.
This will disable them. We can try re-enabling them later.
=> Disabling cxx20

.gitattributes
This is required for amalgamate.sh to produce correct results
=> Use Unix line endings for c/c++ code

include/simdjson/portability.h
Mentioned by @pps83 
Would help fix https://github.com/simdjson/simdjson/issues/1066
=> Adding strings.h header.

benchmark/benchmarker.h, benchmark/minifiercompetition.cpp, include/simdjson/dom/parser.h, include/simdjson/inline/padded_string.h, include/simdjson/inline/parser.h, include/simdjson/padded_string.h, include/simdjson/portability.h
This is simpler than https://github.com/simdjson/simdjson/pull/1068
Would help fix https://github.com/simdjson/simdjson/issues/1066
=> This removes the crazy alignment requirements.

include/simdjson/common_defs.h
@eddelbuettel will be happy to know that he won't need to disable computed gotos anymore with the next release.
=> This is dead code (computed gotos)

singleheader/amalgamate.sh, singleheader/amalgamate_demo.cpp
README.md and amalgamate_demo.cpp are always the same, there is no point to keep a copy and recreate them from amalgamate.sh
=> Do not update README.md and amalgamate_demo.cpp from amalgamate.sh

.circleci/config.yml, doc/performance.md, include/simdjson/portability.h, src/generic/dom_parser_implementation.h
Also removes a CI target (yay!).
=> Remove information about nonexistent computed gotos :)

benchmark/bench_sax.cpp, src/generic/stage2/numberparsing.h
If we are going to have internal SAX, I think we ought to have a couple of benchmarks. This was written quickly but might prove useful.
This is mostly for discussion though it could be merged (into jkeiser/sax-bench). My main purpose was to learn about the new code.
I invite you to checkout the performance results for yourself. Assuming that I did not get anything wrong, they are impressive.
=> This adds a new SAX benchmark

.cirrus.yml, benchmark/checkperf.cmake, cmake/simdjson-flags.cmake, dependencies/CMakeLists.txt, singleheader/CMakeLists.txt, tests/CMakeLists.txt
With the recent changes to amalgamate.sh, it looks like we can't amalgamate anymore under FreeBSD. This PR would disable bash and amalgamation under FreeBSD.
=> This would disable bash scripts under FreeBSD.

doc/basics.md, tests/readme_examples.cpp
Should be obvious.
I would not be surprised if I introduced the problem.
=> This corrects a small typo in the documentation.

.cirrus.yml, benchmark/checkperf.cmake, cmake/simdjson-flags.cmake, dependencies/CMakeLists.txt, include/simdjson/dom/document_stream.h, include/simdjson/dom/parser.h, include/simdjson/inline/document_stream.h, singleheader/CMakeLists.txt, tests/CMakeLists.txt, tests/document_stream_tests.cpp
Fix for https://github.com/simdjson/simdjson/issues/925
One might compile with threading enabled and still not want simdjson to use threads.
=> This allows the users to disable threading.

doc/basics.md, include/simdjson/dom/array.h, include/simdjson/dom/element.h, include/simdjson/dom/object.h, include/simdjson/inline/array.h, include/simdjson/inline/element.h, include/simdjson/inline/object.h, include/simdjson/inline/tape_ref.h, include/simdjson/internal/tape_ref.h, tests/CMakeLists.txt, tests/jsoncheck.cpp, tests/pointercheck.cpp, tests/readme_examples.cpp, tools/CMakeLists.txt
Fixes our support for JSON pointer,  Issue https://github.com/simdjson/simdjson/issues/1063
Credit to @bbulkow
=> Verification and fix for issue 1063 (JSON Pointers)

cmake/simdjson-flags.cmake, include/simdjson/portability.h
=> Remove SIMDJSON_DO_NOT_USE_THREADS_NO_MATTER_WHAT

.circleci/config.yml, .github/workflows/ubuntu18-checkperf.yml, .github/workflows/ubuntu18.yml, .github/workflows/ubuntu20-checkperf.yml, .github/workflows/ubuntu20.yml
This should clearly distinguish performance checks from other checks.
=>  This will isolate the perf checks in CI

.circleci/config.yml, .drone.yml
A couple other places that don't appear to be excluding checkperf. Extension of #1164.
=> Isolate checkperf more

doc/basics.md, include/simdjson/minify.h, src/fallback/dom_parser_implementation.cpp, src/generic/stage1/json_minifier.h, tests/basictests.cpp, tests/readme_examples.cpp, tools/minify.cpp
Fixes https://github.com/simdjson/simdjson/issues/1170
=> Fixes issue 1170 and makes the usage of minify easier.

benchmark/linux/linux-perf-events.h, benchmark/twitter/sax_tweet_reader_visitor.h, doc/basics.md, doc/basics_doxygen.md, doc/performance.md, include/simdjson/dom/document-inl.h, include/simdjson/dom/parsedjson_iterator-inl.h, include/simdjson/dom/parsedjson_iterator.h, include/simdjson/dom/parser-inl.h, include/simdjson/dom/parser.h, include/simdjson/error.h, include/simdjson/internal/tape_ref-inl.h, include/simdjson/padded_string-inl.h, src/generic/stage1/buf_block_reader.h, src/generic/stage2/tape_builder.h, tests/basictests.cpp, tests/errortests.cpp, tests/jsoncheck.cpp, tests/minefieldcheck.cpp, tests/numberparsingcheck.cpp, tests/parse_many_test.cpp, tests/pointercheck.cpp, tests/readme_examples.cpp, tests/stringparsingcheck.cpp, tests/unicode_tests.cpp
Related to issue https://github.com/simdjson/simdjson/issues/1175
We are clear enough that padding is required. However, it is apparently not clear that the padded bytes may be accessed. This needs to be documented.
=> Adding documentation.

include/simdjson/dom/parser.h, src/fallback/dom_parser_implementation.cpp, tests/basictests.cpp
Fixes https://github.com/simdjson/simdjson/issues/1187
=> Attempt to fix issue 1187.

tests/basictests.cpp
There is supposedly an issue with input buffers spanning 129 bytes:
https://oss-fuzz.com/testcase-detail/5079699967180800
I cannot verify the issue.
@pauldreik  : can you help?
=> This adds two tests to verify a new fuzzer issue. (So far I could not  verify.)

include/simdjson/dom/serialization-inl.h, tests/basictests.cpp
Issue detected thanks to @pauldreik 's fuzzing.
I took the opportunity to optimize slightly the code so that it should be a bit faster.
=> Fixing "undefined behavior" issue in new fast_itoa functions

src/isadetection.h, tests/stringparsingcheck.cpp
=> Minor fixes to some headers (tweak)

fuzz/build_fuzzer_variants.sh
=> fix merge conflict on master

CMakeLists.txt
This is nicer and more maintainable.
=> Simplifying slightly the logic in the cmake

doc/basics.md, doc/basics_doxygen.md
Being explicit about the suffix.
=> Being more specific regarding the padding.

doc/ondemand.md, tests/ondemand/ondemand_basictests.cpp
This serves to validate the traversal order with on demand. Simple sanity checks. It also adds some improvements to the documentation.
fixes https://github.com/simdjson/simdjson/issues/1229
=> This adds new tests regarding ordering.

benchmark/largerandom/sax.h, benchmark/partial_tweets/sax.h, include/simdjson/dom/document-inl.h
=> We have hardcoded 32 values

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/standard-issue-template.md, doc/ondemand.md
=> Tweaking further the documentation.

tests/ondemand/ondemand_basictests.cpp
Just trying not to introduce misleading anti-patterns.
=> There are a couple of extra value() that should not be there

include/simdjson/arm64/numberparsing.h, include/simdjson/fallback/numberparsing.h, include/simdjson/generic/numberparsing.h, include/simdjson/generic/ondemand/json_iterator-inl.h, include/simdjson/ppc64/numberparsing.h
I am also trying to scope the memcpy to be a good C++ citizen.
=> Mostly tiny changes, with one optimization to fallback for number parsing.

.github/workflows/fuzzers.yml, fuzz/CMakeLists.txt, fuzz/fuzz_ondemand.cpp
Eventually this will hopefully fuzz the new ondemand functionality.
Work in progress, this pull request exists so I can run the CI jobs conveniently.
=> fuzz on demand

.drone.yml, scripts/addcmakeppa.sh
I have no idea how things went from [all green](https://cloud.drone.io/simdjson/simdjson/7049) to [some failing](https://cloud.drone.io/simdjson/simdjson/7053) without any changes to Drone CI.  
I even rebased my changes in the PR to make sure the CI scripts are in sync.
I took the time to check all the packages that are needed are actually available.
=> Fix unintended Drone CI break

include/simdjson/generic/numberparsing.h, tests/ondemand/ondemand_basictests.cpp
=> fix segfault in numberparsing #1273

include/simdjson/generic/numberparsing.h, tests/ondemand/ondemand_basictests.cpp
Accidentally forgot to commit this change before I merged #1274
=> remove asserts from compute_float_64

.drone.yml, benchmark/parsingcompetition.cpp, dependencies/CMakeLists.txt, include/simdjson/generic/numberparsing.h, singleheader/simdjson.cpp, singleheader/simdjson.h, src/from_chars.cpp, src/to_chars.cpp
It appears that legacy libc++ requires special care.
=> Updating main branch for legacy libc++ support

include/simdjson/generic/numberparsing.h
see if it's the good old define max that tricks us
=> it the windows numeric_limits problem caused by the max macro?

fuzz/Fuzzing.md, fuzz/minimize_and_cleanse.sh
This adds a helper script to conveniently trim down fuzzer crashes locally.
=> add script and instructions for minimizing and cleansing fuzz crashes

singleheader/amalgamate.py
This is spinoff from work I did trying to hunt down a weird fuzzer crash, but I think it may be generally useful. It replaces the macro SIMDJSON_IMPLEMENTATION during amalgamation so it is easier to follow (for humans and IDE's) the code in the single file header.
=> when amalagamating, replace the SIMDJSON_IMPLEMENTATION

include/simdjson/dom/document_stream-inl.h, tests/document_stream_tests.cpp, tests/parse_many_test.cpp
Fixes https://github.com/simdjson/simdjson/issues/1302
cc @jkeiser
=> This fixes issue 1302

include/simdjson/dom/document_stream-inl.h, include/simdjson/dom/parser.h, tests/document_stream_tests.cpp
This attempts to verify issues
https://github.com/simdjson/simdjson/issues/1311
https://github.com/simdjson/simdjson/issues/1310
https://github.com/simdjson/simdjson/issues/1309
https://github.com/simdjson/simdjson/issues/1308
https://github.com/simdjson/simdjson/issues/1307
They all appear to be invalid documents that cannot be iterated over.
=> Trying to verify recent document stream issues.

.github/workflows/alpine.yml, src/fallback/dom_parser_implementation.cpp, src/generic/stage1/json_minifier.h, src/generic/stage1/json_scanner.h, src/generic/stage1/json_string_scanner.h, src/generic/stage1/json_structural_indexer.h, tests/document_stream_tests.cpp
We have an issue that, in some rare cases, with adversarial inputs, our code will misbehave.
credit: @pauldreik  for identifying the issue and helping me reproduce it.
=> This should fix an issue we have with unclosed strings with document_stream

include/simdjson/haswell.h
Fixes https://github.com/simdjson/simdjson/issues/1247
=> Fixing issue 1247

.circleci/config.yml, .github/workflows/fix-trailing-whitespace.yml, include/simdjson/dom/document_stream-inl.h, tests/document_stream_tests.cpp
Adds even more tests with respect to threading.
=> more thread testing

.github/workflows/msys2-clang.yml
We should test clang under msys2.
=> Adding clang/msys-ci

tests/ondemand/ondemand_assert_out_of_order_values.cpp
Right now, if you just run `ctest`, it will run the new assert test, even in release mode. This causes it to fail, which could be concerning to users. This makes the assert tests run, but not actually run the tests, if you are in release mode.
Fixes #1350 .
Note that this *could* be done by preventing it from compiling. I'm amenable to that, but also hoping to add an assert-like capability to release builds (for those who don't opt out), so I expect to run some of these tests against release builds at some point.
=> Make assert test succeed (not run anything) in Release builds

README.md, examples/quickstart/CMakeLists.txt, examples/quickstart/add_quickstart_test.cmake, examples/quickstart/quickstart_ondemand.cpp, examples/quickstart/quickstart_ondemand_noexceptions.cpp
This adds a quick start for On Demand to README.md, and tests it.
A User Guide is still forthcoming. Bit by bit ...
=> Add quick start for On Demand

doc/ondemand.md, doc/ondemand_design.md
This is a PR to modify https://github.com/simdjson/simdjson/pull/1360 slightly. I have made a few edits that I think are useful.
Note that this does not apply to our main branch but to https://github.com/simdjson/simdjson/pull/1360
=> Minor edits regarding the On Demand documentation.

tests/CMakeLists.txt, tests/trivially_copyable_test.cpp
=> Add element representation trivially_copyable property test

tests/jsoncheck.cpp, tests/minefieldcheck.cpp
the function has the ability to exit without first clearing the allocated memory.
I propose to fix this error.
=> fix function was exited without releasing

.github/workflows/ubuntu20-checkperf.yml, benchmark/benchmarker.h, include/simdjson/arm64/simd.h, include/simdjson/generic/stringparsing.h, include/simdjson/ppc64/simd.h
CI change. I expect it will pass.
=> This adds a little test to see if we can compiler with very strict flags (conventional casts)

.github/workflows/ubuntu20.yml
It seems that many users rely on `find_package(simdjson)` in CMake and this broke in 0.8.0 (fixed in 0.8.1). This PR tests the functionality.
=> Let us actually test the find package functionality.

include/simdjson/generic/dom_parser_implementation.h
Fixes https://github.com/simdjson/simdjson/issues/948
=> Deleting unused function.

tests/basictests.cpp
=> unit test macos build fix

.github/workflows/vs15-ci.yml
We already have Visual Studio 2017 CI tests but a user reports an issue at
https://github.com/simdjson/simdjson/issues/1437
This PR is meant to help verify it.
=> Adding Visual studio 2017 CI tests to GitHub actions.

doc/basics.md
It does not seem to have been documented previously.
=> Document SIMDJSON_EXCEPTIONS

src/generic/stage1/buf_block_reader.h, src/generic/stage2/tape_builder.h
Should be self-explanatory.
Ping @rrohak
=> Removing mallocs in main library.

include/simdjson/dom/element.h, include/simdjson/dom/object.h, include/simdjson/error.h, include/simdjson/generic/implementation_simdjson_result_base.h, singleheader/simdjson.h
This PR corrects a few typos in the comments.
=> Let us stop evoluating.

tests/basictests.cpp, tests/document_stream_tests.cpp, tests/document_tests.cpp, tests/integer_tests.cpp, tests/ondemand/ondemand_number_tests.cpp, tests/random_string_number_tests.cpp
I suspect that some large stack allocations might trigger problems in CI, especially with sanitizers. This PR makes all 1kB+ stack allocations into heap allocations.
=> Avoiding large stack allocation.

tests/basictests.cpp, tests/ondemand/ondemand_parse_api_tests.cpp
I do not expect that there is a bug, but it makes sense to test empty files as it is one corner case.
=> We should be able to open empty files (paranoid test)

doc/basics.md, doc/dom.md, include/simdjson/generic/ondemand-inl.h, include/simdjson/generic/ondemand.h, include/simdjson/generic/ondemand/serialization-inl.h, include/simdjson/generic/ondemand/serialization.h, src/to_chars.cpp, tests/minify_tests.cpp, tests/ondemand/CMakeLists.txt, tests/ondemand/ondemand_tostring_tests.cpp, tools/json2json.cpp
This implementation consumes the element. We need to a way to rewind pointers, I will open an issue.
Fixes https://github.com/simdjson/simdjson/issues/1498
=> This implements string serialization for On Demand instances.

src/generic/stage2/json_iterator.h
=> Correcting what seems to be a typo and adding some extra logging.

README.md
Update the journal reference of the "Validating UTF-8 In Less Than One
Instruction Per Byte" paper.
=> Update journal reference

include/simdjson/padded_string-inl.h, include/simdjson/padded_string.h
Don't allocate std::string just for padded_string::load()
Use std::string_view instead
=> Don't allocate std::string just for padded_string::load()

doc/basics.md, tests/ondemand/ondemand_tostring_tests.cpp
We do not really explain it very well currently. This improves the explanation.
=> Improving how to_string is explained.

include/simdjson/generic/ondemand/json_iterator-inl.h, include/simdjson/generic/ondemand/json_iterator.h, include/simdjson/generic/ondemand/token_iterator-inl.h, include/simdjson/generic/ondemand/token_iterator.h, include/simdjson/generic/ondemand/value_iterator-inl.h, include/simdjson/generic/ondemand/value_iterator.h, tests/ondemand/ondemand_array_tests.cpp
Add tests and a correction.
Fixes https://github.com/simdjson/simdjson/issues/1588
=> Verifies and fixes issue 1588

.github/workflows/alpine.yml, .github/workflows/mingw-ci.yml, .github/workflows/mingw64-ci.yml, .github/workflows/msys2-clang.yml, .github/workflows/msys2.yml, .github/workflows/ubuntu18-checkperf.yml, .github/workflows/ubuntu18-threadsani.yml, .github/workflows/ubuntu18.yml, .github/workflows/ubuntu20-checkperf.yml, .github/workflows/ubuntu20-noexcept.yml, .github/workflows/ubuntu20-nothread.yml, .github/workflows/ubuntu20-threadsani.yml, .github/workflows/ubuntu20.yml, .github/workflows/vs15-ci.yml, .github/workflows/vs16-arm-ci.yml, .github/workflows/vs16-ci.yml, .github/workflows/vs16-clang-ci.yml, .github/workflows/vs16-ninja-ci.yml, .github/workflows/vs16-noexcept-ci.yml
We used to test ARM builds under Visual Studio but I want to make sure that they work.
=> Adds compile-test for Visual Studio + ARM and turn developer mode throughout CI.

include/simdjson/generic/ondemand/parser.h, tests/ondemand/ondemand_json_pointer_tests.cpp
The On Demand API only validates what you use. This PR adds tests to codify this behavior.
cc @NicolasJiaxin 
Fixes https://github.com/simdjson/simdjson/issues/1623
=> Added tests over invalid documents.

.github/workflows/ubuntu20-noexcept.yml, .github/workflows/ubuntu20-nothread.yml, .github/workflows/ubuntu20.yml, .github/workflows/vs15-ci.yml, .github/workflows/vs16-ci.yml
=> We should be more generously testing in debug mode.

.vscode/settings.json, include/simdjson/generic/ondemand/array-inl.h, include/simdjson/generic/ondemand/value_iterator-inl.h, include/simdjson/generic/ondemand/value_iterator.h
It is a private implementation that should be save to use for when we need to go at the beginning of an array or an object to go through it again.
It is not meant for end users.
=> This introduces a reset functionality for object and array containers

doc/basics.md, include/simdjson/generic/ondemand/document-inl.h, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/value-inl.h, include/simdjson/generic/ondemand/value.h, src/internal/error_tables.cpp, tests/ondemand/ondemand_document_stream_tests.cpp, tests/ondemand/ondemand_readme_examples.cpp
There were still many remnants of the DOM documentation in the main documentation file. All examples are now On Demand.
=> Additional tests and document tuning

singleheader/amalgamate_demo.cpp, singleheader/simdjson.cpp, singleheader/simdjson.h
Our current amalgamate_demo.cpp demo file used DOM.
=> This will update the amalgamate_demo.cpp file to use On Demand.

tests/ondemand/ondemand_misc_tests.cpp
This validates that we can use a document_reference.
=> Small test for document_reference usage.

doc/basics.md, include/simdjson/generic/ondemand/value_iterator-inl.h, tests/ondemand/ondemand_error_location_tests.cpp, tests/ondemand/ondemand_readme_examples.cpp
I made some minor changes to how the new current_location() method works and I updated the documentation.
These are minor changes.
=> Tweaking current_location().

CMakeLists.txt, Doxyfile, README.md, include/simdjson/simdjson_version.h, singleheader/simdjson.cpp, singleheader/simdjson.h
This is a candidate release for version 1.0.0.
=> Release 1.0.0 candidate.

tests/dom/document_stream_tests.cpp, tests/ondemand/ondemand_document_stream_tests.cpp
=> Minor typo.

doc/basics.md, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/object.h, include/simdjson/generic/ondemand/value.h, tests/ondemand/ondemand_object_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/1745 (documentation issue?)
=> Adding tests for issue 1745.

src/generic/stage2/json_iterator.h
The variable is called LOG_ENABLED, not ENABLE_LOGGING. Fix the
documentation in json_iterator.h.
=> Fix typos in documentation

include/simdjson/implementations.h
Minor tweak for non-Visual Studio users.
=> Adding conditions on haswell

doc/basics.md, doc/dom.md, include/simdjson/generic/ondemand/array.h, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/value.h, singleheader/simdjson.h
Helps with https://github.com/simdjson/simdjson/issues/1764
=> Making the documentation more explicit.

benchmark/benchfeatures.cpp, benchmark/dom/parse.cpp, benchmark/json_benchmark/run_json_benchmark.h, doc/implementation-selection.md, fuzz/fuzz_implementations.cpp, fuzz/supported_implementations.h, include/simdjson/dom/parser-inl.h, include/simdjson/generic/ondemand/parser-inl.h, include/simdjson/implementation.h, singleheader/simdjson.cpp, singleheader/simdjson.h, src/implementation.cpp, tests/checkimplementation.cpp, tests/dom/basictests.cpp, tests/dom/document_stream_tests.cpp, tests/dom/document_tests.cpp, tests/dom/errortests.cpp, tests/dom/jsoncheck.cpp, tests/dom/minefieldcheck.cpp, tests/dom/parse_many_test.cpp, tests/dom/random_string_number_tests.cpp, tests/dom/readme_examples.cpp, tests/ondemand/test_ondemand.h, tests/unicode_tests.cpp, tools/json2json.cpp, tools/minify.cpp
Fixes https://github.com/simdjson/simdjson/issues/1771
=> Use static variables to enforce initialization order.

benchmark/benchfeatures.cpp, benchmark/dom/parse.cpp, benchmark/json_benchmark/run_json_benchmark.h, doc/implementation-selection.md, fuzz/fuzz_implementations.cpp, fuzz/supported_implementations.h, include/simdjson/dom/parser-inl.h, include/simdjson/generic/ondemand/parser-inl.h, include/simdjson/implementation.h, singleheader/simdjson.cpp, singleheader/simdjson.h, src/implementation.cpp, tests/checkimplementation.cpp, tests/dom/basictests.cpp, tests/dom/document_stream_tests.cpp, tests/dom/document_tests.cpp, tests/dom/errortests.cpp, tests/dom/jsoncheck.cpp, tests/dom/minefieldcheck.cpp, tests/dom/parse_many_test.cpp, tests/dom/random_string_number_tests.cpp, tests/dom/readme_examples.cpp, tests/ondemand/test_ondemand.h, tests/unicode_tests.cpp, tools/json2json.cpp, tools/minify.cpp
Fixes https://github.com/simdjson/simdjson/issues/1771
=> Use static variables to enforce initialization order. (#1773)

include/simdjson/arm64/simd.h, include/simdjson/haswell/simd.h, include/simdjson/ppc64/simd.h, include/simdjson/westmere/simd.h
This fixes the build warnings described in issue #1782
=> Fix C++20 build warnings (#1782)

CMakeLists.txt
This is an experiment in relation with issue 1803.
=> what happens if we remove this check for CI?

CMakeLists.txt
This simplifies the build somewhat.
=> Always including developer-options.cmake

doc/basics.md
`simdjson::ondemand::element` doesn't exist
=> docs(basics): ondemand::element -> ::document

include/simdjson/generic/numberparsing.h, tests/ondemand/ondemand_number_tests.cpp
There is a small logical error in the get_number_type() function.
Fixes https://github.com/simdjson/simdjson/issues/1818
=> Fixing get_number_type(), issue 1818

doc/basics.md, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/value.h
Fixes https://github.com/simdjson/simdjson/issues/1820
=> Better documentation regarding the direct get_number_type() method.

include/simdjson/generic/ondemand/document-inl.h, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/value-inl.h, include/simdjson/generic/ondemand/value.h, include/simdjson/generic/ondemand/value_iterator.h, tests/ondemand/ondemand_readme_examples.cpp
This adds a direct way to get access to the current depth. I am not planning to overly 
cc @NicolasJiaxin  could you review ?
=> Adds 'current_depth()'.

include/simdjson/generic/ondemand/json_iterator.h, include/simdjson/generic/ondemand/logger-inl.h, include/simdjson/generic/ondemand/object.h, include/simdjson/generic/ondemand/value.h
Fixes a few typos in code and code documentation.
=> fix a few typos

benchmark/benchmarker.h, include/simdjson/common_defs.h, include/simdjson/implementations.h, singleheader/amalgamate.py, singleheader/simdjson.cpp, singleheader/simdjson.h, src/generic/stage1/json_structural_indexer.h, src/icelake/dom_parser_implementation.cpp, tools/minify.cpp
It is convenient to be able to benchmark minify.
=> Let us time minify and make sure AVX-512 is used by default.

.github/workflows/ubuntu22-gcc12.yml, tests/ondemand/ondemand_assert_out_of_order_values.cpp
Fixes https://github.com/simdjson/simdjson/issues/1835
=> Attempting to support gcc12 without warnings.

include/simdjson/error.h, singleheader/simdjson.h
Fixes https://github.com/simdjson/simdjson/issues/1851
=> Removing dead code.

benchmark/bench_ondemand.cpp, benchmark/json2msgpack/simdjson_dom.h, benchmark/json2msgpack/simdjson_ondemand.h
=> Adding DOM benchmark to msgpack

include/simdjson/dom/parser-inl.h, include/simdjson/padded_string-inl.h, src/generic/stage1/json_scanner.h, src/generic/stage1/utf8_lookup4_algorithm.h
@lemire, hi
Minor fixes in condition expression, Win64 systems and trivial constructors
=> Fixed if-else-if condition, Win64 _fseeki64, trivial constructors C++11

include/simdjson/implementation.h
Some issues in doxygen were solved.
=> Fix documentation of description() method in implementation

include/simdjson/generic/numberparsing.h, tests/dom/basictests.cpp
Fixes #1898
Before this commit, simdjson parsed "-1e-999" and "-0e-999" and "-1e-342" as 0.0.
After this commit, those JSON strings get parsed as -0.0. (https://en.wikipedia.org/wiki/Signed_zero)
The old behavior was inconsistent with the way simdjson parsed "-0.0" as -0.0.
=> fix: Preserve sign for number with underflowing exponent

include/simdjson/generic/numberparsing.h, tests/dom/basictests.cpp, tests/ondemand/ondemand_number_tests.cpp
Combines the fix by @TysonAndre with new tests.
Fixes https://github.com/simdjson/simdjson/issues/1898
=> Fixing issue 1898

.github/workflows/ubuntu22-clang14.yml
We compile with `-Werror` and we want to make sure that we do not trigger any warning.
=> Adding clang14 CI

include/simdjson/generic/ondemand/logger-inl.h, tests/ondemand/CMakeLists.txt, tests/ondemand/ondemand_log_tests.cpp
See https://github.com/simdjson/simdjson/discussions/1938
=> Testing and fixing log issues.

dependencies/import.cmake
=> Safer add-dependency script.

.github/workflows/s390x.yml, doc/basics.md, doc/implementation-selection.md
So we can say that we have big-endian support.
=> Trying s390x in CI

README.md
This should make the whitespace test pass again.
=> Remove trailing whitespace in README.md

include/simdjson/internal/isadetection.h, singleheader/simdjson.cpp, singleheader/simdjson.h
Credit to @StefanStojanovic from Microsoft for raising the issue.
=> Fixing support for windows ARM64

doc/basics.md, tests/ondemand/ondemand_readme_examples.cpp
Some users feel that we are missing examples in the documentation.
=> This adds some examples to the documentation.

CMakeLists.txt, tests/dom/random_string_number_tests.cpp, tools/jsonstats.cpp
This should help with issue 1963 as a workaround for the MingGW bug.
@spnda Please verify.
Fix https://github.com/simdjson/simdjson/issues/1963
=> Adding -Og to debug builds.

.github/workflows/ubuntu22-glibcxxassertions.yml, cmake/developer-options.cmake, tests/dom/basictests.cpp, tests/ondemand/ondemand_array_tests.cpp
Relates to https://github.com/simdjson/simdjson/issues/1968
=> Adding tests with _GLIBCXX_ASSERTIONS

cmake/developer-options.cmake, include/simdjson/generic/ondemand/json_iterator-inl.h, include/simdjson/generic/ondemand/json_iterator.h, include/simdjson/generic/ondemand/value_iterator-inl.h, tests/ondemand/ondemand_misc_tests.cpp, tests/test_macros.h
Verifies...
Fixes https://github.com/simdjson/simdjson/issues/1981
=> Fix for issue 1981

.github/workflows/ppc64.yml
=> Adding more PPC64 testing.

doc/basics.md
Trying to improve our documentation.
=> Document key queries.

doc/basics.md, include/simdjson/generic/ondemand/array-inl.h, include/simdjson/generic/ondemand/array.h, include/simdjson/generic/ondemand/object-inl.h, include/simdjson/generic/ondemand/object.h, tests/ondemand/ondemand_readme_examples.cpp
This documents `raw_json()`. It does not change its behaviour (as alluded in 1943).
This is a documentation update, mostly, with some additional tests (to verify the documentation).
=> Fixing issue 1943

benchmark/bench_dom_api.cpp, benchmark/benchmarker.h, include/simdjson/portability.h
=> Removing iso header.

.github/workflows/ubuntu22-cxx20.yml, .github/workflows/vs17-ci-cxx20.yml, cmake/developer-options.cmake, tests/dom/basictests.cpp, tests/minify_tests.cpp, tests/ondemand/ondemand_json_pointer_tests.cpp, tests/ondemand/ondemand_misc_tests.cpp, tests/ondemand/ondemand_readme_examples.cpp, tests/ondemand/ondemand_tostring_tests.cpp
We want to test with CXX 20 enabled.
=> Adding CXX 20 to CI

.github/ISSUE_TEMPLATE/bug_report.md, include/simdjson/haswell/bitmanipulation.h, include/simdjson/portability.h, include/simdjson/ppc64/bitmanipulation.h, include/simdjson/westmere/bitmanipulation.h
This tunes some comments regarding 32-bit support.
=> We do actually support legacy 32-bit systems, although not with fast kernels.

.github/workflows/fuzzers.yml
It seems that the llvm.sh script was updated and it is now causing us problems.
I am trying to apply a fix proposed by @annnei at https://github.com/llvm/llvm-project/issues/64182
=> We are having issues with llvm.sh

include/simdjson/compiler_check.h, src/generic/stage1/json_structural_indexer.h, src/generic/stage1/utf8_lookup4_algorithm.h, tests/dom/integer_tests.cpp
These are minor compatibility fixes for the branch [jkeiser/structural_indexer_step](https://github.com/simdjson/simdjson/pull/2052)
Merging this would not affect our main branch, it is a PR toward [jkeiser/structural_indexer_step](https://github.com/simdjson/simdjson/pull/2052)
cc @jkeiser
=> Standard compatibility fixes

benchmark/apple/apple_arm_events.h, benchmark/event_counter.h, benchmark/json_benchmark/run_json_benchmark.h
This should make it possible for Apple users to have performance counters (Apple Silicon).
=> Adding support for Apple event counters

include/simdjson/generic/numberparsing.h
As discussed in https://github.com/simdjson/simdjson/discussions/2048 I'm removing the fallback.
=> Removed number parsing fallback

doc/basics.md, doc/dom.md, doc/implementation-selection.md, doc/iterate_many.md, doc/ondemand_design.md, doc/parse_many.md
Fix https://github.com/simdjson/simdjson/issues/2058
=> Adding a few spaces (minor formatting)

README.md
Added link to gemmaJSON, a Nim JSON parser library based on simdjson bindings
=> Added link to Nim bindings

include/simdjson/generic/numberparsing.h, tests/ondemand/ondemand_number_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/2093
=> fix for issue 2093

include/simdjson/generic/numberparsing.h, include/simdjson/generic/ondemand/json_type.h, tests/ondemand/ondemand_number_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/2099
=> fix for issue 2099

README.md, doc/basics.md, include/simdjson/nonstd/string_view.hpp, singleheader/simdjson.cpp, singleheader/simdjson.h
=> This PR updates the backup string_view implementation. It also adds a  few comments to our README.md file.

.vscode/settings.json, doc/basics.md, include/simdjson/generic/ondemand/document-inl.h, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/field-inl.h, include/simdjson/generic/ondemand/field.h, include/simdjson/generic/ondemand/json_iterator.h, include/simdjson/generic/ondemand/value-inl.h, include/simdjson/generic/ondemand/value.h, include/simdjson/generic/ondemand/value_iterator.h, tests/ondemand/ondemand_readme_examples.cpp
It also updates the documentation.
=> This PR adds a convenience method (is_string) as well as a new method key_raw_json_token() to get the raw key token.

.github/ISSUE_TEMPLATE/bug_report.md, .vscode/settings.json, CMakeLists.txt, CONTRIBUTING.md, Doxyfile, doc/tape.md, fuzz/build_fuzzer_variants.sh, include/simdjson/dom/element.h, include/simdjson/generic/numberparsing.h, include/simdjson/generic/ondemand/field-inl.h, include/simdjson/generic/ondemand/json_iterator.h, include/simdjson/generic/ondemand/token_iterator.h, include/simdjson/simdjson.h, include/simdjson/simdjson_version.h, singleheader/simdjson.cpp, singleheader/simdjson.h, src/generic/stage1/json_structural_indexer.h
This will be the next release.
=> Release candidate (3.7.0)

include/simdjson/generic/ondemand/document-inl.h, include/simdjson/generic/ondemand/json_iterator-inl.h, include/simdjson/generic/ondemand/json_iterator.h, include/simdjson/generic/ondemand/token_iterator-inl.h, include/simdjson/generic/ondemand/token_iterator.h, include/simdjson/generic/ondemand/value_iterator-inl.h, include/simdjson/generic/ondemand/value_iterator.h, singleheader/simdjson.cpp, singleheader/simdjson.h, tests/ondemand/ondemand_document_stream_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/2137
=> verify issue 2137

.github/workflows/alpine.yml, .github/workflows/fuzzers.yml, .github/workflows/macos.yml, .github/workflows/msys2-clang.yml, .github/workflows/msys2.yml, .github/workflows/ubuntu20-checkperf.yml, .github/workflows/ubuntu20-gcc8.yml, .github/workflows/ubuntu20-noexcept.yml, .github/workflows/ubuntu20-nothread.yml, .github/workflows/ubuntu20-sani.yml, .github/workflows/ubuntu20.yml, .github/workflows/ubuntu22-clang13.yml, .github/workflows/ubuntu22-clang14.yml, .github/workflows/ubuntu22-cxx20.yml, .github/workflows/ubuntu22-gcc12.yml, .github/workflows/ubuntu22-gcc13.yml, .github/workflows/ubuntu22-glibcxxassertions.yml, .github/workflows/ubuntu22-threadsani.yml, .github/workflows/ubuntu22.yml, .github/workflows/vs17-noexcept-ci.yml
This PR is just meant as maintenance for our CI routines.
=> some updates to our CI

include/simdjson/implementation_detection.h
Fixes https://github.com/simdjson/simdjson/issues/2163
=> fix: adopt recommendation from issue 2163

include/simdjson/dom/document_stream-inl.h, include/simdjson/generic/ondemand/document_stream-inl.h, tests/dom/document_stream_tests.cpp, tests/ondemand/ondemand_document_stream_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/2170
=> issue 2170

include/simdjson/haswell/simd.h, include/simdjson/icelake/simd.h, include/simdjson/lasx/simd.h, include/simdjson/lsx/simd.h, include/simdjson/ppc64/simd.h, include/simdjson/westmere/simd.h, singleheader/simdjson.cpp
Fixes https://github.com/simdjson/simdjson/issues/2176
=> fix: satisfy a C++20 compiler warning

include/simdjson/dom/document_stream-inl.h, include/simdjson/generic/ondemand/document_stream-inl.h, tests/dom/document_stream_tests.cpp, tests/ondemand/ondemand_document_stream_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/2181
=> fix: solve issue 2181

.github/workflows/ubuntu24.yml, tests/ondemand/ondemand_misc_tests.cpp
Verification attempt for https://github.com/simdjson/simdjson/issues/2199
=> fix: add test for issue 2199

include/simdjson/dom/parser-inl.h, include/simdjson/dom/parser.h, include/simdjson/generic/ondemand/parser-inl.h, include/simdjson/generic/ondemand/parser.h, include/simdjson/internal/dom_parser_implementation.h, include/simdjson/portability.h
Related to https://github.com/simdjson/simdjson/issues/2207
cc @georgthegreat
=> Marking a few functions as pure (no side-effect)

.github/workflows/msys2-clang.yml, .github/workflows/msys2.yml, .github/workflows/ubuntu24.yml, .github/workflows/vs17-ci.yml, .github/workflows/vs17-clang-ci.yml
Related to https://github.com/simdjson/simdjson/issues/2207
cc @georgthegreat
=> chore: add RelWithDebInfo to our CI tests

tests/dom/basictests.cpp
Verifying https://github.com/simdjson/simdjson/issues/2213
=> adding test for issue 2213

doc/basics.md, tests/ondemand/ondemand_readme_examples.cpp
Related to https://github.com/simdjson/simdjson/discussions/2215
=> adding an example of value capture with std::string_view

HACKING.md, README.md, benchmark/partial_tweets/ondemand.h, doc/basics.md, doc/dom.md, doc/ondemand_design.md, doc/performance.md, examples/quickstart/CMakeLists.txt, include/simdjson/generic/ondemand/parser.h, src/generic/stage1/json_structural_indexer.h, tools/json2json.cpp
=> fix: use On-Demand throughout.

include/simdjson/generic/ondemand/amalgamated.h, include/simdjson/generic/ondemand/deserialize.h, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/value.h
Corrects a few small issues with recent commit by @the-moisrex 
See PR https://github.com/simdjson/simdjson/pull/2228
=> fix: correct small issues with deserialize

include/simdjson/arm64/bitmanipulation.h
Fixes https://github.com/simdjson/simdjson/pull/2251
=> adding missing undef silencer

doc/basics.md, include/simdjson/generic/ondemand/document.h
Fixes https://github.com/simdjson/simdjson/issues/2259
=> documentation for issue 2259 (clarifying)

.github/workflows/aarch64.yml, .github/workflows/cifuzz.yml, .github/workflows/fix-trailing-whitespace.yml, .github/workflows/msys2.yml, .github/workflows/ppc64.yml, .github/workflows/s390x.yml, .github/workflows/vs17-clang-ci-cxx20.yml
We are doing some work in the Builder development branch (builder_development_branch). This work is a bit speculative and not ready for the main branch.
However, the main branch benefited from an update to the CI setup and I believe we need to push it to builder_development_branch as well.
=> Builder development branch : update ci

doc/basics.md, include/simdjson/generic/ondemand/deserialize.h, include/simdjson/generic/ondemand/document-inl.h, include/simdjson/generic/ondemand/document.h, include/simdjson/generic/ondemand/document_stream-inl.h, singleheader/simdjson.cpp, tests/ondemand/CMakeLists.txt, tests/ondemand/ondemand_car_deserialization.cpp, tests/ondemand/ondemand_car_tag_invoke_deserialization.cpp, tests/ondemand/ondemand_custom_types_document_tests.cpp, tests/ondemand/ondemand_custom_types_tests.cpp, tests/ondemand/ondemand_readme_examples.cpp, tests/ondemand/ondemand_stl_types_tests.cpp
Let us try to document the new custom deserializer as well as we can.
=> C++20 custom deserializer: better documentation

doc/performance.md, tests/ondemand/ondemand_cacheline.cpp
The `need_allocation` function in our documentation is incorrect.
Thanks to @dan-robertson  for the analysis.
Fixes https://github.com/simdjson/simdjson/issues/2271
=> fixes issue 2271 (documentation bug)

CMakeLists.txt, Doxyfile, include/simdjson/simdjson_version.h, singleheader/simdjson.cpp
Fixes https://github.com/simdjson/simdjson/issues/2322
=> release candidate

include/simdjson/generic/ondemand/json_string_builder-inl.h
=> fix for pre C++17 if constexpr

benchmark/large_random/simdjson_ondemand.h, include/simdjson/generic/ondemand/json_builder.h, include/simdjson/generic/ondemand/std_deserialize.h, singleheader/simdjson.cpp
I am also adding some guarding so that we don't deserialize const or non-public members.
=> The syntax changed: ^E became ^^E.

doc/basics.md, include/simdjson/generic/ondemand/value_iterator-inl.h, tests/ondemand/ondemand_misc_tests.cpp, tests/ondemand/ondemand_readme_examples.cpp
Fixes https://github.com/simdjson/simdjson/issues/2354
=> fixing issue 2354: get_bool() on document with trailing spaces

CMakeLists.txt, Doxyfile, include/simdjson/simdjson_version.h, singleheader/simdjson.cpp
=> preparing patch release 3.12.3

doc/basics.md, tests/ondemand/ondemand_custom_types_document_tests.cpp, tests/test_macros.h
=> slightly better documentation of the C++20 features

dependencies/CMakeLists.txt, doc/dom.md, singleheader/CMakeLists.txt, tests/dom/basictests.cpp
Testing https://github.com/simdjson/simdjson/issues/2375
=> adding test for issue 2375

.github/workflows/emscripten.yml, CMakeLists.txt, doc/dom.md
=> Emscripten

doc/basics.md, doc/performance.md, include/simdjson/common_defs.h, include/simdjson/dom/array.h, include/simdjson/dom/element.h, include/simdjson/dom/object.h, include/simdjson/portability.h
Fixes https://github.com/simdjson/simdjson/issues/2387
=> clarifying NDEBUG usage

include/simdjson/dom/serialization-inl.h, include/simdjson/dom/serialization.h, tests/dom/json_path_tests.cpp, tests/dom/parse_many_test.cpp, tests/ondemand/ondemand_cacheline.cpp, tests/test_macros.h
This is a variant of https://github.com/simdjson/simdjson/pull/2408 by @toughengineer which fixes some compilation issues.
=> Sped up serialization fix

benchmark/CMakeLists.txt, benchmark/from/CMakeLists.txt, benchmark/from/benchmark_helpers.h, benchmark/from/car_helpers.h, benchmark/from/from_benchmark.cpp, doc/basics.md, include/simdjson/compiler_check.h, include/simdjson/convert.h, include/simdjson/generic/ondemand/array_iterator.h, include/simdjson/generic/ondemand/deserialize.h, include/simdjson/generic/ondemand/document_stream-inl.h, include/simdjson/generic/ondemand/document_stream.h, include/simdjson/generic/ondemand/parser-inl.h, include/simdjson/generic/ondemand/parser.h, include/simdjson/nonstd/string_view.hpp, singleheader/simdjson.cpp, tests/ondemand/ondemand_convert_tests.cpp
This modifies @the-moisrex's code slightly so that we can default on a thread-local parser. This should drastically improve performance in some cases.
=> introducing a thread-local parser

include/simdjson/dom/parser-inl.h, include/simdjson/dom/parser.h
=> Use std::string_view in parser.load function

doc/builder.md, include/simdjson/generic/ondemand/json_string_builder-inl.h, tests/builder/builder_string_builder_tests.cpp
Fixes https://github.com/simdjson/simdjson/issues/2424
=> fix issue 2424

include/simdjson/generic/ondemand/json_builder.h
=> removing leftover <experimental/...>

doc/basics.md, doc/builder.md, doc/dom.md
Fixes a few typos in documentation.
=> fix some typos

.github/workflows/ubuntu24-noexcept.yml, .github/workflows/ubuntu24-nothread.yml, doc/builder.md, include/simdjson/generic/ondemand/json_string_builder-inl.h, include/simdjson/generic/ondemand/json_string_builder.h, tests/builder/builder_string_builder_tests.cpp
=> adding keys as templates in builder

include/simdjson/generic/ondemand/json_string_builder-inl.h, tests/builder/builder_string_builder_tests.cpp
Fixed typo/missing keyword.
Type of change
=> Fixed `string_builder::operator std::string()`

doc/builder.md, tests/builder/static_reflection_comprehensive_tests.cpp
Minor PR that would go to `francisco/extract_from`. Mostly I just add some documentation.
=> minor tweaks

.github/workflows/aarch64.yml
Update workflow name to correctly reflect its architecture and [compiler version](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) in GitHub Actions.
=> Update workflow name to Ubuntu aarch64 (GCC 13)
